"""Generate docs/architecture/quality-tooling-map.md from tooling/quality/tooling_manifest.yaml.

Usage:
    python tooling/quality/generate_quality_tooling_map.py [--check]

Options:
    --check   Verify the generated file is up-to-date without writing. Exits 1 if stale.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML required: pip install PyYAML", file=sys.stderr)
    sys.exit(1)

MANIFEST = Path("tooling/quality/tooling_manifest.yaml")
OUTPUT = Path("docs/architecture/quality-tooling-map.md")

TYPE_ORDER = ["gates", "validators", "self_heals", "schema_sources", "agent_skills", "hooks", "bpa_rules", "reference_docs"]

TYPE_LABELS = {
    "gates": "Gates (Orchestration Entry Points)",
    "validators": "Validators",
    "self_heals": "Self-Heal Scripts",
    "schema_sources": "Schema Sources",
    "agent_skills": "Agent Skills",
    "hooks": "PostToolUse Hooks",
    "bpa_rules": "BPA Rule Sets",
    "reference_docs": "Reference Documentation",
}

SCOPE_EMOJI = {
    "report": "report",
    "model": "model",
    "kpi": "kpi",
    "governance": "gov",
    "all": "all",
}


def _badge(value: str, field: str) -> str:
    return f"`{value}`"


def _entry_row(entry: dict) -> str:
    id_ = entry.get("id", "")
    entrypoint = entry.get("entrypoint", "")
    scope = entry.get("scope", "")
    runs_in = entry.get("runs_in", "")
    docs = entry.get("docs", "")
    fixes = entry.get("fixes")
    summary = entry.get("summary_mode")

    link = f"[`{entrypoint}`]({entrypoint})" if entrypoint else ""
    fixes_str = ", ".join(f"`{f}`" for f in fixes) if fixes else ""
    extras: list[str] = []
    if fixes_str:
        extras.append(f"fixes: {fixes_str}")
    if summary:
        extras.append(f"summary: `{summary}`")

    extra_str = "; ".join(extras)
    return f"| `{id_}` | {link} | `{scope}` | `{runs_in}` | {docs}{(' -- ' + extra_str) if extra_str else ''} |"


def generate(manifest_path: Path) -> str:
    with open(manifest_path, encoding="utf-8") as f:
        data = yaml.safe_load(f)

    version = data.get("version", "?")
    lines: list[str] = [
        "# Quality Tooling Map",
        "",
        "> **Auto-generated** from [`tooling/quality/tooling_manifest.yaml`](../../tooling/quality/tooling_manifest.yaml).",
        f"> Manifest version: {version}. Regenerate with `python tooling/quality/generate_quality_tooling_map.py`.",
        "> Do NOT edit this file manually.",
        "",
        "## Flowchart",
        "",
        "```mermaid",
        "flowchart LR",
        "  authoring[Authoring] --> detect[Detect]",
        "  detect --> classify[Classify]",
        "  classify --> fix[Deterministic Fix]",
        "  fix --> revalidate[Revalidate]",
        "  revalidate -->|still failing| classify",
        "  revalidate -->|green| learn[Learn]",
        "  learn --> package[Reusable Toolkit]",
        "```",
        "",
    ]

    for section_key in TYPE_ORDER:
        entries = data.get(section_key)
        if not entries:
            continue
        label = TYPE_LABELS.get(section_key, section_key.replace("_", " ").title())
        lines.append(f"## {label}")
        lines.append("")
        lines.append("| ID | Entrypoint | Scope | Runs In | Description |")
        lines.append("|---|---|---|---|---|")
        for entry in entries:
            lines.append(_entry_row(entry))
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by `generate_quality_tooling_map.py`. Edit `tooling_manifest.yaml` to change this file.*")
    lines.append("")

    return "\n".join(lines)


def _sha(content: str) -> str:
    return hashlib.md5(content.encode()).hexdigest()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check only; exit 1 if stale.")
    args = parser.parse_args(argv)

    if not MANIFEST.exists():
        print(f"Manifest not found: {MANIFEST}", file=sys.stderr)
        return 1

    content = generate(MANIFEST)

    if args.check:
        if OUTPUT.exists() and _sha(OUTPUT.read_text(encoding="utf-8")) == _sha(content):
            print("quality-tooling-map.md is up to date.")
            return 0
        print("quality-tooling-map.md is STALE. Run generate_quality_tooling_map.py to refresh.", file=sys.stderr)
        return 1

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Written: {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
