/**
 * Tailwind CSS configuration for the Open-Source Stack (Evidence.dev).
 *
 * Maps Evidence design token classes to brand CSS custom properties
 * generated by the brand derivation pipeline (core/brand/derivations/).
 *
 * Usage in Evidence pages:
 *   fill-primary       → SVG/chart fill using primary brand color
 *   text-brand-header  → Heading text color
 *   bg-surface         → Card / panel background
 *   text-positive      → Positive signal (green)
 *   text-negative      → Negative signal (red)
 *   text-warning       → Warning signal (amber)
 *
 * Source of truth: products/open_source_stack/themes/variables.css
 * Generated by:    tooling/brand/derive_brand_artifacts.py --showcase <name>
 */

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['../evidence_app/**/*.{html,md,svelte}'],
  theme: {
    extend: {
      colors: {
        // Primary brand colors
        primary:          "var(--brand-color-primary)",
        secondary:        "var(--brand-color-secondary)",
        "primary-subtle": "var(--brand-color-primary-subtle)",

        // Semantic signal colors
        positive:         "var(--brand-color-positive)",
        negative:         "var(--brand-color-negative)",
        warning:          "var(--brand-color-warning)",
        neutral:          "var(--brand-color-neutral)",
        "positive-bg":    "var(--brand-color-positive-bg)",
        "negative-bg":    "var(--brand-color-negative-bg)",
        "warning-bg":     "var(--brand-color-warning-bg)",

        // Neutral scale
        "neutral-50":     "var(--brand-neutral-50)",
        "neutral-100":    "var(--brand-neutral-100)",
        "neutral-200":    "var(--brand-neutral-200)",
        "neutral-400":    "var(--brand-neutral-400)",
        "neutral-700":    "var(--brand-neutral-700)",
        "neutral-900":    "var(--brand-neutral-900)",

        // Semantic role aliases — used in core/templates/evidence_page_template.md
        surface:           "var(--brand-color-surface)",
        background:        "var(--brand-color-background)",
        border:            "var(--brand-color-border)",
        muted:             "var(--brand-color-muted)",
        body:              "var(--brand-color-body)",
        "brand-header":    "var(--brand-color-heading)",
      },
      fill: {
        primary: "var(--brand-color-primary)",
      },
      fontFamily: {
        brand: ["var(--brand-font-primary)"],
        mono:  ["var(--brand-font-mono)"],
      },
      fontSize: {
        "brand-xs":    "var(--brand-type-xs)",
        "brand-sm":    "var(--brand-type-sm)",
        "brand-md":    "var(--brand-type-md)",
        "brand-lg":    "var(--brand-type-lg)",
        "brand-xl":    "var(--brand-type-xl)",
        "brand-2xl":   "var(--brand-type-2xl)",
        "brand-3xl":   "var(--brand-type-3xl)",
        "kpi-value":   "var(--brand-type-kpi-value)",
        "kpi-label":   "var(--brand-type-kpi-label)",
        "kpi-delta":   "var(--brand-type-kpi-delta)",
        "chart-title": "var(--brand-type-chart-title)",
        "axis-label":  "var(--brand-type-axis-label)",
      },
      spacing: {
        "brand-xs":  "var(--brand-spacing-xs)",
        "brand-sm":  "var(--brand-spacing-sm)",
        "brand-md":  "var(--brand-spacing-md)",
        "brand-lg":  "var(--brand-spacing-lg)",
        "brand-xl":  "var(--brand-spacing-xl)",
      },
      borderRadius: {
        "brand-sm": "var(--brand-radius-sm)",
        "brand-md": "var(--brand-radius-md)",
        "brand-lg": "var(--brand-radius-lg)",
      },
      boxShadow: {
        "brand-low":    "var(--brand-shadow-low)",
        "brand-medium": "var(--brand-shadow-medium)",
        "brand-high":   "var(--brand-shadow-high)",
      },
    },
  },
  plugins: [],
};
