/// Cost of goods sold at location-SKU-month grain
table fact_cogs
	lineageTag: fbabdae4-996d-53e7-a09a-38e4d9ff956e
	column DateKey
		dataType: Int64
		sourceColumn: DateKey
		summarizeBy: none
	column OrgKey
		dataType: Int64
		sourceColumn: OrgKey
		summarizeBy: none
	column ProductKey
		dataType: Int64
		sourceColumn: ProductKey
		summarizeBy: none
	column 'COGS Amount'
		dataType: Decimal
		sourceColumn: COGS Amount
		summarizeBy: none
	partition fact_cogs = m
		mode: import
		source =
			let
				Source = Folder.Files(GoldDataPath & "/facts/fact_cogs"),
				FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
				FirstFile = FilteredFiles{0}[Content],
				ParquetData = Parquet.Document(FirstFile)
			in
				ParquetData
