/// Promotion dimension (type, mechanic, date range) for promo effectiveness.
/// Promo ROI, incremental sales, and cannibalization analysis.
table dim_promo
	lineageTag: f8543909-2484-4842-befd-aa21037030bc

	column PromoKey
		dataType: int64
		isHidden
		lineageTag: 27939d1d-d3c1-4c7d-9362-8bd61a9b85e4
		summarizeBy: none
		sourceColumn: PromoKey

	column PromoCode
		dataType: string
		lineageTag: 156ada94-bf4f-455b-815d-179ccd8ad3f2
		sourceColumn: PromoCode

	column PromoName
		dataType: string
		lineageTag: db4f95e0-66aa-4741-b76b-6d9b7babdd96
		sourceColumn: PromoName

	column 'Promo Type'
		dataType: string
		lineageTag: d9fbd171-0626-4fe7-99f4-570c43a4997a
		sourceColumn: Promo Type

	column 'Promo Mechanic'
		dataType: string
		lineageTag: 01a8aa8a-f619-4a04-9df7-b66c4508ff02
		sourceColumn: Promo Mechanic

	column 'Start DateKey'
		dataType: int64
		lineageTag: 92b6b59c-9828-436b-a759-e27e0a7dc0ea
		summarizeBy: none
		sourceColumn: Start DateKey

	column 'End DateKey'
		dataType: int64
		lineageTag: 04eb0c62-4ab1-4c64-99b2-8a7ddb1431a1
		summarizeBy: none
		sourceColumn: End DateKey

	column 'Discount %'
		dataType: double
		lineageTag: 35606087-a7d3-42e6-b343-0658e15fb4d0
		summarizeBy: none
		sourceColumn: Discount %

	hierarchy Promo
		lineageTag: 19a4f664-133f-4659-b1f3-5fe16bafc5c6

		level 'Promo Type'
			lineageTag: 9c0ba844-2985-4c03-ab6d-dec0256e98f3
			column: 'Promo Type'

		level 'Promo Mechanic'
			lineageTag: 06227da2-204e-4741-9fa8-f81a012ab3a1
			column: 'Promo Mechanic'

		level 'Promo Name'
			lineageTag: 77a8e18e-e260-482e-8cd4-27bf8d2eb898
			column: PromoName

	partition dim_promo = m
		mode: import
		source =
				let
					Source = Folder.Files(GoldDataPath & "/dimensions/dim_promo"),
					FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
					FirstFile = FilteredFiles{0}[Content],
					ParquetData = Parquet.Document(FirstFile)
				in
					ParquetData

