/// Support case facts (SLA, FCR, handle time, escalation, backlog).
/// Case performance and SLA reporting.
table fact_support_cases
	lineageTag: c1534537-4466-4ca0-9b8b-7e6f1afce49f

	column DateKey
		dataType: int64
		lineageTag: e44a3aa7-8e46-4e0c-b855-ff0dec1346a7
		summarizeBy: none
		sourceColumn: DateKey

	column OrgKey
		dataType: int64
		lineageTag: 3083121a-5e19-4639-9677-d85180625413
		summarizeBy: none
		sourceColumn: OrgKey

	column QueueKey
		dataType: int64
		lineageTag: 8ca98916-8167-4bc9-85af-5ecf752cf738
		summarizeBy: none
		sourceColumn: QueueKey

	column IssueKey
		dataType: int64
		lineageTag: 77c91965-7587-4f44-9dd2-6bbea57203ce
		summarizeBy: none
		sourceColumn: IssueKey

	column 'SLA Met Flag'
		dataType: boolean
		lineageTag: efbd0eee-1359-4779-b234-08fa8d6ec523
		sourceColumn: SLA Met Flag

	column 'FCR Flag'
		dataType: boolean
		lineageTag: 1b3c87bc-dba7-4962-85ad-3adbfb8b98d6
		sourceColumn: FCR Flag

	column 'Handle Time Minutes'
		dataType: double
		lineageTag: 48082856-7282-4888-a6df-5aa7365bb3cc
		summarizeBy: none
		sourceColumn: Handle Time Minutes

	column 'Escalation Flag'
		dataType: boolean
		lineageTag: 6d580d0f-c477-4e5d-981d-c6519f0e9bcc
		sourceColumn: Escalation Flag

	column 'Backlog Flag'
		dataType: boolean
		lineageTag: 39bfc68a-00c8-4341-aaf1-25b050c1379d
		sourceColumn: Backlog Flag

	column 'Open Case Flag'
		dataType: boolean
		lineageTag: 40e056d3-c278-41f6-99a4-afa72d3da39d
		sourceColumn: Open Case Flag

	partition fact_support_cases = m
		mode: import
		source =
				let
					Source = Folder.Files(GoldDataPath & "/facts/fact_support_cases"),
					FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
					FirstFile = FilteredFiles{0}[Content],
					ParquetData = Parquet.Document(FirstFile)
				in
					ParquetData

