/// Product dimension with ABC/XYZ classification for supply chain analysis
table dim_product
	lineageTag: 78e6f7e8-1cc9-5bdb-9b51-81c79bd8a35d
	column ProductKey
		dataType: Int64
		sourceColumn: ProductKey
		summarizeBy: none
		isHidden
	column ProductCode
		dataType: String
		sourceColumn: ProductCode
		summarizeBy: none
	column ProductName
		dataType: String
		sourceColumn: ProductName
		summarizeBy: none
	column Category
		dataType: String
		sourceColumn: Category
		summarizeBy: none
	column Subcategory
		dataType: String
		sourceColumn: Subcategory
		summarizeBy: none
	column ABC_Class
		dataType: String
		sourceColumn: ABC_Class
		summarizeBy: none
	column XYZ_Class
		dataType: String
		sourceColumn: XYZ_Class
		summarizeBy: none
	partition dim_product = m
		mode: import
		source =
			let
				Source = Folder.Files(GoldDataPath & "/dimensions/dim_product"),
				FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
				FirstFile = FilteredFiles{0}[Content],
				ParquetData = Parquet.Document(FirstFile)
			in
				ParquetData

	hierarchy 'Product Hierarchy'
		lineageTag: 3f04d64f-f7dc-5375-a193-e2cc0ed84578
		level Category
			column: Category
		level Subcategory
			column: Subcategory
		level ProductName
			column: ProductName

	hierarchy 'ABC/XYZ Classification'
		lineageTag: e1fa68cd-2b93-5893-b8a3-65d0fd4fb0eb
		level ABC_Class
			column: ABC_Class
		level XYZ_Class
			column: XYZ_Class
		level ProductName
			column: ProductName
