/// User-to-Org mapping table for Row-Level Security.
table security_user_org
	lineageTag: 82dd51d6-39bd-5b5f-a66f-7717a38bd745

	column UserPrincipalName
		dataType: String
		sourceColumn: UserPrincipalName
		summarizeBy: none

	column OrgKey
		dataType: Int64
		sourceColumn: OrgKey
		summarizeBy: none
		isHidden

	partition security_user_org = m
		mode: import
		source =
			let
				Source = Folder.Files(GoldDataPath & "/security_user_org"),
				FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
				FirstFile = FilteredFiles{0}[Content],
				ParquetData = Parquet.Document(FirstFile)
			in
				ParquetData
