/**
 * Brand Spec API — PATCH for writing brand overrides to core/brand/overrides.yaml.
 *
 * Does NOT overwrite BrandSpec.schema.yaml (that is a schema/reference file).
 * Instead writes to core/brand/overrides.yaml which is consumed by downstream tools.
 */

import { join } from 'node:path';
import { writeFileSync } from 'node:fs';
import { requireAuth } from '@/lib/auth/session';
import { apiSuccess, apiError } from '@/lib/api/response';
import { ErrorCode } from '@/lib/api/error-codes';

interface BrandSpecOverrides {
  primary?: string;
  background?: string;
  surface?: string;
  fontFamily?: string;
}

export async function PATCH(request: Request) {
  const [, authError] = await requireAuth();
  if (authError) return authError;

  let body: BrandSpecOverrides;
  try {
    body = (await request.json()) as BrandSpecOverrides;
  } catch {
    return apiError(ErrorCode.VALIDATION_ERROR, 'Invalid JSON body', 400);
  }

  const primary    = body.primary    ?? '#00D4AA';
  const background = body.background ?? '#0d0e10';
  const surface    = body.surface    ?? '#131416';
  const fontFamily = body.fontFamily ?? 'Inter';

  const yaml = [
    '# Studio Brand Overrides — generated by Brand Lab Tweaks',
    `primary: "${primary}"`,
    `background: "${background}"`,
    `surface: "${surface}"`,
    `fontFamily: "${fontFamily}"`,
    '',
  ].join('\n');

  const overridesPath = join(process.cwd(), '..', 'core', 'brand', 'overrides.yaml');

  try {
    writeFileSync(overridesPath, yaml, 'utf-8');
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Failed to write overrides.yaml';
    return apiError(ErrorCode.INTERNAL_ERROR, message, 500);
  }

  return apiSuccess({ ok: true });
}
