table ProductSubcategory
	lineageTag: b248cf36-d10a-430e-833e-29a5c338482c

	column ProductSubcategoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9a66a2b2-e754-44ed-9bb7-50435ff564f6
		summarizeBy: none
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column ProductSubcategory
		dataType: string
		lineageTag: 379224b8-82b4-4d83-861f-e91902ec83ae
		summarizeBy: none
		sourceColumn: ProductSubcategory

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column ProductCategoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 79314501-7898-4a25-9e44-9d35591554c2
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		annotation SummarizationSetBy = Automatic

	partition ProductSubcategory-aa5c8a99-d0a5-480c-bacf-c3b1c9950bbc = m
		mode: import
		source =
				let
				    Source = Access.Database(File.Contents("C:\Users\owend\Documents\ContosoSalesV31_64bit.accdb")),
				    _DimProductSubcategory = Source{[Schema="",Item="DimProductSubcategory"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(_DimProductSubcategory,{"ProductSubcategoryLabel", "ProductSubcategoryDescription", "ETLLoadID", "LoadDate", "UpdateDate"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"ProductSubcategoryName", "ProductSubcategory"}})
				in
				    #"Renamed Columns"

	annotation ColumnsMetadata = {"Columns":[{"Name":"ProductSubcategoryKey","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimProductSubcategory.{ProductSubcategoryKey,0}"},{"Name":"ProductSubcategory","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimProductSubcategory.{ProductSubcategoryName,2}"},{"Name":"ProductCategoryKey","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimProductSubcategory.{ProductCategoryKey,4}"}]}

	annotation PBI_ResultType = Table

