#!/usr/bin/env python3
"""
check_storyline.py — govern the guided use-case-to-decision storyline.

The storyline is what the report/story generators render (tooling/storyline/derive_storyline.py).
This gate keeps the storyline structurally sound so "each visual answers a question of the page's
decision, and page 1 hands off to page 2" is enforced, not just conventional:

1. Every populated page carries a `decision_question` — the spine each page answers.
2. Every `component_30s` visual carries an explicit `question` — the question that visual answers
   (its `message` is the answer). This makes the storyline first-class rather than inferred.
3. Handoff: a use case with both pages has a decision_question on each — page 1 (are we OK?) hands
   off to page 2 (what do we do?).
4. The generated storyboard `docs/architecture/use_case_storylines.md` is in sync with the deriver
   (no stale doc), mirroring the reference_graph gate.

Semantic laddering (does the question truly serve the decision?) is left to human/LLM review — this
gate enforces the machine-checkable structure that makes the ladder possible.

Usage:
    python tooling/validation/check_storyline.py            # advisory report
    python tooling/validation/check_storyline.py --strict   # any violation = exit 1
"""
from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:  # pragma: no cover
    print("ERROR: pyyaml not installed.", file=sys.stderr)
    sys.exit(1)

REPO = Path(__file__).resolve().parents[2]
STORYBOARD = REPO / "docs/architecture/use_case_storylines.md"


def _deriver():
    spec = importlib.util.spec_from_file_location(
        "derive_storyline", REPO / "tooling/storyline/derive_storyline.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _chart_fit_mod():
    spec = importlib.util.spec_from_file_location(
        "chart_question_fit", REPO / "tooling/storyline/chart_question_fit.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def chart_fit_advisories(bracket: dict[str, Any]) -> list[str]:
    """ADVISORY (never a hard failure): a static BI visual can only *generically* fit its question.
    Surface where the chosen visual type is an unusual match for the question intent, so the designer
    knows the user must read the chart themselves — not a defect, an awareness note (see the PBI-vs-
    dynamic distinction in ADR-0017 / RENDER_GATED_RUNBOOK)."""
    fit = _chart_fit_mod()
    ucid = bracket.get("id", "?")
    ux = bracket.get("ux_layout_rules", {}) or {}
    out: list[str] = []
    for pk in ("page_1_summary", "page_2_execution"):
        page = ux.get(pk) or {}
        if not isinstance(page, dict):
            continue
        for i, c in enumerate(page.get("component_30s") or [], 1):
            if (c.get("question") or "").strip():
                ok, reason = fit.fits(c.get("question"), c.get("visual_type"))
                if not ok:
                    out.append(f"{ucid}/{pk} 30s#{i}: {reason}")
    return out


def check_bracket(bracket: dict[str, Any]) -> list[str]:
    """Structural storyline checks for one bracket."""
    ucid = bracket.get("id", "?")
    ux = bracket.get("ux_layout_rules", {}) or {}
    problems: list[str] = []
    pages = [(k, ux.get(k)) for k in ("page_1_summary", "page_2_execution")
             if isinstance(ux.get(k), dict) and ux.get(k)]
    for pk, page in pages:
        if not (page.get("decision_question") or "").strip():
            problems.append(f"{ucid}/{pk}: no decision_question (storyline spine missing)")
        for i, c in enumerate(page.get("component_30s") or [], 1):
            if not (c.get("question") or "").strip():
                problems.append(
                    f"{ucid}/{pk} 30s#{i} ({c.get('kpi_id')}): no `question` "
                    f"(each visual must answer a stated question)")
    # handoff: a 2-page-lead use case needs a decision on both
    if len(pages) == 2:
        p1, p2 = pages[0][1], pages[1][1]
        if (p1.get("decision_question") and not p2.get("decision_question")):
            problems.append(f"{ucid}: page-1→page-2 handoff broken (page 2 has no decision_question)")
    return problems


def render_out_of_sync() -> str | None:
    """Return a message if the generated storyboard doc is stale, else None."""
    mod = _deriver()
    kpi_domains, kpi_keys, action_related = mod._kpi_domains(), mod._kpi_keys(), mod._action_related()
    header = ("# Use-case storylines (derived)\n\n"
              "> Generated by `tooling/storyline/derive_storyline.py` from the governed brackets — "
              "deterministic, no LLM. Each visual answers a question; the questions ladder to the "
              "page's decision, and page 1 hands off to page 2 to cover the whole use-case-to-decision arc.\n")
    parts = [header]
    for b in mod.load_brackets(None):
        parts.append(mod.storyboard(yaml.safe_load(b.read_text(encoding="utf-8")) or {},
                                    kpi_domains, kpi_keys, action_related))
    expected = "\n".join(parts)
    actual = STORYBOARD.read_text(encoding="utf-8") if STORYBOARD.exists() else ""
    if actual != expected:
        return ("docs/architecture/use_case_storylines.md is stale — regenerate with: "
                "python tooling/storyline/derive_storyline.py --render docs/architecture/use_case_storylines.md")
    return None


def main() -> int:
    ap = argparse.ArgumentParser(description="Govern the use-case storyline structure")
    ap.add_argument("--strict", action="store_true")
    args = ap.parse_args()

    total = 0
    advisories: list[str] = []
    for b in sorted(REPO.glob("core/usecases/**/UseCase_Bracket.yaml")):
        bracket = yaml.safe_load(b.read_text(encoding="utf-8")) or {}
        for p in check_bracket(bracket):
            print(f"  ⚠ {p}")
            total += 1
        advisories += chart_fit_advisories(bracket)
    sync = render_out_of_sync()
    if sync:
        print(f"  ⚠ {sync}")
        total += 1

    n = len(list(REPO.glob("core/usecases/**/UseCase_Bracket.yaml")))
    if advisories:
        print(f"\nchart-fit advisories ({len(advisories)}) — static BI can only generically fit the "
              f"question; the user reads the chart. Not failures:")
        for a in advisories:
            print(f"  ℹ {a}")
    print(f"\ncheck_storyline: {n} use cases · {total} violation(s) · {len(advisories)} chart-fit advisory(ies).")
    if args.strict and total:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
