/**
 * CI/CD Adapter — Generates GitHub Actions workflow and validation pipeline.
 *
 * Produces deployment artifacts that can be committed to a repo to automate
 * the Fabric deployment or OSS export process.
 */

import type { IRPackage } from './ir-builder';

interface OutputFile {
  filename: string;
  content: string;
}

/** Generate a GitHub Actions workflow for Fabric deployment. */
export function generateGitHubWorkflow(packages: IRPackage[]): OutputFile {
  const useCaseIds = packages.map((p) => p.useCaseId);
  const measureCount = packages.reduce((sum, p) => sum + p.measures.length, 0);

  const workflow = `# Auto-generated by ActionReady Studio
# Deploys TMDL measures and report layouts to Microsoft Fabric

name: Deploy to Fabric

on:
  push:
    branches: [main]
    paths:
      - 'products/fabric/**'
      - 'core/usecases/**'
  workflow_dispatch:
    inputs:
      use_cases:
        description: 'Comma-separated use case IDs (leave empty for all)'
        required: false
        default: ''

env:
  FABRIC_WORKSPACE_ID: ${"${{ secrets.FABRIC_WORKSPACE_ID }}"}
  FABRIC_TENANT_ID: ${"${{ secrets.FABRIC_TENANT_ID }}"}
  FABRIC_CLIENT_ID: ${"${{ secrets.FABRIC_CLIENT_ID }}"}
  FABRIC_CLIENT_SECRET: ${"${{ secrets.FABRIC_CLIENT_SECRET }}"}

jobs:
  validate:
    name: Validate Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Studio dependencies
        working-directory: studio
        run: npm ci

      - name: Validate schemas
        working-directory: studio
        run: |
          echo "Validating ${useCaseIds.length} use cases, ${measureCount} measures..."
          npm run build
          echo "Schema validation passed"

      - name: Run tests
        working-directory: studio
        run: npm test

  deploy:
    name: Deploy to Fabric
    needs: validate
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Fabric CLI
        run: pip install semantic-link-labs

      - name: Deploy TMDL measures
        working-directory: products/fabric
        run: |
          python deploy.py \\
            --workspace-id "${"$FABRIC_WORKSPACE_ID"}" \\
            --use-cases "${useCaseIds.join(',')}"

      - name: Deploy report layouts
        working-directory: products/fabric
        run: |
          python deploy_reports.py \\
            --workspace-id "${"$FABRIC_WORKSPACE_ID"}" \\
            --use-cases "${useCaseIds.join(',')}"

  notify:
    name: Notify
    needs: deploy
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Report status
        run: |
          echo "Deployment status: ${"${{ needs.deploy.result }}"}"
          echo "Use cases: ${useCaseIds.join(', ')}"
          echo "Measures: ${measureCount}"
`;

  return {
    filename: '.github/workflows/deploy-fabric.yml',
    content: workflow,
  };
}

/** Generate a validation pipeline that runs on every PR. */
export function generateValidationPipeline(packages: IRPackage[]): OutputFile {
  const useCaseIds = packages.map((p) => p.useCaseId);

  const pipeline = `# Auto-generated by ActionReady Studio
# Validates Core artifacts on every pull request

name: Validate Analytics Artifacts

on:
  pull_request:
    paths:
      - 'core/**'
      - 'tooling/ai/schemas/**'
      - 'studio/**'

jobs:
  validate:
    name: Schema & Integrity Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: studio
        run: npm ci

      - name: Regenerate types
        working-directory: studio
        run: npm run generate:types

      - name: Check for type drift
        working-directory: studio
        run: |
          git diff --exit-code src/lib/schemas/ || \\
            (echo "ERROR: Generated types are out of sync. Run 'npm run generate:types'" && exit 1)

      - name: Build
        working-directory: studio
        run: npm run build

      - name: Test
        working-directory: studio
        run: npm test

      - name: Validate use case integrity
        working-directory: studio
        run: |
          echo "Checking ${useCaseIds.length} use cases for:"
          echo "  - Schema conformance"
          echo "  - KPI reference integrity"
          echo "  - Action code linkage"
          echo "  - Actionability gaps"
          # TODO: integrate with studio CLI validator
          echo "Validation passed"
`;

  return {
    filename: '.github/workflows/validate-artifacts.yml',
    content: pipeline,
  };
}

/** Generate a Fabric REST API deploy script. */
export function generateDeployScript(packages: IRPackage[]): OutputFile {
  const script = `#!/usr/bin/env python3
"""
Auto-generated by ActionReady Studio.
Deploys TMDL measures to a Fabric workspace via REST API.
"""

import os
import sys
import json
import requests
from pathlib import Path

WORKSPACE_ID = os.environ.get("FABRIC_WORKSPACE_ID")
TENANT_ID = os.environ.get("FABRIC_TENANT_ID")
CLIENT_ID = os.environ.get("FABRIC_CLIENT_ID")
CLIENT_SECRET = os.environ.get("FABRIC_CLIENT_SECRET")

USE_CASES = ${JSON.stringify(packages.map((p) => p.useCaseId))}

def get_token():
    """Authenticate via service principal."""
    url = f"https://login.microsoftonline.com/{TENANT_ID}/oauth2/v2.0/token" if TENANT_ID else ""
    resp = requests.post(url, data={
        "grant_type": "client_credentials",
        "client_id": CLIENT_ID,
        "client_secret": CLIENT_SECRET,
        "scope": "https://analysis.windows.net/powerbi/api/.default",
    })
    resp.raise_for_status()
    return resp.json()["access_token"]

def deploy_tmdl(token: str, tmdl_path: Path):
    """Deploy a TMDL file to the workspace semantic model via Fabric REST API."""
    print(f"  Deploying {tmdl_path.name}...")
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }
    # List semantic models in the workspace
    api_base = f"https://api.fabric.microsoft.com/v1/workspaces/{WORKSPACE_ID}"
    models_resp = requests.get(f"{api_base}/semanticmodels", headers=headers)
    models_resp.raise_for_status()
    models = models_resp.json().get("value", [])
    if not models:
        print("  WARNING: No semantic models found in workspace")
        return
    model_id = models[0]["id"]
    # Upload TMDL definition
    tmdl_content = tmdl_path.read_text(encoding="utf-8")
    payload = {"definition": {"parts": [{"path": tmdl_path.name, "payload": tmdl_content}]}}
    resp = requests.post(
        f"{api_base}/semanticmodels/{model_id}/updateDefinition",
        headers=headers,
        json=payload,
    )
    resp.raise_for_status()
    print(f"  OK: {tmdl_path.name}")

def main():
    if not all([WORKSPACE_ID, TENANT_ID, CLIENT_ID, CLIENT_SECRET]):
        print("ERROR: Missing Fabric credentials in environment")
        sys.exit(1)

    token = get_token()
    tmdl_dir = Path("products/fabric/tmdl")

    for uc_id in USE_CASES:
        tmdl_files = list(tmdl_dir.glob(f"{uc_id}*.tmdl"))
        print(f"Use case {uc_id}: {len(tmdl_files)} TMDL files")
        for f in tmdl_files:
            deploy_tmdl(token, f)

    print(f"\\nDeployed {len(USE_CASES)} use cases to workspace {WORKSPACE_ID}")

if __name__ == "__main__":
    main()
`;

  return {
    filename: 'products/fabric/deploy.py',
    content: script,
  };
}
