/// Calendar dimension with fiscal hierarchy (Fiscal Year > Quarter > Month > Date).
table dim_date
	lineageTag: 6a83a514-fef3-41fb-ba4a-6b94f905e53c

	column DateKey
		dataType: Int64
		sourceColumn: DateKey
		summarizeBy: none
		isHidden

	column Date
		dataType: DateTime
		sourceColumn: Date
		summarizeBy: none

	column Year
		dataType: Int64
		sourceColumn: Year
		summarizeBy: none

	column Quarter
		dataType: String
		sourceColumn: Quarter
		summarizeBy: none

	column Month
		dataType: String
		sourceColumn: Month
		summarizeBy: none

	column MonthNumber
		dataType: Int64
		sourceColumn: MonthNumber
		summarizeBy: none

	column CalendarYearMonth
		dataType: String
		sourceColumn: CalendarYearMonth
		summarizeBy: none

	column Week
		dataType: String
		sourceColumn: Week
		summarizeBy: none

	partition dim_date = m
		mode: import
		source =
			let
				Source = Folder.Files(GoldDataPath & "/dimensions/dim_date"),
				FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
				FirstFile = FilteredFiles{0}[Content],
				ParquetData = Parquet.Document(FirstFile),
				WithCalendarYearMonth = Table.AddColumn(ParquetData, "CalendarYearMonth", each Date.ToText(Date.From([Date]), "yyyy-MM"), type text)
			in
				WithCalendarYearMonth

	hierarchy 'Calendar'
		lineageTag: 0ec04f63-07ef-587b-9a60-ddb21de22d22
		level Year
			column: Year
		level Quarter
			column: Quarter
		level Month
			column: Month
		level Date
			column: Date

	hierarchy 'Week Calendar'
		lineageTag: b1d10635-c888-56d0-b8d8-917e3033d921
		level Year
			column: Year
		level Week
			column: Week
		level Date
			column: Date
