/// Invoice-line sales (net sales, quantity, price, COGS) with plan and prior year.
table fact_sales
	lineageTag: c60cd56e-7c63-4272-b9c9-160833889c29

	column DateKey
		dataType: Int64
		sourceColumn: DateKey
		summarizeBy: none

	column OrgKey
		dataType: Int64
		sourceColumn: OrgKey
		summarizeBy: none

	column ProductKey
		dataType: Int64
		sourceColumn: ProductKey
		summarizeBy: none

	column CustomerKey
		dataType: Int64
		sourceColumn: CustomerKey
		summarizeBy: none

	column PromoKey
		dataType: Int64
		sourceColumn: PromoKey
		summarizeBy: none

	column 'Promo Flag'
		dataType: Boolean
		sourceColumn: Promo Flag
		summarizeBy: none

	column 'Net Sales Amount'
		dataType: Decimal
		sourceColumn: Net Sales Amount
		summarizeBy: none

	column Quantity
		dataType: Decimal
		sourceColumn: Quantity
		summarizeBy: none

	column 'Plan Quantity'
		dataType: Decimal
		sourceColumn: Plan Quantity
		summarizeBy: none

	column 'List Price Amount'
		dataType: Decimal
		sourceColumn: List Price Amount
		summarizeBy: none

	column 'Net Price Amount'
		dataType: Decimal
		sourceColumn: Net Price Amount
		summarizeBy: none

	column 'Discount Amount'
		dataType: Decimal
		sourceColumn: Discount Amount
		summarizeBy: none

	column 'Plan Sales Amount'
		dataType: Decimal
		sourceColumn: Plan Sales Amount
		summarizeBy: none

	column 'Last Year Sales Amount'
		dataType: Decimal
		sourceColumn: Last Year Sales Amount
		summarizeBy: none

	column 'Cost of Goods Sold Amount'
		dataType: Decimal
		sourceColumn: Cost of Goods Sold Amount
		summarizeBy: none

	partition fact_sales = m
		mode: import
		source =
			let
				Source = Folder.Files(GoldDataPath & "/facts/fact_sales"),
				FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
				FirstFile = FilteredFiles{0}[Content],
				ParquetData = Parquet.Document(FirstFile)
			in
				ParquetData
