table dim_index
	lineageTag: 217a394a-27ee-4b71-b5b1-d9dd2966f529

	column date
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: a71c50a1-58b2-4c9c-8afa-992489ee8810
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column index_name
		dataType: string
		lineageTag: d3aace2d-97d7-412f-9789-68dd5261bd70
		summarizeBy: none
		sourceColumn: index_name

		annotation SummarizationSetBy = Automatic

	column index_value
		dataType: double
		lineageTag: a671ac0d-30f3-4984-8a6f-8d80975ec89c
		summarizeBy: none
		sourceColumn: index_value

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition dim_index = m
		mode: import
		source =
				let
				    Quelle = Excel.Workbook(File.Contents(Source), null, true),
				    Index_Sheet = Quelle{[Item="Index",Kind="Sheet"]}[Data],
				    #"Höher gestufte Header" = Table.PromoteHeaders(Index_Sheet, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"date", type datetime}, {"index_name", type text}, {"index_value", type number}})
				in
				    #"Geänderter Typ"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

