table dim_date
	lineageTag: 5b65051e-106b-468b-85ac-e6b4fdcd74c0
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: dd.mm.yyyy
		lineageTag: a62a1cac-4c16-4448-86e1-b1fcc6de8ef8
		summarizeBy: none
		sourceColumn: Date

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Year
		dataType: int64
		formatString: 0
		lineageTag: ca2b6a06-db3f-4d2d-bd38-06b191295876
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = User

	column 'Start of Year'
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: fab2140c-59ec-4a2d-96c5-d8824f91a5bc
		summarizeBy: none
		sourceColumn: Start of Year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'End of Year'
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 0f680c27-4049-44f7-97cb-2b09e2e85587
		summarizeBy: none
		sourceColumn: End of Year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Month
		dataType: int64
		formatString: 0
		lineageTag: e37e3d15-6009-4cfd-bde0-59dc54a3f664
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = User

	column 'Start of Month'
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: b5d23a5c-d0f9-45f7-a6e9-f657512073db
		summarizeBy: none
		sourceColumn: Start of Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'End of Month'
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: ea1de9c8-8a2d-4c27-8392-f4c01601ca00
		summarizeBy: none
		sourceColumn: End of Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Days in Month'
		dataType: int64
		formatString: 0
		lineageTag: 0a893250-2465-403a-be27-87615e7f765e
		summarizeBy: none
		sourceColumn: Days in Month

		annotation SummarizationSetBy = User

	column Day
		dataType: int64
		formatString: 0
		lineageTag: df82f871-2937-4084-b7b5-d003bc408e46
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = User

	column 'Day Name'
		dataType: string
		lineageTag: f416f9ae-39d3-4239-aa17-b8f8939be702
		summarizeBy: none
		sourceColumn: Day Name
		sortByColumn: 'Day of Week'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		dataType: int64
		formatString: 0
		lineageTag: 3e8bfef6-b89f-41c8-812c-b224de6b5b5d
		summarizeBy: none
		sourceColumn: Day of Week

		annotation SummarizationSetBy = User

	column 'Day of Year'
		dataType: int64
		formatString: 0
		lineageTag: f1a76f11-8320-4083-a3c6-dccafcd02e9b
		summarizeBy: none
		sourceColumn: Day of Year

		annotation SummarizationSetBy = User

	column 'Month Name'
		dataType: string
		lineageTag: 946f4245-0574-4129-b06e-608a323a8618
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: Month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: ff66b334-9371-47f5-8126-74b924421675
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = User

	column 'Start of Quarter'
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 2a14679b-229e-4156-8078-72abd245e6d9
		summarizeBy: none
		sourceColumn: Start of Quarter

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'End of Quarter'
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: c158e414-2828-4911-901e-acd886238129
		summarizeBy: none
		sourceColumn: End of Quarter

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Week of Year'
		dataType: int64
		formatString: 0
		lineageTag: e0aa45e3-8ac7-4807-9b80-6f19f6ea8bb7
		summarizeBy: none
		sourceColumn: Week of Year

		annotation SummarizationSetBy = User

	column 'Week of Month'
		dataType: int64
		formatString: 0
		lineageTag: 767d0541-a477-4e63-bf1a-d2ce2b08de6c
		summarizeBy: none
		sourceColumn: Week of Month

		annotation SummarizationSetBy = User

	column 'Start of Week'
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 17e1d23d-7e4a-4638-bea8-b3b7d7240fd7
		summarizeBy: none
		sourceColumn: Start of Week

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'End of Week'
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 094b4b9e-5d1e-44cf-bca2-efdf302a93ad
		summarizeBy: none
		sourceColumn: End of Week

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Fiscal Year'
		dataType: int64
		formatString: 0
		lineageTag: 8565a720-fb95-4e0b-ad80-196cce9d6391
		summarizeBy: none
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = User

	column 'Fiscal Quarter'
		dataType: int64
		formatString: 0
		lineageTag: 05cf4b2c-0d6a-4487-a616-3fa0d118afb6
		summarizeBy: none
		sourceColumn: Fiscal Quarter

		annotation SummarizationSetBy = User

	column 'Fiscal Month'
		dataType: int64
		formatString: 0
		lineageTag: 269129ce-b938-4f53-b89d-e3a6e54a548f
		summarizeBy: none
		sourceColumn: Fiscal Month

		annotation SummarizationSetBy = User

	column 'Day Offset'
		dataType: int64
		formatString: 0
		lineageTag: 99a1dba1-3dc5-42d0-a2b7-759318c3539c
		summarizeBy: none
		sourceColumn: Day Offset

		annotation SummarizationSetBy = User

	column 'Month Offset'
		dataType: int64
		formatString: 0
		lineageTag: 2c901afb-0334-4c95-a343-96f3ffeae35b
		summarizeBy: none
		sourceColumn: Month Offset

		annotation SummarizationSetBy = User

	column 'Year Offset'
		dataType: int64
		formatString: 0
		lineageTag: 1ffe7070-b9f0-4994-b6e5-08e11219c54d
		summarizeBy: none
		sourceColumn: Year Offset

		annotation SummarizationSetBy = User

	column 'Quarter Offset'
		dataType: int64
		formatString: 0
		lineageTag: c24465b1-6813-49f6-a9e7-9cb8bb64fc8e
		summarizeBy: none
		sourceColumn: Quarter Offset

		annotation SummarizationSetBy = User

	column Year-Month
		dataType: string
		lineageTag: 3c8d082b-ae12-4eb8-b978-f7c17e51be51
		summarizeBy: none
		sourceColumn: Year-Month
		sortByColumn: 'Year-Month Code'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Year-Month Code'
		dataType: int64
		formatString: 0
		lineageTag: 15a08dc7-7821-47d0-a11e-29038b83a5df
		summarizeBy: none
		sourceColumn: Year-Month Code

		annotation SummarizationSetBy = User

	partition dim_date = m
		mode: import
		source = ```
				let
				    // configurations start
				    Today = Date.From(DateTime.LocalNow()), // today's date
				    FromYear = Date.Year(Date.AddYears(Today, -2)), // set the start year of the date dimension
				    ToYear = Date.Year(Date.AddYears(Today, 0)), // set the end year of the date dimension
				    StartofFiscalYear = 7, // set the month number that is the start of the financial year
				    firstDayofWeek = Day.Monday, // set the week's start day
				    // configuration end
				
				    FromDate = #date(FromYear, 1, 1),
				    ToDate = #date(ToYear, 12, 31),
				
				    Source = List.Dates(
				        FromDate,
				        Duration.Days(ToDate - FromDate) + 1,
				        #duration(1, 0, 0, 0)
				    ),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
				    
				    // Additional transformations
				    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Inserted Start of Year" = Table.AddColumn(#"Inserted Year", "Start of Year", each Date.StartOfYear([Date]), type date),
				    #"Inserted End of Year" = Table.AddColumn(#"Inserted Start of Year", "End of Year", each Date.EndOfYear([Date]), type date),
				    #"Inserted Month" = Table.AddColumn(#"Inserted End of Year", "Month", each Date.Month([Date]), Int64.Type),
				    #"Inserted Start of Month" = Table.AddColumn(#"Inserted Month", "Start of Month", each Date.StartOfMonth([Date]), type date),
				    #"Inserted End of Month" = Table.AddColumn(#"Inserted Start of Month", "End of Month", each Date.EndOfMonth([Date]), type date),
				    #"Inserted Days in Month" = Table.AddColumn(#"Inserted End of Month", "Days in Month", each Date.DaysInMonth([Date]), Int64.Type),
				    #"Inserted Day" = Table.AddColumn(#"Inserted Days in Month", "Day", each Date.Day([Date]), Int64.Type),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted Day", "Day Name", each Date.DayOfWeekName([Date]), type text),
				    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Day Name", "Day of Week", each Date.DayOfWeek([Date],firstDayofWeek), Int64.Type),
				    #"Inserted Day of Year" = Table.AddColumn(#"Inserted Day of Week", "Day of Year", each Date.DayOfYear([Date]), Int64.Type),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Day of Year", "Month Name", each Date.MonthName([Date]), type text),
				    #"Inserted Quarter" = Table.AddColumn(#"Inserted Month Name", "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
				    #"Inserted Start of Quarter" = Table.AddColumn(#"Inserted Quarter", "Start of Quarter", each Date.StartOfQuarter([Date]), type date),
				    #"Inserted End of Quarter" = Table.AddColumn(#"Inserted Start of Quarter", "End of Quarter", each Date.EndOfQuarter([Date]), type date),
				    #"Inserted Week of Year" = Table.AddColumn(#"Inserted End of Quarter", "Week of Year", each Date.WeekOfYear([Date],firstDayofWeek), Int64.Type),
				    #"Inserted Week of Month" = Table.AddColumn(#"Inserted Week of Year", "Week of Month", each Date.WeekOfMonth([Date],firstDayofWeek), Int64.Type),
				    #"Inserted Start of Week" = Table.AddColumn(#"Inserted Week of Month", "Start of Week", each Date.StartOfWeek([Date],firstDayofWeek), type date),
				    #"Inserted End of Week" = Table.AddColumn(#"Inserted Start of Week", "End of Week", each Date.EndOfWeek([Date],firstDayofWeek), type date),
				    FiscalMonthBaseIndex = 13 - StartofFiscalYear,
				    adjustedFiscalMonthBaseIndex = if(FiscalMonthBaseIndex >= 12 or FiscalMonthBaseIndex < 0) then 0 else FiscalMonthBaseIndex,
				    #"Added Custom" = Table.AddColumn(#"Inserted End of Week", "FiscalBaseDate", each Date.AddMonths([Date], adjustedFiscalMonthBaseIndex)),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"FiscalBaseDate", type date}}),
				    #"Inserted Year1" = Table.AddColumn(#"Changed Type1", "Year.1", each Date.Year([FiscalBaseDate]), Int64.Type),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Year1",{{"Year.1", "Fiscal Year"}}),
				    #"Inserted Quarter1" = Table.AddColumn(#"Renamed Columns1", "Quarter.1", each Date.QuarterOfYear([FiscalBaseDate]), Int64.Type),
				    #"Renamed Columns2" = Table.RenameColumns(#"Inserted Quarter1",{{"Quarter.1", "Fiscal Quarter"}}),
				    #"Inserted Month1" = Table.AddColumn(#"Renamed Columns2", "Month.1", each Date.Month([FiscalBaseDate]), Int64.Type),
				    #"Renamed Columns3" = Table.RenameColumns(#"Inserted Month1",{{"Month.1", "Fiscal Month"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns3",{"FiscalBaseDate"}),
				    #"Inserted Age" = Table.AddColumn(#"Removed Columns", "Age", each [Date] - Today, type duration),
				    #"Extracted Days" = Table.TransformColumns(#"Inserted Age",{{"Age", Duration.Days, Int64.Type}}),
				    #"Renamed Columns4" = Table.RenameColumns(#"Extracted Days",{{"Age", "Day Offset"}}),
				    #"Added Custom1" = Table.AddColumn(#"Renamed Columns4", "Month Offset", each (([Year] - Date.Year(Today)) * 12) + ([Month] - Date.Month(Today))),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom1",{{"Month Offset", Int64.Type}}),
				    #"Added Custom2" = Table.AddColumn(#"Changed Type2", "Year Offset", each [Year] - Date.Year(Today)),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom2",{{"Year Offset", Int64.Type}}),
				    #"Added Custom3" = Table.AddColumn(#"Changed Type3", "Quarter Offset", each (([Year] - Date.Year(Today)) * 4) + ([Quarter] - Date.QuarterOfYear(Today))),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom3",{{"Quarter Offset", Int64.Type}}),
				    #"Added Custom4" = Table.AddColumn(#"Changed Type4", "Year-Month", each Date.ToText([Date], "MMM yyyy")),
				    #"Added Custom5" = Table.AddColumn(#"Added Custom4", "Year-Month Code", each Date.ToText([Date], "yyyyMM")),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Added Custom5",{{"Year-Month", type text}, {"Year-Month Code", Int64.Type}})
				in
				    #"Changed Type5"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

