/**
 * POST /api/core/draft
 *
 * Creates a discovery draft branch in the repo and writes a
 * human-readable summary of extracted elements to
 * internal/discovery/<timestamp>.md
 *
 * Body: { elements: ExtractedElement[] }
 * Returns: { branch, file, kpisAdded, actionsAdded, anchorsAdded }
 */

import { execFileSync } from 'node:child_process';
import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { apiSuccess, apiError } from '@/lib/api/response';
import { ErrorCode } from '@/lib/api/error-codes';
import { loadAllActionCodes } from '@/lib/core/action-loader';
import { loadKpiCatalog } from '@/lib/core/catalog-loader';
import { requireAuth } from '@/lib/auth/session';

interface DraftElement {
  type: string;
  id: string;
  name: string;
  source?: string;
}

interface DraftDecision {
  key: string;
  mode: 'create' | 'reuse' | 'merge';
  reusedId?: string;
}

function isValidElement(e: unknown): e is DraftElement {
  if (e === null || typeof e !== 'object') return false;
  const obj = e as Record<string, unknown>;
  return (
    typeof obj.type === 'string' &&
    typeof obj.id === 'string' &&
    typeof obj.name === 'string' &&
    obj.id.length > 0 &&
    obj.name.length > 0
  );
}

export async function POST(request: Request) {
  const [, authError] = await requireAuth();
  if (authError) return authError;

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return apiError(ErrorCode.VALIDATION_ERROR, 'Invalid JSON body', 400);
  }

  if (body === null || typeof body !== 'object') {
    return apiError(ErrorCode.VALIDATION_ERROR, 'Request body must be an object', 400);
  }

  const rawElements = (body as Record<string, unknown>).elements;
  const rawDecisions = (body as Record<string, unknown>).decisions;
  if (!Array.isArray(rawElements)) {
    return apiError(ErrorCode.VALIDATION_ERROR, 'elements must be an array', 400);
  }

  const elements = rawElements.filter(isValidElement);
  if (elements.length === 0) {
    return apiError(ErrorCode.VALIDATION_ERROR, 'No valid elements to draft', 400);
  }

  const decisions = Array.isArray(rawDecisions)
    ? rawDecisions.filter((item): item is DraftDecision => {
        if (!item || typeof item !== 'object') return false;
        const candidate = item as Record<string, unknown>;
        return typeof candidate.key === 'string' && (candidate.mode === 'create' || candidate.mode === 'reuse' || candidate.mode === 'merge');
      })
    : [];

  const decisionMap = new Map(decisions.map((decision) => [decision.key, decision]));
  const repoRoot = join(process.cwd(), '..');
  const now = new Date();
  // Timestamp slug: YYYYMMDD-HHmmss — safe for filenames and branch names
  const stamp =
    now.getFullYear().toString() +
    String(now.getMonth() + 1).padStart(2, '0') +
    String(now.getDate()).padStart(2, '0') +
    '-' +
    String(now.getHours()).padStart(2, '0') +
    String(now.getMinutes()).padStart(2, '0') +
    String(now.getSeconds()).padStart(2, '0');

  const branchName = `discovery/draft-${stamp}`;

  // Create git branch — uses execFileSync with array args (no shell injection)
  try {
    execFileSync('git', ['checkout', '-b', branchName], {
      cwd: repoRoot,
      timeout: 10_000,
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return apiError(ErrorCode.INTERNAL_ERROR, `Git branch creation failed: ${msg}`, 500);
  }

  // Write draft markdown to internal/discovery/
  const draftDir = join(repoRoot, 'internal', 'discovery');
  await mkdir(draftDir, { recursive: true });
  const fileName = `${stamp}.md`;
  const draftFile = join(draftDir, fileName);

  const lines: string[] = [
    `# Discovery Draft — ${now.toLocaleString('de-DE')}`,
    '',
    `**Branch:** \`${branchName}\``,
    `**Elements:** ${elements.length}`,
    '',
    '---',
    '',
    '## Extracted Elements',
    '',
  ];

  const grouped: Record<string, DraftElement[]> = { anchor: [], kpi: [], action: [] };
  for (const el of elements) {
    const bucket = grouped[el.type] ?? [];
    bucket.push(el);
    grouped[el.type] = bucket;
  }

  for (const [type, items] of Object.entries(grouped)) {
    if (items.length === 0) continue;
    const heading = type === 'kpi' ? 'KPIs' : type === 'action' ? 'Action Codes' : 'Strategy Anchors';
    lines.push(`### ${heading}`);
    lines.push('');
    for (const el of items) {
      const decision = decisionMap.get(`${el.type}:${el.id}:${el.name}`);
      const decisionSuffix = decision?.reusedId ? ` → ${decision.mode} ${decision.reusedId}` : '';
      lines.push(`- **${el.id}** — ${el.name}${el.source ? ` *(${el.source})*` : ''}${decisionSuffix}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('> Auto-generated by Discovery Hub. Review, adjust, and run Stage 1 before merging.');

  await writeFile(draftFile, lines.join('\n'), 'utf-8');

  const [kpis, actions] = await Promise.all([loadKpiCatalog(), loadAllActionCodes()]);
  const anchor = elements.find((element) => element.type === 'anchor');
  const scaffoldKpiElements = elements.filter((element) => element.type === 'kpi');
  const scaffoldActionElements = elements.filter((element) => element.type === 'action');

  const resolvedStrategic = scaffoldKpiElements[0];
  const strategicCatalog = resolvedStrategic
    ? kpis.find((kpi) => kpi.kpi_id.toLowerCase() === resolvedStrategic.id.toLowerCase())
    : null;

  const influencingIds = scaffoldKpiElements.slice(1, 5).map((element) => {
    const decision = decisionMap.get(`${element.type}:${element.id}:${element.name}`);
    return decision?.reusedId ? decision.reusedId : element.id;
  });

  const actionIds = scaffoldActionElements.slice(0, 4).map((element) => {
    const decision = decisionMap.get(`${element.type}:${element.id}:${element.name}`);
    return decision?.reusedId ? decision.reusedId : element.id;
  });

  const resolvedAction = actionIds[0]
    ? actions.find((action) => action.id.toLowerCase() === actionIds[0].toLowerCase())
    : null;

  const domain = strategicCatalog?.domain_tag?.[0] || resolvedAction?.owner_domain || 'XD';
  const domainConfig: Record<string, { owner: string; steward: string; evidence: string }> = {
    Commercial: { owner: 'commercial_controlling_lead', steward: 'commercial_bi_lead', evidence: 'customer_month' },
    Finance: { owner: 'finance_director', steward: 'finance_bi_lead', evidence: 'entity_month' },
    Operations: { owner: 'operations_director', steward: 'operations_bi_lead', evidence: 'entity_month' },
    SupplyChain: { owner: 'head_of_supply_chain', steward: 'supply_chain_bi_lead', evidence: 'entity_month' },
    XD: { owner: 'enterprise_bi_lead', steward: 'enterprise_bi_lead', evidence: 'entity_month' },
  };
  const governance = domainConfig[domain] ?? domainConfig.XD;

  const draftId = `DRAFT-${stamp.replace('-', '')}`;
  const scaffoldTitle = anchor?.name || (resolvedStrategic ? `${resolvedStrategic.name} Improvement` : 'Discovery Draft Use Case');
  const strategicId = resolvedStrategic
    ? (decisionMap.get(`${resolvedStrategic.type}:${resolvedStrategic.id}:${resolvedStrategic.name}`)?.reusedId || resolvedStrategic.id)
    : 'tbd.strategic.kpi';

  const scaffoldLines = [
    "schema_version: '2.0'",
    `id: ${draftId}`,
    `title: ${yamlSafe(scaffoldTitle)}`,
    `domain: ${yamlSafe(domain)}`,
    'governance:',
    `  owner_role: ${governance.owner}`,
    `  steward_role: ${governance.steward}`,
    'orchestration:',
    `  strategic_kpi_id: ${strategicId}`,
    '  influencing_kpi_ids:',
    ...(influencingIds.length > 0 ? influencingIds.map((id) => `  - ${id}`) : ['  - tbd.influencing.kpi']),
    '  action_code_ids:',
    ...(actionIds.length > 0 ? actionIds.map((id) => `  - ${id}`) : ['  - tbd.action.code']),
    'value_driver_model:',
    `  formula: ${yamlSafe(`${strategicId} = f(${influencingIds.length > 0 ? influencingIds.join(', ') : 'drivers'})`)}`,
    '  impact_direction: maximize',
    `  primary_driver: ${influencingIds[0] ?? 'tbd.influencing.kpi'}`,
    `  impact_logic: ${yamlSafe(anchor?.name || 'Discovery-generated draft. Replace with validated business logic before promotion.')}`,
    'ux_layout_rules:',
    '  report_structure: 2-Page-Lead',
    '  page_1_summary:',
    `    title: ${yamlSafe(`${domain} Summary`)}`,
    '    template_id: pulse',
    '    component_3s:',
    `      kpi_id: ${strategicId}`,
    '      visual_type: kpi_card',
    '    component_30s:',
    ...(influencingIds.length > 0
      ? influencingIds.slice(0, 3).map((id) => `    - kpi_id: ${id}\n      visual_type: trend_line`)
      : ['    - kpi_id: tbd.influencing.kpi\n      visual_type: trend_line']),
    '  page_2_execution:',
    `    title: ${yamlSafe(`${domain} Execution`)}`,
    '    template_id: action_matrix',
    '    component_300s:',
    `      evidence_grain: ${governance.evidence}`,
    '      evidence_columns:',
    '      - entity',
    '      - period',
    `      - ${strategicId}`,
    '      action_panel: true',
    '      payload_mode: summary',
    'documentation:',
    '  business_factsheet: ./Business_Factsheet.md',
    'overrides:',
    `  data_contract_ref: ${yamlSafe(`core/data_contracts/domains/${domain.toLowerCase()}.yaml`)}`,
  ];

  const scaffoldDir = join(draftDir, 'scaffolds');
  await mkdir(scaffoldDir, { recursive: true });
  const scaffoldFileName = `${draftId}_UseCase_Bracket.yaml`;
  await writeFile(join(scaffoldDir, scaffoldFileName), scaffoldLines.join('\n'), 'utf-8');

  const kpisAdded = elements.filter((e) => e.type === 'kpi').length;
  const actionsAdded = elements.filter((e) => e.type === 'action').length;
  const anchorsAdded = elements.filter((e) => e.type === 'anchor').length;
  const reusedCount = decisions.filter((decision) => decision.mode === 'reuse' && decision.reusedId).length;

  return apiSuccess({
    branch: branchName,
    file: `internal/discovery/${fileName}`,
    scaffold: {
      id: draftId,
      file: `internal/discovery/scaffolds/${scaffoldFileName}`,
      title: scaffoldTitle,
    },
    scaffoldYaml: scaffoldLines.join('\n'),
    kpisAdded,
    actionsAdded,
    anchorsAdded,
    reusedCount,
    total: elements.length,
  });
}

function yamlSafe(value: string): string {
  return JSON.stringify(value);
}
