table dim_contracts
	lineageTag: dee0ccf0-7dbc-4fe7-b1a7-c375907d9642

	column contract_id
		dataType: string
		lineageTag: 924e58cd-1e45-4b1f-8f10-79cd582ba5e0
		summarizeBy: none
		sourceColumn: contract_id

		annotation SummarizationSetBy = Automatic

	column supplier_id
		dataType: string
		lineageTag: 066f2c8c-9d7e-4f28-955a-b3c34f09c1a6
		summarizeBy: none
		sourceColumn: supplier_id

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 96f5bbf1-ad3b-48fd-b7fb-ede7d1343fbc
		summarizeBy: none
		sourceColumn: start_date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column end_date
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: f3e145ff-894e-40db-9329-83d99069e18e
		summarizeBy: none
		sourceColumn: end_date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column index_linked
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d7e0fbb9-2abb-4099-9ff1-ac6b69f32701
		summarizeBy: none
		sourceColumn: index_linked

		annotation SummarizationSetBy = Automatic

	column contract_type
		dataType: string
		lineageTag: f3b7b53a-8f8e-4f8a-af9c-98494d1fe0e5
		summarizeBy: none
		sourceColumn: contract_type

		annotation SummarizationSetBy = Automatic

	partition dim_contracts = m
		mode: import
		source =
				let
				    Quelle = Excel.Workbook(File.Contents(Source), null, true),
				    Contracts_Sheet = Quelle{[Item="Contracts",Kind="Sheet"]}[Data],
				    #"Höher gestufte Header" = Table.PromoteHeaders(Contracts_Sheet, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"contract_id", type text}, {"supplier_id", type text}, {"start_date", type datetime}, {"end_date", type datetime}, {"index_linked", type logical}, {"contract_type", type text}})
				in
				    #"Geänderter Typ"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

