table fact_transactions
	lineageTag: 0503a4c3-ea97-4057-a6e4-d48d0b0072ee

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a15bf487-a71c-4481-a092-f612bdb3020a
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column part_id
		dataType: string
		lineageTag: a1663a32-9781-45e4-bc4d-b4d3b6ad79c3
		summarizeBy: none
		sourceColumn: part_id

		annotation SummarizationSetBy = Automatic

	column supplier_id
		dataType: string
		lineageTag: 1560828a-f868-43e9-b962-37eb0930287c
		summarizeBy: none
		sourceColumn: supplier_id

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: double
		lineageTag: bb7ba3f0-24cc-49fd-89dd-5d4532414cdc
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: 76caa764-2869-49d2-9aca-c63c6adbde20
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column contract_id
		dataType: string
		lineageTag: 23d7de93-17c8-42bb-8e65-a88c26f1e0b4
		summarizeBy: none
		sourceColumn: contract_id

		annotation SummarizationSetBy = Automatic

	partition fact_transactions = m
		mode: import
		source =
				let
				    Quelle = Excel.Workbook(File.Contents(Source), null, true),
				    Transactions_Sheet = Quelle{[Item="Transactions",Kind="Sheet"]}[Data],
				    #"Höher gestufte Header" = Table.PromoteHeaders(Transactions_Sheet, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"date", type date}, {"part_id", type text}, {"supplier_id", type text}, {"unit_price", type number}, {"quantity", Int64.Type}, {"contract_id", type text}})
				in
				    #"Geänderter Typ"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

