#!/usr/bin/env python3
"""Aggregate the Aurora gold facts into a KPI-values snapshot for ActionReady Studio.

Studio reads governed metadata from core/ live, but report/dashboard numbers were
hard-coded zeros/stubs (Studio audit Gap 1/3: showcases/aurora_group is not wired
in). This tool computes the real commercial KPI values from the gold fact tables
(DuckDB over the partitioned parquet) and writes a static JSON snapshot that the
Studio loader consumes -- no DuckDB/parquet reader needed at Studio runtime.

Usage:
    python showcases/aurora_group/data/build_kpi_snapshot.py
    # writes studio/data/aurora_kpi_snapshot.json
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

import duckdb

_REPO = Path(__file__).resolve().parents[3]
_GOLD = _REPO / "showcases" / "aurora_group" / "data" / "gold" / "facts" / "fact_sales"
_OUT = _REPO / "studio" / "data" / "aurora_kpi_snapshot.json"
_MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


def _glob() -> str:
    return f"read_parquet('{_GOLD}/**/*.parquet', hive_partitioning=true)"


def _monthly(con: duckdb.DuckDBPyConnection) -> list[dict]:
    rows = con.sql(f"""
        SELECT "Fiscal Year" AS fy, "Fiscal Month" AS fm,
               SUM("Net Sales Amount")          AS net_sales,
               SUM("Cost of Goods Sold Amount") AS cogs,
               SUM("Plan Sales Amount")         AS plan_sales,
               SUM("Last Year Sales Amount")    AS ly_sales
        FROM {_glob()}
        GROUP BY 1, 2
        ORDER BY fy, fm
    """).fetchall()
    out = []
    for fy, fm, net, cogs, plan, ly in rows:
        net, cogs, plan, ly = (float(x or 0) for x in (net, cogs, plan, ly))
        out.append({
            "fy": int(fy), "fm": int(fm), "label": _MONTHS[(int(fm) - 1) % 12],
            "net_sales": net, "cogs": cogs, "plan_sales": plan, "ly_sales": ly,
            "gm_amount": net - cogs,
            "gm_pct": (net - cogs) / net * 100 if net else 0.0,
            "vs_plan_pct": (net - plan) / plan * 100 if plan else 0.0,
            "vs_ly_pct": (net - ly) / ly * 100 if ly else 0.0,
        })
    return out


def _kpi(months: list[dict], field: str, unit: str, target_field: str | None = None) -> dict:
    latest, prev = months[-1], (months[-2] if len(months) > 1 else months[-1])
    trend = [{"period": m["label"], "value": round(m[field], 2)} for m in months[-12:]]
    return {
        "value": round(latest[field], 2),
        "previousValue": round(prev[field], 2),
        "target": round(latest[target_field], 2) if target_field else round(latest[field], 2),
        "unit": unit,
        "trend": trend,
    }


def build_snapshot() -> dict:
    con = duckdb.connect()
    con.sql("SET enable_progress_bar=false")
    months = _monthly(con)
    latest = months[-1]
    kpis = {
        "sales.net_sales.amount": _kpi(months, "net_sales", "EUR", "plan_sales"),
        "margin.gm.pct": _kpi(months, "gm_pct", "%"),
        "cost.cogs.amount": _kpi(months, "cogs", "EUR"),
        "sales.net_sales.delta_pct.plan": _kpi(months, "vs_plan_pct", "%"),
        "sales.net_sales.delta_pct.ly": _kpi(months, "vs_ly_pct", "%"),
    }
    return {
        "_meta": {
            "source": "showcases/aurora_group/data/gold/facts/fact_sales",
            "generatedAt": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "latestPeriod": f"FY{latest['fy']}-M{latest['fm']:02d}",
            "note": "Generated by build_kpi_snapshot.py from Aurora gold; consumed by Studio.",
        },
        "kpis": kpis,
    }


def main() -> int:
    snapshot = build_snapshot()
    _OUT.parent.mkdir(parents=True, exist_ok=True)
    _OUT.write_text(json.dumps(snapshot, indent=2) + "\n", encoding="utf-8")
    meta = snapshot["_meta"]
    gm = snapshot["kpis"]["margin.gm.pct"]["value"]
    ns = snapshot["kpis"]["sales.net_sales.amount"]["value"]
    print(f"Wrote {_OUT} ({meta['latestPeriod']}): Net Sales {ns:,.0f} EUR, Gross Margin % {gm}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
