table dim_customer
	lineageTag: 89e25678-1234-5678-9abc-def012345678

	column CustomerKey
		dataType: int64
		sourceColumn: CustomerKey
		isHidden

	column CustomerName
		dataType: string
		sourceColumn: CustomerName

	column Segment
		dataType: string
		sourceColumn: Segment

	column Country
		dataType: string
		sourceColumn: Country

	column Region
		dataType: string
		sourceColumn: Region

	partition dim_customer = m
		mode: import
		source =
				let
					Source = Folder.Files("C:\Users\florianhaferkorn\VSCode\analytics-usecase-library\showcases\aurora_group\data\gold\dimensions\dim_customer"),
					FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
					FirstFile = FilteredFiles{0}[Content],
					ParquetData = Parquet.Document(FirstFile)
				in
					ParquetData
