table dim_product
	lineageTag: abcdef12-3456-7890-abcd-ef1234567890

	column ProductKey
		dataType: int64
		sourceColumn: ProductKey
		isHidden

	column ProductName
		dataType: string
		sourceColumn: ProductName

	column Category
		dataType: string
		sourceColumn: Category

	column SubCategory
		dataType: string
		sourceColumn: SubCategory

	column Brand
		dataType: string
		sourceColumn: Brand

	column ProductFamily
		dataType: string
		sourceColumn: ProductFamily

	hierarchy 'Product Hierarchy'
		lineageTag: product-hierarchy

		level Category
			column: Category

		level 'Sub Category'
			column: SubCategory

		level Brand
			column: Brand

		level 'Product Name'
			column: ProductName

	partition dim_product = m
		mode: import
		source =
				let
					Source = Folder.Files("C:\Users\florianhaferkorn\VSCode\analytics-usecase-library\showcases\aurora_group\data\gold\dimensions\dim_product"),
					FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
					FirstFile = FilteredFiles{0}[Content],
					ParquetData = Parquet.Document(FirstFile)
				in
					ParquetData
