/// Support case queue dimension (queue name, channel, region).
/// Queue-level case and WFM analysis.
table dim_case_queue
	lineageTag: 36ca493e-2636-487f-b663-8e53fe7ce3b5

	column QueueKey
		dataType: int64
		isHidden
		lineageTag: 748a3c88-ac3a-47d9-a3cc-adac2f420c51
		summarizeBy: none
		sourceColumn: QueueKey

	column QueueName
		dataType: string
		lineageTag: 25158f1b-447f-4de4-83e4-8cffdb0055a8
		sourceColumn: QueueName

	column Channel
		dataType: string
		lineageTag: b59b1da4-7258-4f60-bf09-46039bea0c47
		sourceColumn: Channel

	column Region
		dataType: string
		lineageTag: 6554b448-8dce-41e2-b9bc-f17129a4966e
		sourceColumn: Region

	hierarchy 'Support Queue'
		lineageTag: 5639e270-b312-4583-8fb9-3a60c2f8a062

		level Region
			lineageTag: 0456936c-46bf-4f8b-8776-e7c53cc2f037
			column: Region

		level Channel
			lineageTag: b0d84401-59db-432f-b18b-052d9a5f98ca
			column: Channel

		level 'Queue Name'
			lineageTag: fa6401d8-b831-4ef9-a2b3-92c13847ba09
			column: QueueName

	partition dim_case_queue = m
		mode: import
		source =
				let
					Source = Folder.Files(GoldDataPath & "/dimensions/dim_case_queue"),
					FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
					FirstFile = FilteredFiles{0}[Content],
					ParquetData = Parquet.Document(FirstFile)
				in
					ParquetData

