/// Transport lane dimension (origin, destination, mode) for fulfillment.
/// Lane-level OTIF and logistics analysis.
table dim_lane
	lineageTag: 39ee0ff0-056e-4010-ae92-7bdf50e60fa0

	column LaneKey
		dataType: int64
		isHidden
		lineageTag: dca88a4f-9856-4aac-a69d-a8c70223b34e
		summarizeBy: none
		sourceColumn: LaneKey

	column Origin
		dataType: string
		lineageTag: 90ca9241-f958-40c0-8d2c-8ace6433aa72
		sourceColumn: Origin

	column Destination
		dataType: string
		lineageTag: 8c4b7f51-4297-4836-a8c7-30aa17a7bc1a
		sourceColumn: Destination

	column Mode
		dataType: string
		lineageTag: 22f64e9b-20ea-4c0e-81f7-ac8f5bd372cb
		sourceColumn: Mode

	partition dim_lane = m
		mode: import
		source =
				let
					Source = Folder.Files(GoldDataPath & "/dimensions/dim_lane"),
					FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
					FirstFile = FilteredFiles{0}[Content],
					ParquetData = Parquet.Document(FirstFile)
				in
					ParquetData

