table dim_date
	lineageTag: ef5816f6-16fe-4dd5-9d71-20835fbf02b7

	column DateKey
		dataType: int64
		sourceColumn: DateKey
		isHidden

	column Date
		dataType: dateTime
		sourceColumn: Date

	column Year
		dataType: int64
		sourceColumn: Year

	column Quarter
		dataType: string
		sourceColumn: Quarter

	column Month
		dataType: string
		sourceColumn: Month

	column MonthNumber
		dataType: int64
		sourceColumn: MonthNumber

	column Week
		dataType: string
		sourceColumn: Week

	partition dim_date = m
		mode: import
		source =
				let
					Source = Folder.Files("C:\Users\florianhaferkorn\VSCode\analytics-usecase-library\showcases\aurora_group\data\gold\dimensions\dim_date"),
					FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
					FirstFile = FilteredFiles{0}[Content],
					ParquetData = Parquet.Document(FirstFile)
				in
					ParquetData
