table dim_org
	lineageTag: 12345678-abcd-efgh-ijkl-mnopqrstuvwx

	column OrgKey
		dataType: int64
		sourceColumn: OrgKey
		isHidden

	column OrgName
		dataType: string
		sourceColumn: OrgName

	column Region
		dataType: string
		sourceColumn: Region
		description: "Aurora Group operates across 5 regions: DACH, Benelux, Nordics, Southern Europe, CEE"

	column Country
		dataType: string
		sourceColumn: Country

	column Channel
		dataType: string
		sourceColumn: Channel
		description: "Retail Stores, E-Commerce, Marketplaces, Wholesale"

	hierarchy 'Aurora Organization'
		lineageTag: aurora-org-hierarchy

		level Region
			column: Region

		level Country
			column: Country

		level Channel
			column: Channel

		level 'Org Name'
			column: OrgName

	partition dim_org = m
		mode: import
		source =
				let
					Source = Folder.Files("C:\Users\florianhaferkorn\VSCode\analytics-usecase-library\showcases\aurora_group\data\gold\dimensions\dim_org"),
					FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
					FirstFile = FilteredFiles{0}[Content],
					ParquetData = Parquet.Document(FirstFile)
				in
					ParquetData
