/// Customer complaint and experience events (customer, org, date, severity).
/// Complaint and experience KPI reporting.
table fact_experience
	lineageTag: ce85ce66-c29a-4f68-a919-7ce8649fe254

	column 'Complaint ID'
		dataType: string
		lineageTag: 8d345473-6d80-4f37-9a9e-20d4933c6cb0
		sourceColumn: Complaint ID

	column CustomerKey
		dataType: int64
		lineageTag: 00c282b3-33be-4a22-90df-c71906f08fc0
		summarizeBy: none
		sourceColumn: CustomerKey

	column OrgKey
		dataType: int64
		lineageTag: 8adb8bb7-98d3-4749-bae5-10beb1bdd0ec
		summarizeBy: none
		sourceColumn: OrgKey

	column DateKey
		dataType: int64
		lineageTag: c8a9d983-1190-44ba-a135-30d8a32a7ff1
		summarizeBy: none
		sourceColumn: DateKey

	column Severity
		dataType: string
		lineageTag: 19c1eef5-fb37-43ad-a9be-bcec4565a3d2
		sourceColumn: Severity

	partition fact_experience = m
		mode: import
		source =
				let
					Source = Folder.Files(GoldDataPath & "/facts/fact_experience"),
					FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
					ParquetTables = Table.AddColumn(FilteredFiles, "Parquet", each Parquet.Document([Content])),
					Combined = Table.Combine(ParquetTables[Parquet])
				in
					Combined

