/// Line-day quality facts (total/good/scrap/rework units, defect count) for FPY and COPQ.
/// First-pass yield and cost of poor quality.
table fact_quality
	lineageTag: 09fce7df-982f-47d4-ab54-d57bb3ff1b15

	column DateKey
		dataType: int64
		lineageTag: 95ea8872-0958-4109-b2b6-3b94730a2e63
		summarizeBy: none
		sourceColumn: DateKey

	column OrgKey
		dataType: int64
		lineageTag: 4da32b3f-5218-414e-a4fc-d0d7d6112457
		summarizeBy: none
		sourceColumn: OrgKey

	column ProductKey
		dataType: int64
		lineageTag: 11c6cec9-e2a5-43d5-a612-488bfaa0a1a0
		summarizeBy: none
		sourceColumn: ProductKey

	column 'Total Units'
		dataType: double
		lineageTag: 52a22a02-5339-4c37-a462-1c0bfc97fc78
		summarizeBy: none
		sourceColumn: Total Units

	column 'Good Units'
		dataType: double
		lineageTag: de43df91-ec05-498a-8ab8-cb3413a38d3a
		summarizeBy: none
		sourceColumn: Good Units

	column 'Scrap Units'
		dataType: double
		lineageTag: ddb9f6ba-bda0-4ecf-a85d-98436481f6eb
		summarizeBy: none
		sourceColumn: Scrap Units

	column 'Rework Units'
		dataType: double
		lineageTag: 55e7eb84-7960-4206-8d5a-da678c3e5d79
		summarizeBy: none
		sourceColumn: Rework Units

	column 'Defect Count'
		dataType: double
		lineageTag: cd0dc515-be11-49c5-9e7f-5818d0dae670
		summarizeBy: none
		sourceColumn: Defect Count

	partition fact_quality = m
		mode: import
		source =
				let
					Source = Folder.Files(GoldDataPath & "/facts/fact_quality"),
					FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
					FirstFile = FilteredFiles{0}[Content],
					ParquetData = Parquet.Document(FirstFile)
				in
					ParquetData

