/// Workforce management facts (work, paid, talk, wrap, idle, overtime, shrinkage) per agent-day.
/// WFM utilization and shrinkage reporting.
table fact_workforce_management
	lineageTag: 52e5f38a-5f42-4bc8-8c10-8eb92f85761a

	column DateKey
		dataType: int64
		lineageTag: 9431c792-5600-4ea4-bb5b-4fcffe69e879
		summarizeBy: none
		sourceColumn: DateKey

	column OrgKey
		dataType: int64
		lineageTag: 5f169cc9-1eb2-42db-9e8a-ec5f55c6eae2
		summarizeBy: none
		sourceColumn: OrgKey

	column QueueKey
		dataType: int64
		lineageTag: 8af9a457-3aa7-43c0-ac6d-2de4410b87b6
		summarizeBy: none
		sourceColumn: QueueKey

	column 'Work Time Minutes'
		dataType: double
		lineageTag: 82e295fa-b904-4199-a83f-cc4b7d76a99b
		sourceColumn: Work Time Minutes

	column 'Paid Time Minutes'
		dataType: double
		lineageTag: 106c5d40-3b59-4f45-a4fc-c81632fe55fc
		sourceColumn: Paid Time Minutes

	column 'Talk Time Minutes'
		dataType: double
		lineageTag: 830f475f-e04d-45bd-a31f-8ba2d55ecc39
		sourceColumn: Talk Time Minutes

	column 'Wrap Time Minutes'
		dataType: double
		lineageTag: 4304703e-a420-4dc5-a60a-28c2b1a24ff2
		sourceColumn: Wrap Time Minutes

	column 'Idle Time Minutes'
		dataType: double
		lineageTag: 4556eab9-6f89-4d23-bd45-b39fa2096836
		sourceColumn: Idle Time Minutes

	column 'Overtime Minutes'
		dataType: double
		lineageTag: 488fb1b6-bdf5-4180-acc0-622166251edb
		sourceColumn: Overtime Minutes

	column 'Shrinkage Minutes'
		dataType: double
		lineageTag: 1b80933f-ebba-4358-8487-93f69a067653
		sourceColumn: Shrinkage Minutes

	partition fact_workforce_management = m
		mode: import
		source =
				let
					Source = Folder.Files(GoldDataPath & "/facts/fact_workforce_management"),
					FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
					FirstFile = FilteredFiles{0}[Content],
					ParquetData = Parquet.Document(FirstFile)
				in
					ParquetData

