table fact_sales
	lineageTag: 4abd72a9-83bb-4ea9-9fa8-36b5196ee5ed

	column DateKey
		dataType: int64
		sourceColumn: DateKey

	column OrgKey
		dataType: int64
		sourceColumn: OrgKey

	column ProductKey
		dataType: int64
		sourceColumn: ProductKey

	column CustomerKey
		dataType: int64
		sourceColumn: CustomerKey

	column PromoKey
		dataType: int64
		sourceColumn: PromoKey

	column 'Promo Flag'
		dataType: string
		sourceColumn: Promo Flag

	column 'Net Sales Amount'
		dataType: string
		sourceColumn: Net Sales Amount

	column Quantity
		dataType: double
		sourceColumn: Quantity

	column 'Plan Quantity'
		dataType: double
		sourceColumn: Plan Quantity

	column 'List Price Amount'
		dataType: string
		sourceColumn: List Price Amount

	column 'Net Price Amount'
		dataType: string
		sourceColumn: Net Price Amount

	column 'Discount Amount'
		dataType: string
		sourceColumn: Discount Amount

	column 'Plan Sales Amount'
		dataType: string
		sourceColumn: Plan Sales Amount

	column 'Last Year Sales Amount'
		dataType: string
		sourceColumn: Last Year Sales Amount

	column 'Cost of Goods Sold Amount'
		dataType: string
		sourceColumn: Cost of Goods Sold Amount

	partition fact_sales = m
		mode: import
		source =
				let
					Source = Folder.Files("C:\Users\florianhaferkorn\VSCode\analytics-usecase-library\showcases\aurora_group\data\gold\facts\fact_sales"),
					FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
					FirstFile = FilteredFiles{0}[Content],
					ParquetData = Parquet.Document(FirstFile)
				in
					ParquetData

