/// Cost of goods sold at location-SKU-month grain.
/// COGS and margin analysis.
table fact_cogs
	lineageTag: d7e03089-f0a1-429f-956e-a1e611a6882a

	column DateKey
		dataType: int64
		lineageTag: 5f129abe-2662-422c-9540-440367ea4ee2
		summarizeBy: none
		sourceColumn: DateKey

	column OrgKey
		dataType: int64
		lineageTag: f2241997-2595-4aa2-a4ab-581d52fd68b1
		summarizeBy: none
		sourceColumn: OrgKey

	column ProductKey
		dataType: int64
		lineageTag: fba1009f-db13-436a-bca2-ec4c526a5cc6
		summarizeBy: none
		sourceColumn: ProductKey

	column 'COGS Amount'
		dataType: double
		lineageTag: 1ccad5b8-033a-4a48-8b97-915a908474c8
		sourceColumn: COGS Amount

	partition fact_cogs = m
		mode: import
		source =
				let
					Source = Folder.Files(GoldDataPath & "/facts/fact_cogs"),
					FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
					FirstFile = FilteredFiles{0}[Content],
					ParquetData = Parquet.Document(FirstFile)
				in
					ParquetData

