/// Working capital view by org and period (AR, AP, Inventory).
/// Working capital and cash conversion reporting.
table fact_working_capital
	lineageTag: 09b8eb1c-4e01-4ea5-9691-45ae8712fa7b

	column 'MonthEnd DateKey'
		dataType: int64
		lineageTag: 06381336-de02-4f64-b2b3-c4eadfe01ac8
		summarizeBy: none
		sourceColumn: MonthEnd DateKey

	column OrgKey
		dataType: int64
		lineageTag: cb4f9c94-ce09-497a-b909-c228d0dd7389
		summarizeBy: none
		sourceColumn: OrgKey

	column 'AR Balance Amount'
		dataType: double
		lineageTag: cb279978-10c7-46ec-8705-9815d586b5ad
		summarizeBy: none
		sourceColumn: AR Balance Amount

	column 'AP Balance Amount'
		dataType: double
		lineageTag: f0731745-f91c-4067-bf04-9389c6ad9683
		summarizeBy: none
		sourceColumn: AP Balance Amount

	column 'Inventory Value Amount'
		dataType: double
		lineageTag: fc90ef71-e141-4d48-b462-22413c6dd927
		summarizeBy: none
		sourceColumn: Inventory Value Amount

	column 'Period Net Sales Amount'
		dataType: double
		lineageTag: c30d7115-0451-4723-a5fd-1b8c93cd0759
		summarizeBy: none
		sourceColumn: Period Net Sales Amount

	column 'Period COGS Amount'
		dataType: double
		lineageTag: 00335b16-0432-4306-af64-be1de8066ee0
		summarizeBy: none
		sourceColumn: Period COGS Amount

	column 'Days In Period Count'
		dataType: int64
		formatString: 0
		lineageTag: e62d26fc-51c4-4561-95d7-2c4dc606fa46
		summarizeBy: none
		sourceColumn: Days In Period Count

		annotation SummarizationSetBy = Automatic

	partition fact_working_capital = m
		mode: import
		source =
				let
					Source = Folder.Files(GoldDataPath & "/facts/fact_working_capital"),
					FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
					FirstFile = FilteredFiles{0}[Content],
					ParquetData = Parquet.Document(FirstFile)
				in
					ParquetData

