/// Accounts receivable and revenue by entity and customer per month.
/// AR aging and revenue recognition.
table fact_accounts_receivable
	lineageTag: b057e0bc-50b5-47ba-a654-94965a3fb798

	column DateKey
		dataType: int64
		lineageTag: 9714100f-fcac-42dc-bd68-8202b3659d30
		summarizeBy: none
		sourceColumn: DateKey

	column OrgKey
		dataType: int64
		lineageTag: 22d92bc8-a1bf-4344-b1e9-cd8eb6de7e33
		summarizeBy: none
		sourceColumn: OrgKey

	column CustomerKey
		dataType: int64
		lineageTag: df75fdf0-3795-44bd-814d-a55c7726b655
		summarizeBy: none
		sourceColumn: CustomerKey

	column 'AR Amount'
		dataType: double
		lineageTag: 526d015a-dfd1-4c64-8082-6baaf126891e
		summarizeBy: none
		sourceColumn: AR Amount

	column 'Revenue Amount'
		dataType: double
		lineageTag: 360bfc95-909a-471c-ba0d-c37f8f135d9d
		summarizeBy: none
		sourceColumn: Revenue Amount

	partition fact_accounts_receivable = m
		mode: import
		source =
				let
					Source = Folder.Files(GoldDataPath & "/facts/fact_accounts_receivable"),
					FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
					FirstFile = FilteredFiles{0}[Content],
					ParquetData = Parquet.Document(FirstFile)
				in
					ParquetData

