/// Monthly operating cash flow, CapEx, and plan OCF per entity.
/// Cash flow and liquidity planning.
table fact_cash_flow
	lineageTag: bd8fabe6-14f1-45f3-bfff-51206000f3ef

	column DateKey
		dataType: int64
		lineageTag: 47ae5fb2-df18-4eca-9a57-3ea4fb7c9d4b
		summarizeBy: none
		sourceColumn: DateKey

	column OrgKey
		dataType: int64
		lineageTag: 5364b72f-2aa7-45cf-ac3b-6e225c97f074
		summarizeBy: none
		sourceColumn: OrgKey

	column 'Operating Cash Flow Amount'
		dataType: double
		lineageTag: 3b06e31d-f7bc-4d9d-9841-975722ed993c
		sourceColumn: Operating Cash Flow Amount

	column 'CapEx Amount'
		dataType: double
		lineageTag: c7ffb9e7-5b32-4a4c-828f-86f2d2ce9c30
		sourceColumn: CapEx Amount

	column 'Plan OCF Amount'
		dataType: double
		lineageTag: b2dd8c16-54c5-4875-b912-3d132fed79fc
		sourceColumn: Plan OCF Amount

	partition fact_cash_flow = m
		mode: import
		source =
				let
					Source = Folder.Files(GoldDataPath & "/facts/fact_cash_flow"),
					FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
					FirstFile = FilteredFiles{0}[Content],
					ParquetData = Parquet.Document(FirstFile)
				in
					ParquetData

