/// Daily cash balance and plan cash per entity.
/// Cash position and liquidity.
table fact_cash_position
	lineageTag: 1ad172bb-142c-4b0e-aae6-7c8e2d9bfb58

	column DateKey
		dataType: int64
		lineageTag: fffe54c6-5845-40b6-95c4-662818474c30
		summarizeBy: none
		sourceColumn: DateKey

	column OrgKey
		dataType: int64
		lineageTag: 6241db20-19a6-4d29-a0f3-c926c698fbc4
		summarizeBy: none
		sourceColumn: OrgKey

	column 'Cash Balance Amount'
		dataType: double
		lineageTag: cdbad8e4-eb6d-48be-a883-a667d0277090
		sourceColumn: Cash Balance Amount

	column 'Plan Cash Amount'
		dataType: double
		lineageTag: 080ea9da-fe4e-4ea4-a978-49eb06aa3ac7
		sourceColumn: Plan Cash Amount

	partition fact_cash_position = m
		mode: import
		source =
				let
					Source = Folder.Files(GoldDataPath & "/facts/fact_cash_position"),
					FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
					FirstFile = FilteredFiles{0}[Content],
					ParquetData = Parquet.Document(FirstFile)
				in
					ParquetData

