/// Failure events per asset (start/end, repair duration, cause) for MTBF and root cause.
/// Reliability and failure analysis.
table fact_ops_failures
	lineageTag: ee7878cf-ae5e-4333-b5ff-208a5a77007b

	column AssetKey
		dataType: int64
		lineageTag: 23e59a09-53c6-4c92-b0a2-57b7ea65f229
		summarizeBy: none
		sourceColumn: AssetKey

	column 'Failure Start DateTime'
		dataType: dateTime
		lineageTag: 57986f24-d9c5-4d89-b409-b729a7822e4a
		summarizeBy: none
		sourceColumn: Failure Start DateTime

		variation Variation
			isDefault
			relationship: 85b87053-b3af-4256-abe1-197c337f18b0
			defaultHierarchy: LocalDateTable_fcfd8f32-5c1c-4af8-94a6-a464af76df39.Datumshierarchie

		annotation SummarizationSetBy = Automatic

	column 'Failure End DateTime'
		dataType: dateTime
		lineageTag: 09007bb7-bb57-4ccd-8007-0ee210164e22
		summarizeBy: none
		sourceColumn: Failure End DateTime

		variation Variation
			isDefault
			relationship: aa897560-2240-43e6-940a-c8df1017e202
			defaultHierarchy: LocalDateTable_eb612d2e-5c00-469e-85d4-7e756fcd3eaf.Datumshierarchie

		annotation SummarizationSetBy = Automatic

	column 'Repair Duration Hours'
		dataType: double
		lineageTag: 8ec9361b-040b-4e2e-99c2-5c2e1e2f7b3a
		summarizeBy: none
		sourceColumn: Repair Duration Hours

		annotation SummarizationSetBy = Automatic

	column 'Downtime Minutes'
		dataType: double
		lineageTag: e1f18446-69a8-4b89-b300-e24dc8dd5562
		summarizeBy: none
		sourceColumn: Downtime Minutes

		annotation SummarizationSetBy = Automatic

	column 'Cause Code'
		dataType: string
		lineageTag: 079c020a-cf13-46f5-a9a6-05cace916b0e
		summarizeBy: none
		sourceColumn: Cause Code

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: int64
		lineageTag: 723bd3d1-1551-434f-bcf9-4b0beb7ae61c
		summarizeBy: none
		sourceColumn: DateKey

	partition fact_ops_failures = m
		mode: import
		source =
				let
					Source = Folder.Files(GoldDataPath & "/facts/fact_ops_failures"),
					FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
					ParquetTables = Table.AddColumn(FilteredFiles, "Parquet", each Parquet.Document([Content])),
					Combined = Table.Combine(ParquetTables[Parquet])
				in
					Combined

