/// Promotion costs and baseline (sales, quantity, non-promo baseline) per promotion.
/// Promo ROI, incremental sales, and cannibalization calculations.
table fact_promo
	lineageTag: 1bb9e993-890b-4e99-b1f2-e0080fd98e7f

	column PromoKey
		dataType: int64
		lineageTag: 16ed868e-b497-4a3d-a5fd-a621a4f2a5db
		summarizeBy: none
		sourceColumn: PromoKey

	column 'Promo Cost'
		dataType: double
		lineageTag: f42dc634-1198-4d99-8572-c18b7aa8006d
		summarizeBy: none
		sourceColumn: Promo Cost

	column 'Funding Amount'
		dataType: double
		lineageTag: 088495fa-1540-4620-bc45-7c29f56bdc73
		summarizeBy: none
		sourceColumn: Funding Amount

	column 'Baseline Sales Amount'
		dataType: double
		lineageTag: 924bb0fb-6d8d-4906-a495-4aa5668fc59d
		summarizeBy: none
		sourceColumn: Baseline Sales Amount

	column 'Baseline Quantity'
		dataType: double
		lineageTag: dbf30e9f-1d5c-42a0-8d06-371938d7f414
		summarizeBy: none
		sourceColumn: Baseline Quantity

	column 'Baseline Non-Promo Sales Amount'
		dataType: double
		lineageTag: 90ea0bc1-3b14-4e94-ad83-c1178ad1ddd2
		summarizeBy: none
		sourceColumn: Baseline Non-Promo Sales Amount

	partition fact_promo = m
		mode: import
		source =
				let
					Source = Folder.Files(GoldDataPath & "/facts/fact_promo"),
					FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
					FirstFile = FilteredFiles{0}[Content],
					ParquetData = Parquet.Document(FirstFile)
				in
					ParquetData

