/// RLS bridge: user to org for row-level security.
/// Scoping report data by user's assigned org(s).
table security_user_org
	lineageTag: security-user-org-rls

	column UserPrincipalName
		dataType: string
		lineageTag: a6197642-ea7c-4b11-981e-6c7959b00141
		sourceColumn: UserPrincipalName

	column OrgKey
		dataType: int64
		lineageTag: 2f5972ab-d3ef-491e-9bcc-3d37376181b2
		summarizeBy: none
		sourceColumn: OrgKey

	column Region
		dataType: string
		lineageTag: 5723ebb2-3942-44f4-85c9-a8e667f80544
		sourceColumn: Region

	column Country
		dataType: string
		lineageTag: 8bf79b76-77dd-489a-bb76-2bfd8a95b0a7
		sourceColumn: Country

	column Channel
		dataType: string
		lineageTag: 197047ee-e254-4e15-bb62-0cc2953a7e51
		sourceColumn: Channel

	partition security_user_org = m
		mode: import
		source =
				let
					Source = Folder.Files(GoldDataPath & "/security_user_org"),
					FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
					FirstFile = FilteredFiles{0}[Content],
					ParquetData = Parquet.Document(FirstFile)
				in
					ParquetData

