/// Organization dimension (region, channel, queue, agent group) for experience
table dim_org
	lineageTag: a6709dd6-64c2-577f-8018-22c5ae8dabbf
	column OrgKey
		dataType: Int64
		sourceColumn: OrgKey
		summarizeBy: none
		isHidden
	column Region
		dataType: String
		sourceColumn: Region
		summarizeBy: none
	column Channel
		dataType: String
		sourceColumn: Channel
		summarizeBy: none
	column Queue
		dataType: String
		sourceColumn: Queue
		summarizeBy: none
	column 'Agent Group'
		dataType: String
		sourceColumn: Agent Group
		summarizeBy: none
	partition dim_org = m
		mode: import
		source =
			let
				Source = Folder.Files(GoldDataPath & "/dimensions/dim_org"),
				FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
				FirstFile = FilteredFiles{0}[Content],
				ParquetData = Parquet.Document(FirstFile)
			in
				ParquetData
	hierarchy 'Org Hierarchy'
		lineageTag: 20da60d9-b6da-51d0-95d8-4f2d223afe62
		level Region
			column: Region
		level Channel
			column: Channel
		level Queue
			column: Queue
