/// Planned sales and COGS at product-month grain for variance vs plan.
table fact_plan_sales
		lineageTag: c66eba9b-38ec-4704-a146-d3be05d1d146

		column DateKey
			dataType: Int64
			sourceColumn: DateKey
			summarizeBy: none

		column OrgKey
			dataType: Int64
			sourceColumn: OrgKey
			summarizeBy: none

		column ProductKey
			dataType: Int64
			sourceColumn: ProductKey
			summarizeBy: none

		column 'Plan Net Sales Amount'
			dataType: Decimal
			sourceColumn: Plan Net Sales Amount
			summarizeBy: none

		column 'Plan Cost of Goods Sold Amount'
			dataType: Decimal
			sourceColumn: Plan Cost of Goods Sold Amount
			summarizeBy: none

		column 'Plan Gross Margin Amount'
			dataType: Decimal
			sourceColumn: Plan Gross Margin Amount
			summarizeBy: none

		partition fact_plan_sales = m
			mode: import
			source =
			let
					Source = Folder.Files(GoldDataPath & "/facts/fact_plan_sales"),
					FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
					FirstFile = FilteredFiles{0}[Content],
					ParquetData = Parquet.Document(FirstFile)
					in
					ParquetData

