table Geography
	lineageTag: 7fff028a-00fa-4654-aa08-fb245edc8f8b

	column GeographyKey
		dataType: double
		isHidden
		lineageTag: 140e9ed3-182c-482e-a605-00b0ffc3d82f
		summarizeBy: none
		sourceColumn: GeographyKey

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GeographyType
		dataType: string
		lineageTag: 17689ace-455b-47e6-b327-a921b2f9c5c6
		summarizeBy: none
		sourceColumn: GeographyType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column ContinentName
		dataType: string
		lineageTag: 5134d920-9256-4ba6-b8b4-21f533ac8690
		summarizeBy: none
		sourceColumn: ContinentName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column RegionCountryName
		dataType: string
		lineageTag: 04d183b5-98b2-4a4e-af6e-26279effe89e
		summarizeBy: none
		sourceColumn: RegionCountryName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition Geography-58d372dd-b829-4a56-ab9b-7254792b8d12 = m
		mode: import
		source =
				let
				    Source = Access.Database(File.Contents("C:\Users\owend\Documents\ContosoSalesV31_64bit.accdb")),
				    _DimGeography = Source{[Schema="",Item="DimGeography"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(_DimGeography,{"ETLLoadID", "LoadDate", "UpdateDate"})
				in
				    #"Removed Columns"

	annotation ColumnsMetadata = {"Columns":[{"Name":"GeographyKey","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimGeography.{GeographyKey,0}"},{"Name":"GeographyType","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimGeography.{GeographyType,1}"},{"Name":"ContinentName","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimGeography.{ContinentName,2}"},{"Name":"RegionCountryName","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimGeography.{RegionCountryName,3}"}]}

	annotation PBI_ResultType = Table

