table Stores
	lineageTag: 03ed55d6-c882-4191-955d-d2cbb1f56754

	column StoreKey
		dataType: double
		isHidden
		lineageTag: 23717da6-22ae-42f3-960f-9e687a72f21d
		summarizeBy: none
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GeographyKey
		dataType: double
		isHidden
		lineageTag: c6c6087d-ce93-4fd4-b556-678fddbda15d
		summarizeBy: none
		sourceColumn: GeographyKey

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column StoreType
		dataType: string
		lineageTag: 6e09fb09-c1d5-499f-8c0b-782bc6299d67
		summarizeBy: none
		sourceColumn: StoreType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column StoreName
		dataType: string
		lineageTag: fb44042c-be42-43d0-aa03-d03ecde4da0b
		summarizeBy: none
		sourceColumn: StoreName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Status
		dataType: string
		lineageTag: f53d011e-8fc6-4a09-b123-00fab78220b6
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column CloseReason
		dataType: string
		lineageTag: 02a4828d-a5f9-4719-a901-f2fc73aae100
		summarizeBy: none
		sourceColumn: CloseReason

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column EmployeeCount
		dataType: double
		lineageTag: 5fa4a0ee-aacb-4f78-a44f-ad29a93dbb6e
		summarizeBy: sum
		sourceColumn: EmployeeCount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SellingAreaSize
		dataType: double
		lineageTag: f392e875-6db4-4a64-a7e4-df9f53586a24
		summarizeBy: sum
		sourceColumn: SellingAreaSize

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Stores-9adb2fe5-82cc-4247-9cbf-199daa1f6820 = m
		mode: import
		source =
				let
				    Source = Access.Database(File.Contents("C:\Users\owend\Documents\ContosoSalesV31_64bit.accdb")),
				    _DimStores = Source{[Schema="",Item="DimStores"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(_DimStores,{"StoreManager", "CloseDate", "OpenDate", "ZipCode", "ZipCodeExtension", "StorePhone", "StoreFax", "AddressLine1", "AddressLine2", "LastRemodelDate", "GeoLocation", "Geometry", "ETLLoadID", "LoadDate", "UpdateDate", "EntityKey", "StoreDescription"})
				in
				    #"Removed Columns"

	annotation ColumnsMetadata = {"Columns":[{"Name":"StoreKey","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimStores.{StoreKey,0}"},{"Name":"GeographyKey","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimStores.{GeographyKey,1}"},{"Name":"StoreType","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimStores.{StoreType,3}"},{"Name":"StoreName","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimStores.{StoreName,4}"},{"Name":"Status","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimStores.{Status,6}"},{"Name":"CloseReason","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimStores.{CloseReason,16}"},{"Name":"EmployeeCount","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimStores.{EmployeeCount,17}"},{"Name":"SellingAreaSize","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimStores.{SellingAreaSize,18}"}]}

	annotation PBI_ResultType = Table

