/**
 * HTML Report Builder — Composes sections into a complete downloadable HTML document.
 */

import type { ThemeConfig } from '@/lib/store/project-store';
import type { KpiSnapshot, TrendPoint, WaterfallDriver, EvidenceRow } from '@/lib/dashboard/sample-data';
import { generateReportStyles } from './report-styles';
import {
  renderPulseSection,
  renderTrendSection,
  renderWaterfallSection,
  renderEvidenceSection,
} from './report-sections';
import { renderTableOfContents } from './table-of-contents';

export interface ReportData {
  projectName: string;
  bracketTitle?: string;
  kpis: KpiSnapshot[];
  trend: TrendPoint[];
  trendLabel: string;
  waterfall: WaterfallDriver[];
  evidence: EvidenceRow[];
}

export function buildHtmlReport(data: ReportData, theme: ThemeConfig): string {
  const dateStr = new Date().toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });

  const title = data.bracketTitle
    ? `${data.projectName} — ${data.bracketTitle}`
    : data.projectName;

  const styles = generateReportStyles(theme);
  const pulse = renderPulseSection(data.kpis);
  const trend = renderTrendSection(data.trendLabel, data.trend);
  const waterfall = renderWaterfallSection(data.waterfall);
  const evidence = renderEvidenceSection(data.evidence);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeForAttr(title)} — Board Report</title>
  <style>${styles}</style>
</head>
<body>
  <header>
    <h1>${escapeForHtml(title)}</h1>
    <span class="date">${dateStr}</span>
  </header>

  ${pulse}
  ${trend}
  ${waterfall}
  ${evidence}

  <footer>
    Generated by ActionReady Studio — ${dateStr}
  </footer>
</body>
</html>`;
}

export function buildBoardPackReport(
  reports: ReportData[],
  theme: ThemeConfig,
  projectName: string,
): string {
  const dateStr = new Date().toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });

  const styles = generateReportStyles(theme);
  const toc = renderTableOfContents(reports);
  const sections = reports.map((r, i) => {
    const title = r.bracketTitle ?? 'Overview';
    return `
      <div id="section-${i}" style="page-break-before: always;">
        <h2 style="border-bottom: 2px solid ${theme.primary}; padding-bottom: 8px;">${escapeForHtml(title)}</h2>
        ${renderPulseSection(r.kpis)}
        ${renderEvidenceSection(r.evidence)}
      </div>
    `;
  }).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${escapeForAttr(projectName)} — Board Pack</title>
  <style>${styles}</style>
</head>
<body>
  <header>
    <h1>${escapeForHtml(projectName)} — Board Pack</h1>
    <span class="date">${dateStr}</span>
  </header>

  ${toc}
  ${sections}

  <footer>
    Generated by ActionReady Studio — ${dateStr}
  </footer>
</body>
</html>`;
}

function escapeForHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function escapeForAttr(s: string): string {
  return escapeForHtml(s).replace(/"/g, '&quot;');
}
