#!/usr/bin/env python3
"""
generate_semantic_model.py
==========================
Generates a complete Power BI PBIP Semantic Model folder (TMDL format)
from a Blueprint YAML + Data Contract YAML.

TMDL specification: https://learn.microsoft.com/analysis-services/tmdl/tmdl-overview
Folder structure per domain:
  dist/<Domain>.SemanticModel/
    definition.pbism
    definition/
      model.tmdl          <- model header + ref table declarations
      expressions.tmdl    <- GoldDataPath parameter
      tables/
        <table>.tmdl      <- one file per table (from data contract)
        _Measures.tmdl    <- PRESERVED if exists (generated by generate_tmdl_measures)
      relationships/
        <name>.tmdl       <- one file per relationship (from blueprint)
      roles/
        <name>.tmdl       <- one file per RLS role (from blueprint)

Usage:
  python generate_semantic_model.py --domain Finance
  python generate_semantic_model.py --all
  python generate_semantic_model.py --domain Finance --gold-path /data/gold

Author: Generated from TMDL spec (Microsoft Learn) + Aurora Blueprint
"""

import argparse
import json
import os
import re
import sys
import uuid
from pathlib import Path

import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined
from tooling.utils.yaml_loader import load_yaml  # shared utility

# ─────────────────────────────────────────────────────────────────────────────
# Paths (relative to this script)
# ─────────────────────────────────────────────────────────────────────────────
SCRIPT_DIR   = Path(__file__).parent.resolve()
PBIP_ROOT    = SCRIPT_DIR.parent                                         # products/fabric/powerbi/
PROJECT_ROOT = PBIP_ROOT.parent.parent.parent                            # analytics-usecase-library/
BLUEPRINTS   = PBIP_ROOT / "blueprints"
DIST         = PBIP_ROOT / "dist"
DATA_CONTRACTS = PROJECT_ROOT / "core" / "data_contracts" / "domains"
TEMPLATES    = SCRIPT_DIR / "tmdl_templates"

# ─────────────────────────────────────────────────────────────────────────────
# Domain → data contract filename mapping
# ─────────────────────────────────────────────────────────────────────────────
DOMAIN_CONTRACT = {
    "Commercial":  "commercial_sales.yaml",
    "Finance":     "finance.yaml",
    "Operations":  "operations.yaml",
    "SupplyChain": "supply_chain.yaml",
    "Experience":  "experience.yaml",
}

# ─────────────────────────────────────────────────────────────────────────────
# TMDL data type mapping (from data contract → TMDL/TOM types)
# Source: https://learn.microsoft.com/analysis-services/tmdl/tmdl-reference-tabular-object
# ─────────────────────────────────────────────────────────────────────────────
TYPE_MAP = {
    "int":      "Int64",
    "int64":    "Int64",
    "boolean":  "Boolean",
    "bool":     "Boolean",
    "currency": "Decimal",
    "decimal":  "Decimal",
    "float":    "Decimal",
    "text":     "String",
    "string":   "String",
    "date":     "DateTime",
    "datetime": "DateTime",
}

# ─────────────────────────────────────────────────────────────────────────────
# Jinja2 environment
# ─────────────────────────────────────────────────────────────────────────────
JINJA = Environment(
    loader=FileSystemLoader(str(TEMPLATES)),
    keep_trailing_newline=True,
    trim_blocks=True,
    lstrip_blocks=True,
    undefined=StrictUndefined,
)


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def stable_uuid(seed: str) -> str:
    """Generate a deterministic UUID from a seed string (reproducible across runs)."""
    return str(uuid.uuid5(uuid.NAMESPACE_DNS, seed))


def tmdl_name(col_name: str) -> str:
    """Wrap column/measure names in single quotes if they contain spaces or dots."""
    if " " in col_name or "." in col_name or "'" in col_name:
        escaped = col_name.replace("'", "''")
        return f"'{escaped}'"
    return col_name


def dax_to_single_line(dax: str) -> str:
    """Collapse a multi-line DAX expression to a single line (for RLS filters)."""
    return " ".join(line.strip() for line in dax.strip().splitlines() if line.strip())


def get_subfolder(table_name: str) -> str:
    """Determine the gold data sub-folder from the table naming convention."""
    if table_name.startswith("dim_"):
        return "dimensions"
    elif table_name.startswith("fact_"):
        return "facts"
    elif table_name.startswith("security_"):
        return "security"
    return "other"


def quote_if_spaces(name: str) -> str:
    """Return name wrapped in single quotes if it contains whitespace."""
    if " " in name:
        return f"'{name}'"
    return name


# load_yaml imported from tooling.utils.yaml_loader above


# ─────────────────────────────────────────────────────────────────────────────
# Data contract parser
# ─────────────────────────────────────────────────────────────────────────────

def load_data_contract(domain: str) -> dict:
    """Load and index a data contract by table name."""
    contract_file = DATA_CONTRACTS / DOMAIN_CONTRACT[domain]
    if not contract_file.exists():
        raise FileNotFoundError(f"Data contract not found: {contract_file}")
    raw = load_yaml(contract_file)
    tables = {}
    for section in ("dimension", "fact"):
        for tbl in raw.get(section, []):
            tables[tbl["name"]] = {
                "kind": section,
                "description": tbl.get("description", tbl["name"]),
                "columns": tbl.get("columns", []),
            }
    return tables


def build_columns(table_name: str, contract_entry: dict) -> list[dict]:
    """Build column context list from a data contract entry."""
    cols = []
    for c in contract_entry.get("columns", []):
        name = c["name"]
        raw_type = c.get("type", "text")
        tmdl_type = TYPE_MAP.get(raw_type.lower(), "String")
        # Key columns and FK columns are hidden in dimension tables; FK in facts are not hidden
        is_key = (c.get("role") == "key")
        is_dim = contract_entry["kind"] == "dimension"
        cols.append({
            "tmdl_name":     quote_if_spaces(name),
            "source_column": name,
            "data_type":     tmdl_type,
            "is_hidden":     is_key and is_dim,
        })
    return cols


# ─────────────────────────────────────────────────────────────────────────────
# Relationship direction
# Per TMDL spec: fromColumn = the "many" side, toColumn = the "one" side.
# Blueprint convention: from_table = one side (cardinality one-to-many)
#                       from_table = many side (cardinality many-to-one)
# ─────────────────────────────────────────────────────────────────────────────

def resolve_relationship(rel: dict) -> dict:
    """Map blueprint cardinality to TMDL from/to sides."""
    cardinality = rel.get("cardinality", "one-to-many")
    ft, fc = rel["from_table"], rel["from_column"]
    tt, tc = rel["to_table"],   rel["to_column"]

    if cardinality == "one-to-many":
        # blueprint from = one side → TMDL to side
        # blueprint to   = many side → TMDL from side
        tmdl_from_table, tmdl_from_col = tt, tc
        tmdl_to_table,   tmdl_to_col   = ft, fc
    else:
        # many-to-one or many-to-many: blueprint from = many → TMDL from
        tmdl_from_table, tmdl_from_col = ft, fc
        tmdl_to_table,   tmdl_to_col   = tt, tc

    # File name: <one-side-table>_<many-side-table>
    rel_name = f"{tmdl_to_table}_{tmdl_from_table}"

    return {
        "rel_name":     rel_name,
        "from_table":   tmdl_from_table,
        "from_column":  tmdl_from_col,
        "to_table":     tmdl_to_table,
        "to_column":    tmdl_to_col,
        "cross_filter": rel.get("cross_filter", "single"),
        "is_inactive":  rel.get("is_inactive", False),
    }


# ─────────────────────────────────────────────────────────────────────────────
# Core generator
# ─────────────────────────────────────────────────────────────────────────────

def generate_domain(domain: str, gold_path: str, dry_run: bool = False):
    print(f"\n{'='*60}")
    print(f"  Generating: {domain}")
    print(f"{'='*60}")

    # 1. Load blueprint
    bp_path = BLUEPRINTS / f"{domain}.yaml"
    if not bp_path.exists():
        print(f"  ❌  Blueprint not found: {bp_path}")
        return
    blueprint = load_yaml(bp_path)

    # 2. Load data contract
    contract = load_data_contract(domain)

    # 3. Collect all tables from blueprint
    dim_tables   = [t for t in blueprint.get("tables", {}).get("dimensions", [])]
    fact_tables  = [t for t in blueprint.get("tables", {}).get("facts", [])]
    sec_tables   = [t for t in blueprint.get("tables", {}).get("security", [])]

    def tname(t): return t if isinstance(t, str) else t["table_name"]

    all_dim  = [tname(t) for t in dim_tables]
    all_fact = [tname(t) for t in fact_tables]
    all_sec  = [tname(t) for t in sec_tables]

    # 4. Output paths
    model_dir = DIST / f"{domain}.SemanticModel"
    def_dir   = model_dir / "definition"
    tbl_dir   = def_dir / "tables"
    rel_dir   = def_dir / "relationships"
    role_dir  = def_dir / "roles"

    if not dry_run:
        for d in [def_dir, tbl_dir, rel_dir, role_dir]:
            d.mkdir(parents=True, exist_ok=True)

    # 5. definition.pbism
    pbism = {
        "settings": {},
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/semanticModel/definitionProperties/1.0.0/schema.json",
        "version": "4.2"
    }
    write_file(model_dir / "definition.pbism", json.dumps(pbism, indent=4), dry_run)

    # 6. model.tmdl
    # All tables: dims + facts + security + standard measure tables
    all_table_names = (
        ["_ActionReady_Logic", "_Measures"]
        + all_dim
        + all_fact
        + all_sec
    )
    model_content = JINJA.get_template("model.tmdl.j2").render(
        all_tables=all_table_names
    )
    write_file(def_dir / "model.tmdl", model_content, dry_run)

    # 7. expressions.tmdl
    expr_content = JINJA.get_template("expressions.tmdl.j2").render(
        gold_data_path=gold_path,
        gold_data_path_tag=stable_uuid(f"{domain}.GoldDataPath"),
    )
    write_file(def_dir / "expressions.tmdl", expr_content, dry_run)

    # 8. Table files — dimensions and facts from data contract
    table_tpl = JINJA.get_template("table.tmdl.j2")
    sec_tpl   = JINJA.get_template("security_table.tmdl.j2")

    generated_tables = []

    for tbl_entry in dim_tables + fact_tables:
        tname_str = tname(tbl_entry)
        meta = tbl_entry if isinstance(tbl_entry, dict) else {}
        contract_entry = contract.get(tname_str)

        if contract_entry is None:
            print(f"  ⚠️  Table '{tname_str}' not in data contract — skipping table file")
            continue

        cols = build_columns(tname_str, contract_entry)
        desc = meta.get("description", contract_entry.get("description", tname_str))

        # Hierarchies from blueprint (if present)
        hierarchies = []
        if isinstance(tbl_entry, dict):
            for h in tbl_entry.get("hierarchies", []):
                hierarchies.append({
                    "name":   h["name"],
                    "tag":    stable_uuid(f"{domain}.{tname_str}.{h['name']}"),
                    "levels": h["levels"],
                })

        ctx = {
            "table_name":  tname_str,
            "description": desc,
            "lineage_tag": stable_uuid(f"{domain}.{tname_str}"),
            "subfolder":   get_subfolder(tname_str),
            "columns":     cols,
            "hierarchies": hierarchies,
        }
        write_file(tbl_dir / f"{tname_str}.tmdl", table_tpl.render(**ctx), dry_run)
        generated_tables.append(tname_str)

    for tbl_entry in sec_tables:
        tname_str = tname(tbl_entry)
        ctx = {"lineage_tag": stable_uuid(f"{domain}.{tname_str}")}
        write_file(tbl_dir / f"{tname_str}.tmdl", sec_tpl.render(**ctx), dry_run)
        generated_tables.append(tname_str)

    # 9. Relationship files
    rel_tpl = JINJA.get_template("relationship.tmdl.j2")
    rels    = blueprint.get("relationships", [])
    for rel in rels:
        r = resolve_relationship(rel)
        content = rel_tpl.render(**r)
        write_file(rel_dir / f"{r['rel_name']}.tmdl", content, dry_run)

    # 10. Role files
    role_tpl = JINJA.get_template("role.tmdl.j2")
    for role in blueprint.get("security_roles", []):
        table_permissions = [
            {
                "table":          t,
                "dax_single_line": dax_to_single_line(role["dax_filter"]),
            }
            for t in role.get("applies_to_tables", [])
        ]
        content = role_tpl.render(
            role_name=role["role_name"],
            table_permissions=table_permissions,
        )
        write_file(role_dir / f"{role['role_name']}.tmdl", content, dry_run)

    # 11. Summary
    print(f"  ✅  Tables:        {len(generated_tables)}")
    print(f"  ✅  Relationships: {len(rels)}")
    print(f"  ✅  Roles:         {len(blueprint.get('security_roles', []))}")
    print(f"  ✅  Output:        dist/{domain}.SemanticModel/")
    if tbl_dir.exists():
        preserved = [f.name for f in tbl_dir.iterdir() if f.name.startswith("_")]
        if preserved:
            print(f"  ℹ️   Preserved:     {', '.join(preserved)} (not overwritten)")


def write_file(path: Path, content: str, dry_run: bool):
    if dry_run:
        print(f"  [DRY-RUN] Would write: {path.name}")
        return
    # Preserve existing _Measures.tmdl and _ActionReady_Logic.tmdl
    if path.name.startswith("_") and path.exists():
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Generate Power BI TMDL Semantic Model files from Blueprint YAML."
    )
    parser.add_argument(
        "--domain", "-d",
        choices=list(DOMAIN_CONTRACT.keys()),
        help="Single domain to generate (e.g. Finance)",
    )
    parser.add_argument(
        "--all", "-a",
        action="store_true",
        help="Generate all 5 domains",
    )
    parser.add_argument(
        "--gold-path",
        default="showcases/aurora_group/data/gold",
        help="Gold data path for the GoldDataPath Power Query parameter",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be generated without writing files",
    )
    args = parser.parse_args()

    if not args.domain and not args.all:
        parser.print_help()
        sys.exit(1)

    domains = list(DOMAIN_CONTRACT.keys()) if args.all else [args.domain]
    for d in domains:
        generate_domain(d, args.gold_path, dry_run=args.dry_run)

    print(f"\n✅  Done. {len(domains)} domain(s) processed.")


if __name__ == "__main__":
    main()
