#!/usr/bin/env python3
"""
update_schema_manifest.py — Sync the schema manifest with schema_registry.py.

Run this script after updating any version constant in schema_registry.py.
It rewrites tooling/schemas/pbir/schema_manifest.json so the manifest always
reflects what the generators actually produce.

Usage (from repository root):
    py -3 products/fabric/powerbi/tooling/update_schema_manifest.py
    py -3 products/fabric/powerbi/tooling/update_schema_manifest.py --check-only

--check-only: exit 1 if manifest is out of date without writing (use in CI).
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[4]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from products.fabric.powerbi.tooling.schema_registry import (
    REPORT_SCHEMA,
    PAGE_SCHEMA,
    VISUAL_SCHEMA,
    PAGES_METADATA_SCHEMA,
    VERSION_METADATA_SCHEMA,
    DEFINITION_PBIR_SCHEMA,
    SEMANTIC_MODEL_SCHEMA,
    PLATFORM_PROPERTIES_SCHEMA,
    THEME_SCHEMA_PINNED_VERSION,
    THEME_SCHEMA_URL,
)

_MANIFEST_PATH = _REPO_ROOT / "tooling" / "schemas" / "pbir" / "schema_manifest.json"


def _extract_version(url: str) -> str:
    """Extract version segment from a schema URL (e.g. '2.3.0' from .../2.3.0/schema.json)."""
    parts = url.rstrip("/").rstrip("schema.json").rstrip("/").rsplit("/", 1)
    return parts[-1] if parts else "unknown"


def _build_manifest() -> dict:
    """Build the manifest dict from the current registry constants."""
    return {
        "_note": (
            "Auto-generated by products/fabric/powerbi/tooling/update_schema_manifest.py. "
            "Edit schema_registry.py first, then re-run that script."
        ),
        "generated_at": str(date.today()),
        "schemas": {
            "report": {
                "logical_name": "report",
                "pinned_version": _extract_version(REPORT_SCHEMA),
                "url": REPORT_SCHEMA,
                "cached_file": "tooling/schemas/pbir/report.schema.json",
                "applies_to": "definition/report.json inside .Report folders",
            },
            "page": {
                "logical_name": "page",
                "pinned_version": _extract_version(PAGE_SCHEMA),
                "url": PAGE_SCHEMA,
                "cached_file": "tooling/schemas/pbir/page.schema.json",
                "applies_to": "definition/pages/<id>/page.json inside .Report folders",
            },
            "visual": {
                "logical_name": "visual",
                "pinned_version": _extract_version(VISUAL_SCHEMA),
                "url": VISUAL_SCHEMA,
                "cached_file": "tooling/schemas/pbir/visual.schema.json",
                "applies_to": "definition/pages/<id>/visuals/<id>/visual.json inside .Report folders",
            },
            "pages_metadata": {
                "logical_name": "pages_metadata",
                "pinned_version": _extract_version(PAGES_METADATA_SCHEMA),
                "url": PAGES_METADATA_SCHEMA,
                "cached_file": None,
                "applies_to": "definition/pages/pages.json inside .Report folders",
            },
            "version_metadata": {
                "logical_name": "version_metadata",
                "pinned_version": _extract_version(VERSION_METADATA_SCHEMA),
                "url": VERSION_METADATA_SCHEMA,
                "cached_file": None,
                "applies_to": "definition/version.json inside .Report folders",
            },
            "definition_pbir": {
                "logical_name": "definition_pbir",
                "pinned_version": _extract_version(DEFINITION_PBIR_SCHEMA),
                "url": DEFINITION_PBIR_SCHEMA,
                "cached_file": "tooling/schemas/pbir/definition.pbir.schema.json",
                "applies_to": "definition.pbir at .Report root",
            },
            "semantic_model": {
                "logical_name": "semantic_model",
                "pinned_version": _extract_version(SEMANTIC_MODEL_SCHEMA),
                "url": SEMANTIC_MODEL_SCHEMA,
                "cached_file": None,
                "applies_to": "definition.pbism at .SemanticModel root",
            },
            "platform_properties": {
                "logical_name": "platform_properties",
                "pinned_version": _extract_version(PLATFORM_PROPERTIES_SCHEMA),
                "url": PLATFORM_PROPERTIES_SCHEMA,
                "cached_file": None,
                "applies_to": ".platform files in Fabric Git integration",
            },
            "theme": {
                "logical_name": "theme",
                "pinned_version": THEME_SCHEMA_PINNED_VERSION,
                "url": THEME_SCHEMA_URL,
                "cached_file": f"products/fabric/powerbi/tooling/reportThemeSchema-{THEME_SCHEMA_PINNED_VERSION}.json",
                "applies_to": "$schema in Power BI theme JSON files",
            },
        },
    }


def _manifests_equal(a: dict, b: dict) -> bool:
    """Compare two manifests ignoring generated_at timestamp."""
    def _normalised(m: dict) -> dict:
        return {k: v for k, v in m.items() if k != "generated_at"}
    return _normalised(a) == _normalised(b)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check-only",
        action="store_true",
        help="Exit 1 if manifest is out of date without writing.",
    )
    args = parser.parse_args()

    new_manifest = _build_manifest()

    current: dict | None = None
    if _MANIFEST_PATH.exists():
        try:
            current = json.loads(_MANIFEST_PATH.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            current = None

    if current and _manifests_equal(current, new_manifest):
        print("schema_manifest.json is up to date.")
        return 0

    if args.check_only:
        print(
            "FAIL: schema_manifest.json is out of date with schema_registry.py.\n"
            "  Fix: py -3 products/fabric/powerbi/tooling/update_schema_manifest.py",
            file=sys.stderr,
        )
        return 1

    _MANIFEST_PATH.write_text(
        json.dumps(new_manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
        newline="\n")
    print(f"Updated {_MANIFEST_PATH.relative_to(_REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
