#!/usr/bin/env python3
"""Resource-grounded analysis of measure identity (Phase B grounding).

A measure's identity is its *resource* (the columns/measures it aggregates) and
*purpose* (the KPI it backs) — not its display name. This tool groups all
measures by name, computes each instance's resource signature
(aggregation + referenced columns/measures), and classifies duplicate-name
groups:

- UNIFY            same resource & aggregation across all instances -> one
                   canonical measure (define once, behavior-preserving).
- DISTINCT         same name, different resources -> genuinely different
                   measures; keep separate (name overlap is misleading).
- (flagged) DRIFT  instances that share a kpi_id_ref but diverge in resource ->
                   one governed KPI with multiple implementations; reconcile.

Writes a Markdown worksheet to tooling/codegen/reports/measure_grounding.md.
"""
from __future__ import annotations

import glob
import re
from collections import defaultdict
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "tooling/codegen/reports/measure_grounding.md"


def slug(s: str) -> str:
    return re.sub(r"_+", "_", re.sub(r"[^a-z0-9]+", "_", s.lower())).strip("_")


def resources(e: dict) -> tuple:
    """(aggregation, frozenset(columns), frozenset(measure_refs)) for the measure."""
    cols: set[str] = set()
    deps = e.get("dependencies") or {}
    for c in deps.get("columns") or []:
        cols.add(c.strip())
    dax = (e.get("expression") or {}).get("logical", "") or ""
    rhs = dax.split("=", 1)[1] if "=" in dax else dax
    table_cols = {f"{t}[{c}]" for t, c in re.findall(r"(\w+)\[([^\]]+)\]", rhs)}
    cols |= table_cols
    meas = set(re.findall(r"(?<![\w\]])\[([^\]]+)\]", rhs))
    agg = (e.get("expression") or {}).get("aggregation_method")
    return agg, frozenset(cols), frozenset(meas)


def load() -> dict:
    kpi = {}
    for f in glob.glob(str(REPO / "core/kpi_catalog/kpis/*.yaml")):
        if Path(f).name == "_index.yaml":
            continue
        k = yaml.safe_load(open(f, encoding="utf-8"))
        kpi[k["kpi_id"]] = k
    groups = defaultdict(list)
    for f in sorted(glob.glob(str(REPO / "core/semantic_models/domains/*/measures/*.yaml"))):
        if Path(f).name == "_index.yaml":
            continue
        dom = Path(f).parts[-3]
        e = yaml.safe_load(open(f, encoding="utf-8"))
        groups[slug(e["measure_name"])].append((dom, e))
    return kpi, groups


def main() -> int:
    kpi, groups = load()
    multi = {k: v for k, v in groups.items() if len(v) > 1}
    unify, distinct = [], []
    for k, insts in sorted(multi.items()):
        sigs = {resources(e) for _, e in insts}
        (unify if len(sigs) == 1 else distinct).append((k, insts))

    def kpi_drift(insts) -> bool:
        by_ref = defaultdict(set)
        for _, e in insts:
            if e.get("kpi_id_ref"):
                by_ref[e["kpi_id_ref"]].add(resources(e))
        return any(len(s) > 1 for s in by_ref.values())

    L = []
    L.append("# Measure grounding worksheet\n")
    L.append("_Generated by `tooling/codegen/measure_grounding.py`. Identity = resource "
             "(columns/measures aggregated) + purpose (KPI), not display name._\n")
    L.append(f"- Total measures: **{sum(len(v) for v in groups.values())}** in "
             f"**{len(groups)}** name-groups\n"
             f"- Duplicate-name groups: **{len(multi)}** "
             f"(UNIFY **{len(unify)}**, DISTINCT **{len(distinct)}**)\n")

    L.append("\n## UNIFY — one measure (same resource + aggregation): define once\n")
    for k, insts in unify:
        doms = ", ".join(sorted({d for d, _ in insts}))
        refs = sorted({e.get("kpi_id_ref") for _, e in insts if e.get("kpi_id_ref")})
        L.append(f"- **{k}** ×{len(insts)} — {doms}" + (f" — kpi `{refs[0]}`" if refs else ""))

    L.append("\n## DISTINCT — different measures sharing a name (different resources)\n")
    for k, insts in distinct:
        flag = " ⚠️ **same-KPI drift — reconcile**" if kpi_drift(insts) else ""
        L.append(f"\n### `{k}`{flag}\n")
        L.append("| domain | semantic_model | folder | agg | resources | kpi | purpose |")
        L.append("|---|---|---|---|---|---|---|")
        for d, e in insts:
            agg, cols, meas = resources(e)
            res = ", ".join(sorted(cols) or sorted(f"[{m}]" for m in meas)) or "—"
            ref = e.get("kpi_id_ref") or "—"
            purpose = ((kpi.get(ref, {}).get("business", {}) or {}).get("purpose", "")
                       if ref != "—" else "")
            L.append(f"| {d} | {e.get('semantic_model','')} | {e.get('display_folder','')} | "
                     f"{agg} | {res} | {ref} | {purpose[:80]} |")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT}  (UNIFY={len(unify)} DISTINCT={len(distinct)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
