/// Labor hours per plant-line-month
table fact_labor
	lineageTag: 7fc2929f-2791-54f3-87dc-b249edff6d5c
	column DateKey
		dataType: Int64
		sourceColumn: DateKey
		summarizeBy: none
	column OrgKey
		dataType: Int64
		sourceColumn: OrgKey
		summarizeBy: none
	column 'Labor Hours'
		dataType: Decimal
		sourceColumn: Labor Hours
		summarizeBy: none
	partition fact_labor = m
		mode: import
		source =
			let
				Source = Folder.Files(GoldDataPath & "/facts/fact_labor"),
				FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
				FirstFile = FilteredFiles{0}[Content],
				ParquetData = Parquet.Document(FirstFile)
			in
				ParquetData
