/// Accounts payable and COGS by entity and supplier per month
table fact_accounts_payable
	lineageTag: 97d9d8d5-6dd2-502a-9ac1-3c61c1304650
	column DateKey
		dataType: Int64
		sourceColumn: DateKey
		summarizeBy: none
	column OrgKey
		dataType: Int64
		sourceColumn: OrgKey
		summarizeBy: none
	column SupplierKey
		dataType: Int64
		sourceColumn: SupplierKey
		summarizeBy: none
	column 'AP Amount'
		dataType: Decimal
		sourceColumn: AP Amount
		summarizeBy: none
	column 'COGS Amount'
		dataType: Decimal
		sourceColumn: COGS Amount
		summarizeBy: none
	partition fact_accounts_payable = m
		mode: import
		source =
			let
				Source = Folder.Files(GoldDataPath & "/facts/fact_accounts_payable"),
				FilteredFiles = Table.SelectRows(Source, each Text.EndsWith([Name], ".parquet")),
				FirstFile = FilteredFiles{0}[Content],
				ParquetData = Parquet.Document(FirstFile)
			in
				ParquetData
