table 'Capacity Planning'
	isHidden
	lineageTag: 46fef158-851c-45e7-bf54-7e647b0ef525

	column Season_Calendar = Date('Capacity Planning'[Year], 'Capacity Planning'[Season], 15)
		isHidden
		formatString: Short Date
		lineageTag: 1c6c1c47-aa28-42a6-af11-0d59fb1ccc9a
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column sample_bulk = "Bulk"
		isHidden
		lineageTag: b41a91af-4b3c-40cd-9855-60b832ee28ce
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Sub Agency'
		dataType: string
		isHidden
		lineageTag: e157cf5d-792a-4b70-ab12-e5dbd9012b1f
		summarizeBy: none
		sourceColumn: Sub Agency

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: string
		isHidden
		lineageTag: e854f5ce-4f55-49ff-9fad-017a7b86ee3e
		summarizeBy: none
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Planned_val $' =
			
			
			VAR vPostingDate = 'Capacity Planning'[Season_Calendar]
			VAR vCurrency = "USD"
			Var iCurrency = "EUR"
			VAR vMaxValidFrom =
			    CALCULATE (
			        MAX ( CPBI_PLANKURS[Datum] ) ,
			        CPBI_PLANKURS[Nach-Waehrung] = vCurrency &&
			        CPBI_PLANKURS[Von-Waehrung] = iCurrency &&
			        CPBI_PLANKURS[Datum] <= vPostingDate
			    )
			VAR vRate =
			    CALCULATE (
			        MAX ( CPBI_PLANKURS[Kurs] ),
			        CPBI_PLANKURS[Nach-Waehrung] = vCurrency &&
			        CPBI_PLANKURS[Von-Waehrung] = iCurrency &&
			        CPBI_PLANKURS[Datum] = vMaxValidFrom
			    )
			
			Return
			
			'Capacity Planning'[Planned_val] * vRate
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 33a4865b-331f-4fc7-9d71-481e8e3a7539
		summarizeBy: sum

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Vendor ID'
		dataType: string
		isHidden
		lineageTag: cd4da36f-07ab-4d55-a08c-b0e83a7e12a1
		summarizeBy: none
		sourceColumn: Vendor ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Brand ID'
		dataType: string
		isHidden
		lineageTag: df1b18e9-9ea8-487e-b3f3-31321d382a21
		summarizeBy: none
		sourceColumn: Brand ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Gender ID'
		dataType: string
		isHidden
		lineageTag: 41f14219-7226-4166-b49b-bab984173ad2
		summarizeBy: none
		sourceColumn: Gender ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Line ID'
		dataType: string
		isHidden
		lineageTag: c9ff6fa5-398c-43c6-8ada-c4fe75a1732b
		summarizeBy: none
		sourceColumn: Line ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Main Class ID'
		dataType: string
		isHidden
		lineageTag: cba7abee-2bef-49d4-a4b8-3daf19b34221
		summarizeBy: none
		sourceColumn: Main Class ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Season
		dataType: string
		isHidden
		lineageTag: 97bdf07b-e81b-4b6d-96ab-eb4a36b8dee8
		summarizeBy: none
		sourceColumn: Season

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Planned_pcs
		dataType: int64
		formatString: 0
		lineageTag: 8cbade78-12e0-4aa9-aa1a-7067d10a6c99
		summarizeBy: sum
		sourceColumn: Planned_pcs

		annotation SummarizationSetBy = Automatic

	column Planned_val
		dataType: double
		lineageTag: 33b8c373-c340-49fb-9ada-4dd55a9f67ca
		summarizeBy: sum
		sourceColumn: Planned_val

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sourcing Country'
		dataType: string
		lineageTag: 66a9be9a-2ae8-43f2-836d-510d4b0ed6fc
		summarizeBy: none
		sourceColumn: Sourcing Country

		annotation SummarizationSetBy = Automatic

	partition 'Capacity Planning-6319be23-5f63-41cc-8d02-ca281935c9d3' = m
		mode: import
		source =
				let
				    Quelle = Excel.Workbook(File.Contents(File_Source), null, true),
				    #"Capacity Planning_Sheet" = Quelle{[Item="Capacity Planning",Kind="Sheet"]}[Data],
				    #"Höher gestufte Header" = Table.PromoteHeaders(#"Capacity Planning_Sheet", [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"sample_bulk", type text}, {"Sub Agency", type text}, {"Year", type text}, {"Planned_pcs", Int64.Type}, {"Planned_val", type number}, {"Vendor ID", type text}, {"Sourcing Country", type text}, {"Brand ID", type text}, {"Gender ID", type text}, {"Line ID", type text}, {"Main Class ID", type text}, {"Season", type text}}),
				    #"Entfernte Spalten" = Table.RemoveColumns(#"Geänderter Typ",{"sample_bulk"})
				in
				    #"Entfernte Spalten"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

