table CC_VENDOR
	isHidden
	lineageTag: b6b6361d-75ee-4535-b0b0-81fdcfd0ed5f

	column Lieferant
		dataType: string
		isHidden
		lineageTag: 9768af1f-5b17-4c76-9443-e3d03f397edd
		summarizeBy: none
		sourceColumn: Lieferant

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Postleitzahl
		dataType: string
		isHidden
		lineageTag: a215a043-29cb-409e-b75b-2940cbe44302
		summarizeBy: none
		sourceColumn: Postleitzahl

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Textspalte für Attribut 0VENDOR'
		dataType: string
		isHidden
		lineageTag: 6e96537e-e081-4181-96df-c51e1e79de94
		summarizeBy: none
		sourceColumn: Textspalte für Attribut 0VENDOR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition CC_VENDOR-9f284315-7b0e-4871-9310-ea3c4267f5b6 = m
		mode: import
		source =
				let
				    Quelle = Excel.Workbook(File.Contents(File_Source), null, true),
				    CC_VENDOR_Sheet = Quelle{[Item="CC_VENDOR",Kind="Sheet"]}[Data],
				    #"Höher gestufte Header" = Table.PromoteHeaders(CC_VENDOR_Sheet, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"Lieferant", type text}, {"Postleitzahl", type text}, {"Sperrgrund", type text}, {"Textspalte für Attribut 0DISC_REAS", type text}, {"Textspalte für Attribut 0VENDOR", type text}, {"Transportkette", type text}}),
				    #"Gefilterte Zeilen" = Table.SelectRows(#"Geänderter Typ", each [Textspalte für Attribut 0VENDOR] <> null and [Textspalte für Attribut 0VENDOR] <> ""),
				    #"Columns removed by Measure Killer"= Table.RemoveColumns(#"Gefilterte Zeilen",{"Textspalte für Attribut 0DISC_REAS","Transportkette","Sperrgrund"})
				in
				#"Columns removed by Measure Killer"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

