table CCR
	lineageTag: 4e468dfd-4793-4578-9c67-9f4a4881f122

	column 0MATERIAL
		dataType: string
		isHidden
		lineageTag: 77194010-e959-4d50-a443-8d697a893ce7
		summarizeBy: none
		sourceColumn: 0MATERIAL

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'claimed quantity pcs'
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: 58e1d407-81f4-4ece-be77-c8fa271d70b7
		summarizeBy: none
		sourceColumn: claimed quantity pcs

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column claimed_ghvk
		dataType: int64
		isHidden
		formatString: #,0.00
		lineageTag: e175a455-6862-49f6-a1ca-f6562b5b4d81
		summarizeBy: none
		sourceColumn: claimed_ghvk

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'delivered to customer pcs'
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: 585c22f8-ebca-4c0d-8671-6068ddec3551
		summarizeBy: none
		sourceColumn: delivered to customer pcs

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column delivered_ghvk
		dataType: int64
		isHidden
		formatString: #,0.00
		lineageTag: 1102f573-afcd-4b04-b7d5-46757e57a908
		summarizeBy: none
		sourceColumn: delivered_ghvk

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column _SOL_RETURNRS
		dataType: string
		isHidden
		lineageTag: 761be762-79b1-48dc-bf4c-02bcdb4ff5fb
		summarizeBy: none
		sourceColumn: _SOL_RETURNRS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Style (gen.)' = LEFT(RIGHT(CCR[0MATERIAL],10),7)
		isHidden
		lineageTag: 3d99baf2-6681-49ed-aea6-662cd874e9d5
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BILL_DATE
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 40b39bc5-bd68-4c7b-a436-3e9b4a4759e1
		summarizeBy: none
		sourceColumn: BILL_DATE

		variation Variation
			isDefault
			relationship: e99098e4-8de1-4628-a35c-1a6af90db21d
			defaultHierarchy: LocalDateTable_b5fb1908-bcdb-42f4-9c61-c3c956dcadab.Datumshierarchie

		changedProperty = FormatString

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Identifier = YEAR( CCR[BILL_DATE] ) & CCR[0MATERIAL]
		isHidden
		lineageTag: ad677e34-aff9-4987-981a-d0b2cbfa386f
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition CCR-15b9cee8-a774-4c75-ad28-3dc1b3396ea4 = m
		mode: import
		source =
				let
				    Quelle = Csv.Document(File.Contents("C:\Users\florianhaferkorn\OneDrive - Nagarro\Desktop\CCR.csv"),[Delimiter=";", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Höher gestufte Header" = Table.PromoteHeaders(Quelle, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"0MATERIAL", type text}, {"claimed quantity pcs", Int64.Type}, {"claimed_ghvk", Int64.Type}, {"delivered to customer pcs", Int64.Type}, {"delivered_ghvk", Int64.Type}, {"_SOL_RETURNRS", type text}, {"BILL_DATE", type datetime}, {"Identifier", type text}}),
				    #"Entfernte Spalten" = Table.RemoveColumns(#"Geänderter Typ",{"BILL DATE (Year)", "BILL DATE (Month)", "Identifier", "DDDC", "Claim Period in Months", "Claim Period Cluster", "BILL DATE (Week)", "Style (gen.)"}),
				    #"Gefilterte Zeilen" = Table.SelectRows(#"Entfernte Spalten", each ([_SOL_RETURNRS] <> "61" and [_SOL_RETURNRS] <> "62" and [_SOL_RETURNRS] <> "63" and [_SOL_RETURNRS] <> "64" and [_SOL_RETURNRS] <> "65" and [_SOL_RETURNRS] <> "66" and [_SOL_RETURNRS] <> "69" and [_SOL_RETURNRS] <> "71" and [_SOL_RETURNRS] <> "72" and [_SOL_RETURNRS] <> "73" and [_SOL_RETURNRS] <> "74" and [_SOL_RETURNRS] <> "81" and [_SOL_RETURNRS] <> "91" and [_SOL_RETURNRS] <> "92" and [_SOL_RETURNRS] <> "93" and [_SOL_RETURNRS] <> "95" and [_SOL_RETURNRS] <> "96" and [_SOL_RETURNRS] <> "S1" and [_SOL_RETURNRS] <> "S2" and [_SOL_RETURNRS] <> "S4" and [_SOL_RETURNRS] <> "S6")),
				    #"Gefilterte Zeilen1" = Table.SelectRows(#"Gefilterte Zeilen", each [BILL_DATE] > #datetime(2021, 12, 31, 0, 0, 0)),
				    #"Gefilterte Zeilen2" = Table.SelectRows(#"Gefilterte Zeilen1", each not Text.StartsWith([0MATERIAL], "S"))
				in
				    #"Gefilterte Zeilen2"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

