table CPBI_OMS_ARTICLEPERF
	lineageTag: df4788ff-efc3-4a60-94bf-a94665918803

	column UMTAUSCH_stk
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c53edd36-8ad1-4d11-9228-8d18024993cc
		summarizeBy: none
		sourceColumn: UMTAUSCH_stk

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column LIEF_UMS_stk
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 251091f3-a010-4802-bf65-2bbffb42b520
		summarizeBy: none
		sourceColumn: LIEF_UMS_stk

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column UMTAUSCH
		dataType: int64
		isHidden
		lineageTag: aadbbc23-cbd1-45de-9c15-9135661da830
		summarizeBy: none
		sourceColumn: UMTAUSCH

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LIEF_UMS
		dataType: double
		isHidden
		lineageTag: 3efae625-a555-4ab8-b64e-8d9809de3bf4
		summarizeBy: none
		sourceColumn: LIEF_UMS

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Identifier
		dataType: string
		isHidden
		lineageTag: 7d26bd63-2204-4806-9a7b-1c8f17e614a3
		summarizeBy: none
		sourceColumn: Identifier

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Return Reason (Cluster)' = ```
			
			    SWITCH(
			        TRUE() ,
			        CPBI_OMS_ARTICLEPERF[Return Reason ID] = "000010" || CPBI_OMS_ARTICLEPERF[Return Reason ID] = "000071" , "Artikel zu groß (weit / lang)" ,
			        CPBI_OMS_ARTICLEPERF[Return Reason ID] = "000011" || CPBI_OMS_ARTICLEPERF[Return Reason ID] = "000072" , "Artikel zu klein (eng / kurz)" ,
			        CPBI_OMS_ARTICLEPERF[Return Reason ID] = "000012" || CPBI_OMS_ARTICLEPERF[Return Reason ID] = "000076" , "Artikel anders als beschrieben / abgebildet" ,
			        CPBI_OMS_ARTICLEPERF[Return Reason ID] = "000013" || CPBI_OMS_ARTICLEPERF[Return Reason ID] = "000074" , "Artikel gefällt nicht" ,
			        CPBI_OMS_ARTICLEPERF[Return Reason ID] = "000014" || CPBI_OMS_ARTICLEPERF[Return Reason ID] = "000075" , "Qualität spricht nicht der Erwartung" ,
			        CPBI_OMS_ARTICLEPERF[Return Reason ID] = "000073" , "Zur Auswahl bestellt" ,
			        CPBI_OMS_ARTICLEPERF[Return Reason ID] = "000077" , "Artikel defekt" ,
			        CPBI_OMS_ARTICLEPERF[Return Reason ID] = "000078" , "Falscher Artikel geliefert" ,
			        CPBI_OMS_ARTICLEPERF[Return Reason ID] = "000079" , "Zu spät geliefert" ,
			        CPBI_OMS_ARTICLEPERF[Return Reason ID] = "000098" , "Annahme verweigert" ,
			        CPBI_OMS_ARTICLEPERF[Return Reason ID] = "000099" , "Empfänger unbekannt" ,
			        CPBI_OMS_ARTICLEPERF[Return Reason ID] = "000015" , "Sonstiges" ,
			        CPBI_OMS_ARTICLEPERF[Return Reason ID] = "000000" || AND( OR( CPBI_OMS_ARTICLEPERF[Return Reason ID] = "" , CPBI_OMS_ARTICLEPERF[Return Reason ID] = "ST" ) , CPBI_OMS_ARTICLEPERF[UMTAUSCH_stk] > 0 ) , "Ohne Angabe" ,
			        BLANK()
			    )
			```
		lineageTag: 70077b7d-b330-436c-8fa9-554587dce63e
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Return Reason ID'
		dataType: string
		lineageTag: 2d353991-196d-4943-99bf-2b4abf2601c8
		summarizeBy: none
		sourceColumn: Return Reason ID

		annotation SummarizationSetBy = Automatic

	partition CPBI_OMS_ARTICLEPERF = m
		mode: import
		source =
				let
				    Quelle = Csv.Document(File.Contents("C:\Users\florianhaferkorn\OneDrive - Nagarro\Desktop\CPBI_OMS_ARTICLEPERF.csv"),[Delimiter=";", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Höher gestufte Header" = Table.PromoteHeaders(Quelle, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"0CALYEAR", type text}, {"CALMONTH", type text}, {"Artikelvariante", type text}, {"Return Reason", type text}, {"Return Reason ID", type text}, {"UMTAUSCH_stk", Int64.Type}, {"LIEF_UMS_stk", Int64.Type}, {"UMTAUSCH", Int64.Type}, {"LIEF_UMS", type number}}),
				    #"Columns removed by Measure Killer"= Table.RemoveColumns(#"Geänderter Typ",{"Artikelvariante","CALMONTH","0CALYEAR","Return Reason"})
				in
				#"Columns removed by Measure Killer"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

