table CPBI_MATERIAL
	lineageTag: 3e386d0d-437a-4046-8c6e-30af6904381c

	column Kollektionsart
		dataType: string
		isHidden
		lineageTag: 54ebebcc-a311-47fd-b704-b3f4394b2fb7
		summarizeBy: none
		sourceColumn: Kollektionsart

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Kollektionsart Text'
		dataType: string
		isHidden
		lineageTag: 9863c079-8e8f-4117-bc16-7f0c915f520d
		summarizeBy: none
		sourceColumn: Kollektionsart Text

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Sammelartikel
		dataType: string
		isHidden
		lineageTag: 92be57a6-5d5a-4409-be08-1f8e189e028c
		summarizeBy: none
		sourceColumn: Sammelartikel

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Style = RIGHT( CPBI_MATERIAL[sprechende Artikelnummer] , 7 )
		lineageTag: 402ba88a-37db-4d70-9a6b-ca1e5030f77e
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Style Picture' =
			
			CONCATENATE("https://lv-ep-ms-image.prod.az.k8s.intra.local.s.oliver.de/images/article/", Right(CPBI_MATERIAL[Sammelartikel], 7 ) ) & CONCATENATE( CONCATENATE( "/" , CPBI_MATERIAL[Color] ),"?w=500&c=e26d9bbc-c455-49bd-956c-1c34d7e2bdfe" )
		lineageTag: 721d5fd2-31cd-4e4d-a730-43bf34f28eff
		dataCategory: ImageUrl
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		isHidden
		lineageTag: ccd611f5-f66d-4276-a3a5-7f1645fc76b5
		summarizeBy: none
		sourceColumn: Brand

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Brand Text'
		dataType: string
		isHidden
		lineageTag: c9a2046b-9793-4cb4-8537-4788633f1c5b
		summarizeBy: none
		sourceColumn: Brand Text

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		isHidden
		lineageTag: 872f1442-76f9-4d9d-bb06-66fee2a1205b
		summarizeBy: none
		sourceColumn: Gender

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Gender Text'
		dataType: string
		isHidden
		lineageTag: d6796b2d-69c7-4719-84ca-3eac5a5b710e
		summarizeBy: none
		sourceColumn: Gender Text

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Line
		dataType: string
		isHidden
		lineageTag: d91ea763-b6f1-4dbf-a60e-60c38a25aa83
		summarizeBy: none
		sourceColumn: Line

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'sprechende Artikelnummer'
		dataType: string
		isHidden
		lineageTag: 237bc564-71ad-4b97-a411-164c205ad978
		summarizeBy: none
		sourceColumn: sprechende Artikelnummer

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Hauptwarengruppe S4'
		dataType: string
		isHidden
		lineageTag: 83083463-c053-4de4-922d-6ab4096ccef2
		summarizeBy: none
		sourceColumn: Hauptwarengruppe S4

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Hauptwarengruppe S4 Text'
		dataType: string
		isHidden
		lineageTag: 4c912e7f-8b3c-4beb-8a90-49e3ed3831ff
		summarizeBy: none
		sourceColumn: Hauptwarengruppe S4 Text

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'ID-Warengruppe S4'
		dataType: string
		isHidden
		lineageTag: 1bb0f020-3ebb-4ed7-9519-111179eac50b
		summarizeBy: none
		sourceColumn: ID-Warengruppe S4

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'ID-Warengruppe S4 Text'
		dataType: string
		isHidden
		lineageTag: 149a43b2-01be-420f-a81b-4af120718edb
		summarizeBy: none
		sourceColumn: ID-Warengruppe S4 Text

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Unterwarengruppe S4'
		dataType: string
		isHidden
		lineageTag: d8cb4be1-d407-4d9a-944d-b960623c6ce0
		summarizeBy: none
		sourceColumn: Unterwarengruppe S4

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Unterwarengruppe S4 Text'
		dataType: string
		isHidden
		lineageTag: bd27411a-5f7f-49a3-af1e-5f780fed3871
		summarizeBy: none
		sourceColumn: Unterwarengruppe S4 Text

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Group' = ```
			
			    SWITCH(
			        TRUE() ,
			            RIGHT( CPBI_MATERIAL[Product Group_System] , 3 ) = "100" , "MIGRATION" ,
			            RIGHT( CPBI_MATERIAL[Product Group_System] , 3 ) = "110" , "CIRCULAR KNIT" ,
			            RIGHT( CPBI_MATERIAL[Product Group_System] , 3 ) = "120" , "FLAT KNIT" ,
			            RIGHT( CPBI_MATERIAL[Product Group_System] , 3 ) = "130" , "LIGHT WOVEN" ,
			            RIGHT( CPBI_MATERIAL[Product Group_System] , 3 ) = "140" , "DENIM" ,
			            RIGHT( CPBI_MATERIAL[Product Group_System] , 3 ) = "150" , "OUTDOOR" ,
			            RIGHT( CPBI_MATERIAL[Product Group_System] , 3 ) = "160" , "FORMAL WEAR" ,
			            RIGHT( CPBI_MATERIAL[Product Group_System] , 3 ) = "170" , "HEAVY WOVEN" ,
			            RIGHT( CPBI_MATERIAL[Product Group_System] , 3 ) = "180" , "ACCESSORIES" ,
			            RIGHT( CPBI_MATERIAL[Product Group_System] , 3 ) = "190" , "ACCESSORIES FLAT KNIT" ,
			            RIGHT( CPBI_MATERIAL[Product Group_System] , 3 ) = "200" , "NOT YET DEFINED" ,
			            CPBI_MATERIAL[Product Group_System] = "WOVEN" , "HEAVY WOVEN" ,
			            CPBI_MATERIAL[Product Group_System]
			    )
			```
		lineageTag: 23a00d0b-ae38-4faa-9f95-2f7b8264aaad
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Style Variant'
		dataType: string
		lineageTag: b5707c70-d37d-4084-bcdf-dce6b4fc1965
		summarizeBy: none
		sourceColumn: Style Variant

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: 1f35d418-2416-4f53-8d53-353fbb09429c
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column 'Retail Price (UVP) €'
		dataType: double
		lineageTag: d9525919-23b7-4518-aefb-539094824674
		summarizeBy: sum
		sourceColumn: Retail Price (UVP) €

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Material Composition'
		dataType: string
		lineageTag: 17b542f9-ee91-4bd0-a646-4eb602f98bc4
		summarizeBy: none
		sourceColumn: Material Composition

		annotation SummarizationSetBy = Automatic

	column 'Product Group_System'
		dataType: string
		lineageTag: acd73685-3893-4eb1-a2ed-b76b9ad3764f
		summarizeBy: none
		sourceColumn: Product Group_System

		annotation SummarizationSetBy = Automatic

	column 'WHSSP €'
		dataType: int64
		formatString: 0
		lineageTag: d8ebc007-58b2-44c1-b67a-3e5cdd952f27
		summarizeBy: sum
		sourceColumn: WHSSP €

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: Long Date
		lineageTag: 706ac349-45f4-4b2f-bd2d-1f86903e75fc
		summarizeBy: none
		sourceColumn: Created

		variation Variation
			isDefault
			relationship: c21298c0-1ea6-4ca2-972b-cb4bef2b1a9b
			defaultHierarchy: LocalDateTable_addc8431-d44e-4a75-ad02-d16f176032d5.Datumshierarchie

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Line Text'
		dataType: string
		lineageTag: 20fda40f-e633-4bfb-b172-1d959b8db4c8
		summarizeBy: none
		sourceColumn: Line Text

		annotation SummarizationSetBy = Automatic

	partition CPBI_MATERIAL-090bb81f-6394-4236-9f4a-81a3ee6af406 = m
		mode: import
		source =
				let
				    Quelle = Csv.Document(File.Contents("C:\Users\florianhaferkorn\OneDrive - Nagarro\Desktop\CPBI_MATERIAL.csv"),[Delimiter=";", Columns=26, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Höher gestufte Header" = Table.PromoteHeaders(Quelle, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"Style Variant", type text}, {"Color", type text}, {"Kollektionsart", type text}, {"Kollektionsart Text", type text}, {"Sammelartikel", type text}, {"Retail Price (UVP) €", type number}, {"Brand", type text}, {"Brand Text", type text}, {"Gender", type text}, {"Gender Text", type text}, {"Line", type text}, {"Line Text", type text}, {"Material Composition", type any}, {"sprechende Artikelnummer", type text}, {"Hauptwarengruppe S4", type text}, {"Hauptwarengruppe S4 Text", type text}, {"ID-Warengruppe S4", type text}, {"ID-Warengruppe S4 Text", type text}, {"Unterwarengruppe S4", type text}, {"Unterwarengruppe S4 Text", type text}, {"Product Group_System", type text}, {"WHSSP €", Int64.Type}, {"Created", type datetime}}),
				    #"Columns removed by Measure Killer"= Table.RemoveColumns(#"Geänderter Typ",{ "Style", "Style Picture"}),
				    #"Geänderter Typ1" = Table.TransformColumnTypes(#"Columns removed by Measure Killer",{{"Created", type date}}),
				    #"Entfernte Spalten" = Table.RemoveColumns(#"Geänderter Typ1",{"Product Group"})
				in
				    #"Entfernte Spalten"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

