table CSS_Tickets
	lineageTag: a5339313-07bf-4902-b4ff-7cceed840818

	column Artikelnummer
		dataType: string
		isHidden
		lineageTag: 1e834405-52f5-4d67-beaf-7dd570b4b731
		summarizeBy: none
		sourceColumn: Artikelnummer

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CSS_Ticket
		dataType: string
		lineageTag: eec89638-a3b2-4b0f-962e-145876b6e0c3
		summarizeBy: none
		sourceColumn: CSS_Ticket

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: c71c87d7-b0ec-4ed5-b72f-58aa3db41cb0
		summarizeBy: none
		sourceColumn: Status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Style (gen. Article)'
		dataType: string
		isHidden
		lineageTag: cafcaef6-458d-4c6c-9435-244357c799a2
		summarizeBy: none
		sourceColumn: Style (gen. Article)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Claim Reason Code' = CONCATENATE(LEFT(CSS_Tickets[Claim Reason],1), MID(CSS_Tickets[Claim Reason],3,1))
		lineageTag: 7ba07f15-f2cf-4b4e-af77-8eaadc2e8a82
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Claim reason name' = LOOKUPVALUE('Claim reason'[Claim reason name],'Claim reason'[Claim reason],CSS_Tickets[Claim Reason Code])
		lineageTag: 535869bf-2253-453b-8469-73f12ea5cf6b
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Identifier_2 = YEAR( CSS_Tickets[Created] ) & CSS_Tickets[Style (gen. Article)]
		isHidden
		lineageTag: 19fc2618-a757-4d8c-a1f5-6435b4004d44
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Claim Reason'
		dataType: string
		lineageTag: ecfb53d2-8aec-4e54-a5dc-8ab3c4c0f8f1
		summarizeBy: none
		sourceColumn: Claim Reason

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: c9232b36-8cb7-45a7-ba9a-469635ded721
		summarizeBy: none
		sourceColumn: Created

		variation Variation
			isDefault
			relationship: 629991ac-6a50-4f80-8f25-b427322670c0
			defaultHierarchy: LocalDateTable_d930ce65-efbe-4bc0-b03f-1886f89af926.Datumshierarchie

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	partition CSS_Tickets-0efe676f-a690-448e-8408-b93dbc571a4e = m
		mode: import
		source =
				let
				    Quelle = Excel.Workbook(File.Contents(File_Source), null, true),
				    CSS_Tickets_Sheet = Quelle{[Item="CSS_Tickets",Kind="Sheet"]}[Data],
				    #"Höher gestufte Header" = Table.PromoteHeaders(CSS_Tickets_Sheet, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"Artikelnummer", type text}, {"Country", type text}, {"Claim Reason", type text}, {"CSS_Ticket", type text}, {"Created", type datetime}, {"Status", type text}, {"Link", type text}, {"Style (gen. Article)", type text}}),
				    #"Columns removed by Measure Killer"= Table.RemoveColumns(#"Geänderter Typ",{"Link","Country"})
				in
				#"Columns removed by Measure Killer"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

