table Details
	lineageTag: c7bc1d8c-f213-496b-837a-64ddd2da14c7

	column Artikelvariante
		dataType: string
		isHidden
		lineageTag: 1b1d85fa-e8ab-4433-9943-9324a42ca725
		summarizeBy: none
		sourceColumn: Artikelvariante

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HO_akt
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: cd0fbcf8-deac-44c5-a9bb-1b0d981435ec
		summarizeBy: none
		sourceColumn: HO_akt

		variation Variation
			isDefault
			relationship: 52fd7230-048b-4576-83eb-4a52c4454d40
			defaultHierarchy: LocalDateTable_bc2a5fb5-54a8-432c-8e96-a89d6043d6c0.Datumshierarchie

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column HO_best
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: add25ef7-e017-4069-9f36-c96cf41158e6
		summarizeBy: none
		sourceColumn: HO_best

		variation Variation
			isDefault
			relationship: 52bbe495-7e33-4b97-99e2-7c0b9dd62105
			defaultHierarchy: LocalDateTable_af9ff999-700c-4440-b56d-29230fbb5a78.Datumshierarchie

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'PO cancelled (pcs)PO cancelled (pcs)'
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: 42322f58-001d-4ee5-beac-85fa0d61099f
		summarizeBy: sum
		sourceColumn: PO cancelled (pcs)PO cancelled (pcs)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PO overshipped (pcs)'
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: c884d2e4-2424-4f2e-9537-2b33e46e6242
		summarizeBy: none
		sourceColumn: PO overshipped (pcs)

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'PO shortshipped (pcs)'
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: 825290c6-79b3-47a5-8574-eecb27928fd8
		summarizeBy: none
		sourceColumn: PO shortshipped (pcs)

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Delay in days excl. buffer' = ```
			
			    IF(
			        Details[Sub Agency] = "0000013006" , 
			        Details[HO_akt] - ( Details[HO_best] + 10 ) , 
			        Details[HO_akt] - Details[HO_best] 
			    )
			```
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 419cb3fd-df7a-4126-97b5-42062b0de56c
		summarizeBy: sum

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column KPI2137
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: 4852f11b-fa33-4453-a5db-cb816904895c
		summarizeBy: none
		sourceColumn: KPI2137

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isDecimal":true}

	column POconf_after_cxl_pcs
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: 675c30a3-324a-469d-ace1-1e4f4529806b
		summarizeBy: none
		sourceColumn: POconf_after_cxl_pcs

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column sample_bulk
		dataType: string
		isHidden
		lineageTag: 2fdd7b8c-b032-4a9e-818f-c4b8f8059621
		summarizeBy: none
		sourceColumn: sample_bulk

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RT_CONFMAT
		dataType: string
		isHidden
		lineageTag: 1514d222-1178-4786-a9c5-580240b45f9d
		summarizeBy: none
		sourceColumn: RT_CONFMAT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Saison_ALKW_Month_ =
			
			IF(
			    VALUE( RIGHT( Details[Saison_ALKW_Month] , 2 ) ) > 12 ,
			        FORMAT( RIGHT( Details[Saison_ALKW] , 1 ) , "00" ) ,
			        FORMAT( RIGHT( Details[Saison_ALKW] , 2 ) , "0" )
			)
		dataType: string
		isHidden
		lineageTag: 26ba7a5d-67c4-4539-92c5-637a5879b978
		summarizeBy: none

		changedProperty = DataType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WE_DIR_Stk
		dataType: int64
		isHidden
		lineageTag: b55fa383-cc01-4260-8530-eb58802ba640
		summarizeBy: none
		sourceColumn: WE_DIR_Stk

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order Cluster' =
			
			Var QtyperOrder = CALCULATE([PO_conf_pcs], ALLEXCEPT(Details, Details[Purchase Order]))
			Return
			    SWITCH(
			        TRUE(),
			        QtyperOrder <= 500, "A: <= 500",
			        QtyperOrder <= 1000, "B: <= 1.000",
			        QtyperOrder <= 3000, "C: <= 3.000",
			        QtyperOrder <= 5000, "D: <= 5.000",
			        QtyperOrder <= 10000, "E: <= 10.000",
			        "F: > 10.000"
			    )
		lineageTag: 95826445-1eab-4ae7-8b7b-3361839d8272
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Season_Calendar =
			
			IF(
			     VALUE( LEN( Details[Saison_ALKW] ) ) = 6 ,
			        Date( Details[Saison_ALKW_Year] , Details[Saison_ALKW_Month_] , 15 ) ,
			        Date( Details[Saison_ALKW_Year] , RIGHT( Details[Saison_ALKW_Month_] , 1 ) , 15 )
			)
		isHidden
		lineageTag: 90c0b66f-d6bc-48f1-9520-02c373e6352b
		summarizeBy: none

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CITY_MFR
		dataType: string
		isHidden
		lineageTag: 2ab4c6ed-ca8b-41a2-a257-ba20fd87c77b
		dataCategory: Place
		summarizeBy: none
		sourceColumn: CITY_MFR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CITY_VENDOR
		dataType: string
		isHidden
		lineageTag: 3371a3d8-387d-4692-891d-fab63536287e
		dataCategory: Place
		summarizeBy: none
		sourceColumn: CITY_VENDOR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Hersteller
		dataType: string
		isHidden
		lineageTag: 1e215553-b4ac-480c-9533-4303d169deb9
		summarizeBy: none
		sourceColumn: Hersteller

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Liefertermin VZ'
		dataType: string
		isHidden
		lineageTag: c9221b0c-64b1-4d7b-b368-30229b9bcbd6
		summarizeBy: none
		sourceColumn: Liefertermin VZ

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Delivery Date DC' = ```
			
			VAR _Val = VALUE( Details[Liefertermin VZ] )
			
			RETURN
			    IF( 
			        ISBLANK( _Val ) , 
			        BLANK() ,
			        DATE( VALUE( LEFT( _Val , 4 ) ), VALUE( MID( _Val , 5 , 2 ) ) , VALUE( RIGHT( _Val , 2 ) ) )
			    )
			```
		formatString: dd.mm.yyyy
		lineageTag: dd61d03c-8fbc-4ceb-aee0-eed5174fa2d1
		summarizeBy: none

		variation Variation
			isDefault
			relationship: e76dc754-5436-42ea-89d5-657f2e2876e4
			defaultHierarchy: LocalDateTable_c38bd81d-aa4a-4d57-94ab-ce3783e37565.Datumshierarchie

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Handover Status' =
			
			Var OnTime = 0
			Var inTolerance = 5
			
			Return
			IF(
			    Details[sample_bulk] = "BULK" ,
			    Switch(
			        True(),
			            [Delay in days excl. buffer] <= OnTime, "in time",
			            [Delay in days excl. buffer] > OnTime && [Delay in days excl. buffer] <= inTolerance, "nearly overdue",
			            "overdue"
			    ) ,
			    Switch(
			        True(),
			            [Delay in days excl. buffer] <= OnTime, "in time",
			            "overdue"
			    )
			)
		lineageTag: 00474809-37ac-45d8-964a-9586179e0d6d
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column COUNTRY_MFR
		dataType: string
		isHidden
		lineageTag: 0a02de5c-01e9-4bfe-80d8-2d527e689cf5
		summarizeBy: none
		sourceColumn: COUNTRY_MFR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column COUNTRY_VENDOR
		dataType: string
		isHidden
		lineageTag: 4c0029ba-2899-40f0-8d21-8c17537ecf21
		summarizeBy: none
		sourceColumn: COUNTRY_VENDOR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column STREET_MFR
		dataType: string
		isHidden
		lineageTag: bc575da0-9393-4658-b81f-547fe3dac929
		dataCategory: Address
		summarizeBy: none
		sourceColumn: STREET_MFR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column STREET_VENDOR
		dataType: string
		isHidden
		lineageTag: 225e6174-2cea-46d9-ad11-518043613de3
		dataCategory: Address
		summarizeBy: none
		sourceColumn: STREET_VENDOR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Country of Dispatch' = ```
			
			    IF(
			        Details[Country of dispatch (PO)] <> BLANK() ,
			        Details[Country of dispatch (PO)] ,
			        LEFT(    
			            MAXX (
			                FILTER ( CC_LFM1_S4, CC_LFM1_S4[LIFNR] = Details[Vendor] ),
			                CC_LFM1_S4[TRANSPORT_CHAIN]
			            ) , 2 
			        )
			    )
			```
		lineageTag: 6181ac89-9e18-4de2-8bdf-ec91cbff55db
		dataCategory: Country
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PP Ratio Target' = ```
			
			Var _ExceptionTarget = 0.45
			Var _KoopTarget =
			MAXX (
			    FILTER(
			        Targets_PPRatio_BGL ,
			        RELATED( dimBrand[Brand ID] ) = Targets_PPRatio_BGL[Brand] &&
			        RELATED( dimGender[Gender ID] ) = Targets_PPRatio_BGL[Gender] &&
			        RELATED( dimLine[Line ID] ) = Targets_PPRatio_BGL[Line] &&
			        RELATED( dimCollectionType[Collection Type ID] ) = Targets_PPRatio_BGL[Koll.art] &&
			        Details[Season_Calendar] >= Targets_PPRatio_BGL[Gültig ab] &&
			        Details[Season_Calendar] <= Targets_PPRatio_BGL[Gültig bis]
			    ),
			    Targets_PPRatio_BGL[Betrag]
			)
			Var _Lookup_Country =
			MAXX (
			    FILTER(
			        Targets_PPRatio ,
			        RELATED( dimBrand[Brand ID] ) = Targets_PPRatio[Brand] &&
			        RELATED( dimGender[Gender ID] ) = Targets_PPRatio[Gender] &&
			        RELATED( dimLine[Line ID] ) = Targets_PPRatio[Line] &&
			        RELATED( dimCollectionType[Collection Type ID] ) = Targets_PPRatio[Koll.art] &&
			        RELATED( dimMainclass[Main Class ID] ) = Targets_PPRatio[Hauptklass] &&
			        RELATED( dimVendor[Sourcing Country] ) = Targets_PPRatio[AL/R] &&
			        Details[Season_Calendar] >= Targets_PPRatio[Gültig ab] &&
			        Details[Season_Calendar] <= Targets_PPRatio[Gültig bis]
			    ),
			    Targets_PPRatio[Betrag]
			)
			
			Var _Lookup_MC =
			MAXX (
			    FILTER(
			        Targets_PPRatio_MC ,
			        RELATED( dimBrand[Brand ID] ) = Targets_PPRatio_MC[Brand] &&
			        RELATED( dimGender[Gender ID] ) = Targets_PPRatio_MC[Gender] &&
			        RELATED( dimLine[Line ID] ) = Targets_PPRatio_MC[Line] &&
			        RELATED( dimCollectionType[Collection Type ID] ) = Targets_PPRatio_MC[Koll.art] &&
			        RELATED( dimMainclass[Main Class ID] ) = Targets_PPRatio_MC[Hauptklass] &&
			        Details[Season_Calendar] >= Targets_PPRatio_MC[Gültig ab] &&
			        Details[Season_Calendar] <= Targets_PPRatio_MC[Gültig bis]
			    ),
			    Targets_PPRatio_MC[Betrag]
			)
			
			Return
			IF(
			    ISBLANK( _Lookup_Country ) ,
			        IF( 
			            ISBLANK( _Lookup_MC ) ,
			                IF(
			                    ISBLANK( _KoopTarget ) ,
			                    _ExceptionTarget ,
			                    _KoopTarget 
			                ) ,
			            _Lookup_MC
			        ) , 
			    _Lookup_Country
			)
			```
		isHidden
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 16a801a4-8842-40e6-a853-077b73ae1d5a
		summarizeBy: none

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Initial Transport Mode' =
			
			var ActTrans = MID( Details[Initial Transport Chain] , 3 , 2 )
			
			Return
			SWITCH(
			    TRUE(),
			        ActTrans = "AI" , "AIR" ,
			        ActTrans = "SA" , "SEA/AIR" ,
			        ActTrans = "SE" , "SEA" ,
			        ActTrans = "SH" , "SEA" ,
			        ActTrans = "TR" , "TRUCK" ,
			        ActTrans = "CO" , "COURIER" ,
			        "OTHERS"
			)
		lineageTag: c9b1561f-a814-4bed-b82f-af58734a4dbc
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Actual Transport Mode' =
			
			var ActTrans = MID( Details[Actual Transport Chain] , 3 , 2 )
			
			Return
			SWITCH(
			    TRUE(),
			        ActTrans = "AI" , "AIR" ,
			        ActTrans = "SA" , "SEA/AIR" ,
			        ActTrans = "SE" , "SEA" ,
			        ActTrans = "SH" , "SEA" ,
			        ActTrans = "TR" , "TRUCK" ,
			        ActTrans = "CO" , "COURIER" ,
			        "OTHERS"
			)
		lineageTag: a7a71b75-e4aa-43a0-8c2b-ac7aee2fa9c2
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PO_conf_val (PP Ratio Target)' = Details[WHSSP val €] * Details[PP Ratio Target]
		isHidden
		formatString: #,0.00
		lineageTag: 44a31f04-c1ad-4764-acc7-4761b74028c4
		summarizeBy: none

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Retail val' = Details[PO_conf_pcs] * RELATED( CPBI_MATERIAL[Retail Price (UVP) €] )
		isHidden
		formatString: #,0.00
		lineageTag: 2a23fd49-3d42-4765-83c2-68664ca48261
		summarizeBy: none

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'WHSSP val €' = Details[PO_conf_pcs] * RELATED( CPBI_MATERIAL[WHSSP €] )
		isHidden
		formatString: 0
		lineageTag: 42bef733-6682-424d-af3e-7d4b4cc61e10
		summarizeBy: none

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Identifier = Details[Saison_ALKW_Year] & Details[Artikelvariante]
		isHidden
		lineageTag: f02e380a-07a0-4860-85b6-3e787afe61c0
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Identifier_2 = Details[Saison_ALKW_Year] & Details[RT_CONFMAT]
		isHidden
		lineageTag: b148f35f-dcdb-4780-bcbe-b096044bafdc
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PP_FW_CURR
		dataType: string
		isHidden
		lineageTag: 529e083c-dd73-41f4-b476-c8ef345ef5f2
		summarizeBy: none
		sourceColumn: PP_FW_CURR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HSP
		dataType: int64
		lineageTag: 52b446e6-d74f-4037-8a93-d1ae99bb6491
		summarizeBy: none
		sourceColumn: HSP

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Exchange Rate (Plan)' =
			
			
			VAR vPostingDate = Details[Season_Calendar]
			VAR vCurrency = "USD"
			Var iCurrency = "EUR"
			VAR vMaxValidFrom =
			    CALCULATE (
			        MAX ( CPBI_PLANKURS[Datum] ) ,
			        CPBI_PLANKURS[Nach-Waehrung] = vCurrency &&
			        CPBI_PLANKURS[Von-Waehrung] = iCurrency &&
			        CPBI_PLANKURS[Datum] <= vPostingDate
			    )
			VAR vRate =
			    CALCULATE (
			        MAX ( CPBI_PLANKURS[Kurs] ),
			        CPBI_PLANKURS[Nach-Waehrung] = vCurrency &&
			        CPBI_PLANKURS[Von-Waehrung] = iCurrency &&
			        CPBI_PLANKURS[Datum] = vMaxValidFrom
			    )
			
			RETURN
			    vRate
		dataType: double
		formatString: 0.000
		lineageTag: 627ee2aa-1068-42d3-afac-badd5952c81d
		summarizeBy: sum

		changedProperty = DataType

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Exchange Rate (Calc.)' =
			
			
			VAR vPostingDate = Details[Delivery Date DC]
			VAR vCurrency = "USD"
			Var iCurrency = "EUR"
			VAR vMaxValidFrom =
			    CALCULATE (
			        MAX ( CPBI_KALKKURS[Datum] ) ,
			        CPBI_KALKKURS[Nach-Waehrung] = vCurrency &&
			        CPBI_KALKKURS[Von-Waehrung] = iCurrency &&
			        CPBI_KALKKURS[Datum] <= vPostingDate
			    )
			VAR vRate =
			    CALCULATE (
			        MAX ( CPBI_KALKKURS[Kurs] ),
			        CPBI_KALKKURS[Nach-Waehrung] = vCurrency &&
			        CPBI_KALKKURS[Von-Waehrung] = iCurrency &&
			        CPBI_KALKKURS[Datum] = vMaxValidFrom
			    )
			
			RETURN
			    vRate
		formatString: 0.000
		lineageTag: a32930e4-c676-4bd2-98d2-cc66e0710a0a
		summarizeBy: sum

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Year (HO_best)' = YEAR( Details[HO_best] )
		formatString: 0
		lineageTag: 552ad9ba-632a-4f3c-8387-86c42d18b8a4
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Month (HO_best)' = MONTH( Details[HO_best] )
		formatString: 0
		lineageTag: 73d25ed9-98a5-4d92-a805-f79fa712aebf
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column AGY_Comm_pre_calc
		dataType: int64
		isHidden
		formatString: 0.00
		lineageTag: befdcb9a-a08a-43f2-a739-bba36ddc1b53
		summarizeBy: none
		sourceColumn: AGY_Comm_pre_calc

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column customscost_pre_calc
		dataType: int64
		isHidden
		formatString: 0.00
		lineageTag: 240652e2-3771-42a5-abfc-80d5cc4b71ef
		summarizeBy: none
		sourceColumn: customscost_pre_calc

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column freightcost_pre_calc
		dataType: double
		isHidden
		formatString: 0.00
		lineageTag: 07e63d9c-966a-45c4-acf6-40455b71d8d3
		summarizeBy: none
		sourceColumn: freightcost_pre_calc

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Malus_pre_calc
		dataType: int64
		isHidden
		formatString: 0.00
		lineageTag: d33f1e58-82cb-48e5-a020-13052a85effd
		summarizeBy: none
		sourceColumn: Malus_pre_calc

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column PP_CALC_FW
		dataType: double
		isHidden
		formatString: 0.00
		lineageTag: 3aad2f59-356c-44eb-8f8c-95f6004ea613
		summarizeBy: none
		sourceColumn: PP_CALC_FW

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column PP_CALC_HW
		dataType: double
		isHidden
		formatString: 0.00
		lineageTag: a6bc0979-0c6b-4118-b5fe-7876fd58ffa7
		summarizeBy: none
		sourceColumn: PP_CALC_HW

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column samplecost_pre_calc
		dataType: double
		isHidden
		formatString: 0.00
		lineageTag: b7bbaaaf-2af0-4003-98e7-e684522282b7
		summarizeBy: none
		sourceColumn: samplecost_pre_calc

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'COS Target' = ```
			
			
			Var ExceptionTarget = 
			    SWITCH(
			        TRUE() ,
			        MAX( Targets_COS[Year] ) <= 2021 , 0.49 ,
			        MAX( Targets_COS[Year] ) <= 2022 , 0.515 ,
			        0.535
			    )
			    
			Var Lookup =
			MAXX (
			    FILTER(
			        Targets_COS ,
			        RELATED( dimBrand[Brand ID] ) = Targets_COS[Brand] &&
			        RELATED( dimGender[Gender ID] ) = Targets_COS[Gender] &&
			        RELATED( dimLine[Line ID] ) = Targets_COS[Line] &&
			        RELATED( dimCollectionType[Collection Type ID] ) = Targets_COS[Koll.art] &&
			        Details[Season_Calendar] >= Targets_COS[Gültig ab] &&
			        Details[Season_Calendar] <= Targets_COS[Gültig bis]
			    ),
			    Targets_COS[Betrag]
			)
			
			Return
			IF(
			    ISBLANK( Lookup ),
			    ExceptionTarget ,
			    Lookup
			)
			```
		isHidden
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 3f55eee8-7406-40e7-bf9b-72b07965c6d1
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'COS_pre_calc_val (COS Target)' = Details[WHSSP val €] * Details[COS Target]
		isHidden
		formatString: #,0.00
		lineageTag: ce288683-0def-467c-aa48-1b132921ecf4
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Cluster Delay in Days' = ```
			
			var Delay = Details[Delay in days excl. buffer] 
			
			Return
			SWITCH(
			    TRUE(),
			        Delay <= 0 , "A: <= 0" ,
			        Delay <= 5 , "B: <= 5" ,
			        Delay <= 10 , "C: <= 10" ,
			        Delay <= 30 , "D: <= 30" ,
			        "E: > 30" 
			)
			```
		lineageTag: 952e3b1c-d7d6-4436-b0e1-44c5bf5cdeb0
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PO_conf_val $ (PP_Calc)' =
			
			IF(
			    Details[PP_FW_CURR] = "USD",
			    Details[PO_conf_pcs] * Details[PP_CALC_FW] ,
			    Details[PO_conf_pcs] * DIVIDE( Details[PP_CALC_FW] , Details[Exchange Rate (Plan)] , 0 )
			)
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 81cc830e-6dc4-4b70-8c1e-25f367245bc4
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'PO_conf_val € (pre_calc)' =
			
			IF(
			    Details[PP_FW_CURR] = "USD",
			    Details[PO_conf_pcs] * DIVIDE( Details[PP_CALC_FW] , Details[Exchange Rate (Plan)] , 0 ) ,
			    Details[PO_conf_pcs] * Details[PP_CALC_HW]
			)
		isHidden
		formatString: #,0.00
		lineageTag: 2d7d2b37-1dbb-4d33-9b7a-82f9b746117d
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Ordersplit =
			
			IF( CALCULATE( DISTINCTCOUNTNOBLANK( Details[HO_akt] ) , ALLEXCEPT( Details, Details[Purchase Order] ) ) > 1 , TRUE() , FALSE() )
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7542f0a0-27b9-481d-a375-8249d8c9f3ec
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _BSOL_S_KEYLOOK
		dataType: string
		isHidden
		lineageTag: 69a0c13e-2c67-437a-9c68-83f0f14fef02
		summarizeBy: none
		sourceColumn: _BSOL_S_KEYLOOK

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Details","TableItemName":"Key Look (Cluster)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column KSCHL
		dataType: string
		lineageTag: 1b572231-3db7-4d27-90ab-dcddfbc8e82d
		summarizeBy: none
		sourceColumn: KSCHL

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column GB/NB = ```
			
			    SWITCH(
			        TRUE(),
			            LEFT( Details[Purchase Order] , 2 ) = "47" , "NB" ,
			            "GB"
			    )
			```
		lineageTag: ff543ffb-7252-4a7e-b49f-6e6d434290ae
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Key Look (Cluster)' =
			SWITCH(
				TRUE,
				ISBLANK('Details'[_BSOL_S_KEYLOOK]),
				"(Leer)",
				'Details'[_BSOL_S_KEYLOOK] IN {""},
				"NO",
				"YES"
			)
		lineageTag: 46cfb31a-3927-41a3-a2b3-d79b75154839
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Details"
				          }
				        },
				        "Property": "_BSOL_S_KEYLOOK"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"d","Entity":"Details"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"_BSOL_S_KEYLOOK"}}],"GroupItems":[{"DisplayName":"(Leer)","BlankDefaultPlaceholder":true},{"DisplayName":"NO","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"_BSOL_S_KEYLOOK"}}],"Values":[[{"Literal":{"Value":"''"}}]]}}},{"DisplayName":"YES"}]}

		annotation SummarizationSetBy = Automatic

	column 'Hersteller ID' = ```
			
			    IF(
			        NOT( Details[Hersteller] = BLANK() )  ,
			        FORMAT( VALUE( Details[Hersteller] ) , "0000000000" ),
			        BLANK()
			    )
			```
		lineageTag: 3f1a5c05-2571-49b8-adab-a7fc6d58b17c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Purchase Order'
		dataType: string
		lineageTag: 91452bfa-d967-4ec8-8c8e-71c9b0cc0789
		summarizeBy: none
		sourceColumn: Purchase Order

		annotation SummarizationSetBy = Automatic

	column 'Country of dispatch (PO)'
		dataType: string
		lineageTag: c2edd85a-7bd7-4409-9c94-5c390ad35079
		summarizeBy: none
		sourceColumn: Country of dispatch (PO)

		annotation SummarizationSetBy = Automatic

	column Vendor
		dataType: string
		lineageTag: 4a5139a8-dcd5-455c-aeaf-d34291960b88
		summarizeBy: none
		sourceColumn: Vendor

		annotation SummarizationSetBy = Automatic

	column 'Sub Agency'
		dataType: string
		lineageTag: 61315f4f-afdc-4b1e-8684-e3734eab3a43
		summarizeBy: none
		sourceColumn: Sub Agency

		annotation SummarizationSetBy = Automatic

	column PO_conf_pcs
		dataType: int64
		formatString: 0
		lineageTag: aaa60d29-7561-4766-baba-88aeb404e1c4
		summarizeBy: sum
		sourceColumn: PO_conf_pcs

		annotation SummarizationSetBy = Automatic

	column 'Cancellation Reason'
		dataType: string
		lineageTag: fd8b64ff-0801-45aa-a8f8-47cb92e74f18
		summarizeBy: none
		sourceColumn: Cancellation Reason

		annotation SummarizationSetBy = Automatic

	column 'Actual Transport Chain'
		dataType: string
		lineageTag: 4e723d52-bda9-4b70-9738-4cb44772088c
		summarizeBy: none
		sourceColumn: Actual Transport Chain

		annotation SummarizationSetBy = Automatic

	column 'PO Date'
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 03580096-f96d-41d5-b8fa-4bab5dd645c9
		summarizeBy: none
		sourceColumn: PO Date

		variation Variation
			isDefault
			relationship: 0954dd16-56b2-4037-b52f-dc9fc2617b70
			defaultHierarchy: LocalDateTable_7eaf2c6e-5493-4a17-8583-23c6795d4478.Datumshierarchie

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Initial Transport Chain'
		dataType: string
		lineageTag: 3308496f-742f-4eb8-a029-e76d100062ea
		summarizeBy: none
		sourceColumn: Initial Transport Chain

		annotation SummarizationSetBy = Automatic

	column 'Date of Activation MFR'
		dataType: string
		lineageTag: e7a1a862-79b4-4f2e-b16b-a2dd6ac4f4d0
		summarizeBy: none
		sourceColumn: Date of Activation MFR

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Date of Activation Vendor'
		dataType: string
		lineageTag: c2ab404d-9bdf-446e-a807-6eaf7add77b6
		summarizeBy: none
		sourceColumn: Date of Activation Vendor

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Date of Payment'
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: e042e287-4547-4bd9-a7cf-87b75123a5c9
		summarizeBy: none
		sourceColumn: Date of Payment

		variation Variation
			isDefault
			relationship: b2785d50-16cf-48bf-a2fd-858db750bec2
			defaultHierarchy: LocalDateTable_4242dc97-ecc2-4f85-ba48-276e7bbbafba.Datumshierarchie

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column ALKW_Month
		dataType: string
		lineageTag: 8271439d-edfe-40a1-b1f9-da8746257a3a
		summarizeBy: none
		sourceColumn: ALKW_Month

		annotation SummarizationSetBy = Automatic

	column Ordersaison
		dataType: string
		lineageTag: f4edba35-12b4-468f-897c-fcf545b5c6e5
		summarizeBy: none
		sourceColumn: Ordersaison

		annotation SummarizationSetBy = Automatic

	column Saison_ALKW
		dataType: string
		lineageTag: d6f5e373-801e-4585-a56f-89134b253d02
		summarizeBy: none
		sourceColumn: Saison_ALKW

		annotation SummarizationSetBy = Automatic

	column Saison_ALKW_Month
		dataType: string
		lineageTag: 5c848697-398b-47d4-af73-24e93a2e96b6
		summarizeBy: none
		sourceColumn: Saison_ALKW_Month

		annotation SummarizationSetBy = Automatic

	column Saison_ALKW_Year
		dataType: string
		lineageTag: 17a37be9-30d1-407f-a777-674f55f96125
		summarizeBy: none
		sourceColumn: Saison_ALKW_Year

		annotation SummarizationSetBy = Automatic

	partition Details-71f5e97d-b110-409e-a25c-9898fd99a80a = m
		mode: import
		source =
				let
				    Quelle = Csv.Document(File.Contents("C:\Users\florianhaferkorn\OneDrive - Nagarro\Desktop\Details.csv"),[Delimiter=";", Columns=98, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Höher gestufte Header" = Table.PromoteHeaders(Quelle, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"ALKW_Month", type text}, {"Artikelvariante", type text}, {"Purchase Order Item", type text}, {"Purchase Order", type text}, {"HO_akt", type datetime}, {"HO_best", type datetime}, {"Country of dispatch (PO)", type text}, {"Vendor", type text}, {"Ordersaison", type text}, {"Saison_ALKW", type text}, {"Sub Agency", type text}, {"PO_conf_pcs", Int64.Type}, {"PO cancelled (pcs)PO cancelled (pcs)", Int64.Type}, {"PO overshipped (pcs)", Int64.Type}, {"PO shortshipped (pcs)", Int64.Type}, {"Delay in days excl. buffer", Int64.Type}, {"_SOL_FSHSYEAR", type text}, {"KPI2137", Int64.Type}, {"KPI2387", Int64.Type}, {"POconf_after_cxl_pcs", Int64.Type}, {"Saison_ALKW_Month", type text}, {"Cancellation Reason", type text}, {"PUR_REASON", type text}, {"PO_ship_intol_pcs", Int64.Type}, {"sample_bulk", type text}, {"RT_CONFMAT", type text}, {"Saison_ALKW_Month_", type text}, {"Saison_ALKW_Year", type text}, {"WE_DIR_Stk", Int64.Type}, {"Order Cluster", type text}, {"Season_Calendar", type datetime}, {"0DOC_DATE: KPI2215", type text}, {"Actual Transport Chain", type text}, {"CITY_MFR", type text}, {"CITY_VENDOR", type text}, {"PO Date", type datetime}, {"Date of activation_MFR", type text}, {"Date of activation_Vendor", type text}, {"Port of dispatch", type text}, {"Hersteller", type text}, {"Initial Transport Chain", type text}, {"Manufacturer", type text}, {"Liefertermin VZ", type text}, {"Delivery Date DC", type datetime}, {"Handover Status", type text}, {"COUNTRY_MFR", type text}, {"COUNTRY_VENDOR", type text}, {"STREET_MFR", type text}, {"STREET_VENDOR", type text}, {"Country of Dispatch", type text}, {"PP_FW_CURR", type text}, {"PP_HW_CURR", type text}, {"Nettopreis_Währung", type text}, {"HSP", Int64.Type}, {"Nettopreis", type number}, {"AGY_Comm_pre_calc", Int64.Type}, {"customscost_pre_calc", Int64.Type}, {"freightcost_pre_calc", type number}, {"Malus_pre_calc", Int64.Type}, {"PP_CALC_FW", type number}, {"PP_CALC_HW", type number}, {"samplecost_pre_calc", type number}, {"_BSOL_S_KEYLOOK", type text}, {"HC_CATIND1", type text}, {"KSCHL", type text}, {"Top 10", type text}, {"Key Look (Cluster)", type text}, {"Date of Activation MFR", type datetime}, {"Date of Activation Vendor", type datetime}, {"Date of Payment", type datetime}, {"Calculation Quantity", Int64.Type}}),
				    #"Gefilterte Zeilen" = Table.SelectRows(#"Geänderter Typ", each [Season_Calendar] > #datetime(2021, 12, 31, 0, 0, 0)),
				    #"Entfernte Spalten" = Table.RemoveColumns(#"Gefilterte Zeilen",{"Delay in days excl. buffer", "Saison_ALKW_Month_", "Order Cluster", "Season_Calendar", "Delivery Date DC", "Handover Status", "Country of Dispatch", "Top 10", "Key Look (Cluster)"}),
				    #"Columns removed by Measure Killer"= Table.RemoveColumns(#"Entfernte Spalten",{"0DOC_DATE: KPI2215", "PP_HW_CURR", "KPI2387", "PO_ship_intol_pcs", "_SOL_FSHSYEAR", "Nettopreis_Währung", "PUR_REASON", "Nettopreis", "Purchase Order Item", "Port of dispatch", "PP Ratio Target", "PO_conf_val (PP Ratio Target)", "Retail val", "WHSSP val €", "Exchange Rate (Plan)", "Exchange Rate (Calc.)", "COS Target", "COS_pre_calc_val (COS Target)", "Cluster Delay in Days", "PO_conf_val $ (PP_Calc)", "PO_conf_val € (pre_calc)", "PO_conf_val € (post_calc)", "PP Ratio Country Target (based on PY)", "PO_conf_val (PP Ratio Country Target based on PY)", "PO_pre_conf_pcs", "Initial Transport Mode", "Actual Transport Mode", "Identifier", "Identifier_2", "Year (HO_best)", "Month (HO_best)", "Ordersplit", "Delivery Date DC Week", "Delivery Date DC Year", "Delivery Date DC Month", "GB/NB", "Hersteller ID", "Calculation Quantity", "HC_CATIND1"}),
				    #"Geänderter Typ1" = Table.TransformColumnTypes(#"Columns removed by Measure Killer",{{"PO Date", type date}, {"Date of Activation MFR", type date}, {"Date of Activation Vendor", type date}, {"Date of Payment", type date}, {"HO_akt", type date}, {"HO_best", type date}}),
				    #"Gefilterte Zeilen1" = Table.SelectRows(#"Geänderter Typ1", each [Liefertermin VZ] <> null and [Liefertermin VZ] <> ""),
				    #"Entfernte Spalten1" = Table.RemoveColumns(#"Gefilterte Zeilen1",{"Date of activation_MFR", "Date of activation_Vendor"}),
				    #"Gefilterte Zeilen2" = Table.SelectRows(#"Entfernte Spalten1", each ([Saison_ALKW_Year] <> "2025")),
				    #"Entfernte Spalten2" = Table.RemoveColumns(#"Gefilterte Zeilen2",{"Manufacturer"})
				in
				    #"Entfernte Spalten2"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

