table Documentation_Measures
	lineageTag: c09d0d00-9ed5-4153-8353-14da8deb8be5

	column CATALOG_NAME
		dataType: string
		isHidden
		lineageTag: 075367cb-28a0-4b7b-aac3-fec8ef44284b
		summarizeBy: none
		sourceColumn: CATALOG_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MEASURE_NAME
		dataType: string
		lineageTag: 65cfaa6e-d9ac-46e4-9e5b-32db0ce59caa
		summarizeBy: none
		sourceColumn: MEASURE_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DESCRIPTION
		dataType: string
		lineageTag: 37482888-abb4-46e4-8ad8-24a8a3bd9ed6
		summarizeBy: none
		sourceColumn: DESCRIPTION

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EXPRESSION
		dataType: string
		isHidden
		lineageTag: 1bf40292-f0c0-49db-ac03-0c4f3e791bef
		summarizeBy: none
		sourceColumn: EXPRESSION

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MEASUREGROUP_NAME
		dataType: string
		isHidden
		lineageTag: 7c221bc6-5dcf-4ed1-9fba-4050511ac6ab
		summarizeBy: none
		sourceColumn: MEASUREGROUP_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MEASURE_DISPLAY_FOLDER
		dataType: string
		lineageTag: 7543507d-ec9b-4ffe-aff6-42ab585461a0
		summarizeBy: none
		sourceColumn: MEASURE_DISPLAY_FOLDER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DEFAULT_FORMAT_STRING
		dataType: string
		isHidden
		lineageTag: f0e226f8-09f1-4495-b145-586a73baa0c4
		summarizeBy: none
		sourceColumn: DEFAULT_FORMAT_STRING

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MEASURE_GUID
		dataType: string
		isHidden
		lineageTag: 6e051c77-5427-4c11-9d7b-3c65b12cfd5a
		summarizeBy: none
		sourceColumn: MEASURE_GUID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Documentation_Measures-fb0261b1-e422-4c6e-988a-f11238c96901 = m
		mode: import
		source =
				let
				    Quelle = SharePoint.Files("https://soliver.sharepoint.com/teams/O365_O365_VendorManagement", [ApiVersion = 15]),
				    #"Gefilterte Zeilen" = Table.SelectRows(Quelle, each ([Name] = "VM 2.0_Documentation_Measures.xlsx")),
				    #"VM 2 0_Documentation_Measures xlsx_https://soliver sharepoint com/teams/O365_O365_VendorManagement/Freigegebene Dokumente/General/Documentation/" = #"Gefilterte Zeilen"{[Name="VM 2.0_Documentation_Measures.xlsx",#"Folder Path"="https://soliver.sharepoint.com/teams/O365_O365_VendorManagement/Freigegebene Dokumente/General/Documentation/"]}[Content],
				    #"Importierte Excel-Arbeitsmappe" = Excel.Workbook(#"VM 2 0_Documentation_Measures xlsx_https://soliver sharepoint com/teams/O365_O365_VendorManagement/Freigegebene Dokumente/General/Documentation/"),
				    Query1_Sheet = #"Importierte Excel-Arbeitsmappe"{[Item="Query1",Kind="Sheet"]}[Data],
				    #"Höher gestufte Header" = Table.PromoteHeaders(Query1_Sheet, [PromoteAllScalars=true]),
				    #"Filter on visible measures" = Table.SelectRows(#"Höher gestufte Header", each ([MEASURE_IS_VISIBLE] = "True")),
				    #"Entfernte Spalten" = Table.RemoveColumns(#"Filter on visible measures",{"SCHEMA_NAME", "CUBE_NAME", "MEASURE_UNIQUE_NAME", "MEASURE_CAPTION", "MEASURE_AGGREGATOR", "DATA_TYPE", "NUMERIC_PRECISION", "NUMERIC_SCALE", "MEASURE_UNITS", "MEASURE_IS_VISIBLE", "LEVELS_LIST", "MEASURE_UNQUALIFIED_CAPTION", "MEASURE_NAME_SQL_COLUMN_NAME"}),
				    #"Filter on relevant Display Folder" = Table.SelectRows(#"Entfernte Spalten", each ([MEASURE_DISPLAY_FOLDER] <> "Description" and [MEASURE_DISPLAY_FOLDER] <> "Measures for Slicer (dashboard only!)" and [MEASURE_DISPLAY_FOLDER] <> "Ranking" and [MEASURE_DISPLAY_FOLDER] <> "Risk Management" and [MEASURE_DISPLAY_FOLDER] <> "Symbols (dashboard only!)" and [MEASURE_DISPLAY_FOLDER] <> "Target" and [MEASURE_DISPLAY_FOLDER] <> "Target Colors (dashboard only!)" and [MEASURE_DISPLAY_FOLDER] <> "_Not finalized" and [MEASURE_DISPLAY_FOLDER] <> "_RLS" and [MEASURE_DISPLAY_FOLDER] <> "_Slicer Measures (dashboard only!)" and [MEASURE_DISPLAY_FOLDER] <> "_Symbols (dashboard only!)" and [MEASURE_DISPLAY_FOLDER] <> "_Target Colors (dashboard only!)"))
				in
				    #"Filter on relevant Display Folder"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

