table 'Inspections (Centric)'
	lineageTag: f1eadde6-3f73-456e-b6da-d3193c6770a2

	column Inspection
		dataType: string
		lineageTag: 227f6cf3-c25d-4d87-8375-7e0a52e2da19
		summarizeBy: none
		sourceColumn: Inspection

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'MSMT Test Result'
		dataType: string
		lineageTag: 0f8ecd9b-eb69-4392-a837-4bd8a7a56d29
		summarizeBy: none
		sourceColumn: MSMT Test Result

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Optical Test Result'
		dataType: string
		lineageTag: 2d0029f9-fc43-4c31-9cb9-65126df7009c
		summarizeBy: none
		sourceColumn: Optical Test Result

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Wash Test Result'
		dataType: string
		lineageTag: bfe84805-d101-40d1-9519-eeb15e2507d1
		summarizeBy: none
		sourceColumn: Wash Test Result

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Major Defect Score'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7413a340-7da9-4b80-be99-cd930fc44a46
		summarizeBy: none
		sourceColumn: Major Defect Score

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Minor Defect Count'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d10559a9-092d-4762-a0c6-c40186694533
		summarizeBy: none
		sourceColumn: Minor Defect Count

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Minor Defect Score'
		dataType: int64
		isHidden
		lineageTag: 64ea874f-101b-47c6-b9df-935155b98dcd
		summarizeBy: none
		sourceColumn: Minor Defect Score

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Number of Green POMs'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3e6b568e-5bf1-4fd5-865a-de23b0c2d6df
		summarizeBy: none
		sourceColumn: Number of Green POMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Number of Orange POMs'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 08e8eeb1-0022-48f1-83d7-4085b583afd2
		summarizeBy: none
		sourceColumn: Number of Orange POMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Number of Red POMs'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 61bad962-6104-49a5-9d5a-6fdabe0054c0
		summarizeBy: none
		sourceColumn: Number of Red POMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Created
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 599965bc-390c-4812-9643-715fc2593313
		summarizeBy: none
		sourceColumn: Created

		variation Variation
			isDefault
			relationship: 2cfc02b5-bfca-47d6-9a5f-54241d15b33c
			defaultHierarchy: LocalDateTable_3a39c735-0f1a-48ae-b663-79bc264ab4f1.Datumshierarchie

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Modified
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: b2683c75-ca1b-42f4-b008-cb7aeb6368df
		summarizeBy: none
		sourceColumn: Modified

		variation Variation
			isDefault
			relationship: 2cf01f97-d13e-41fe-8560-cb35d27c190b
			defaultHierarchy: LocalDateTable_6c50a319-4c07-4f33-9333-af554cefe5c1.Datumshierarchie

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Style
		dataType: string
		isHidden
		lineageTag: 4b74d8c7-f7fd-4c7c-87ed-e334a2154b6a
		summarizeBy: none
		sourceColumn: Style

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Purchase Order'
		dataType: string
		isHidden
		lineageTag: 88974818-c9d3-4390-bc83-3b3d7b055105
		summarizeBy: none
		sourceColumn: Purchase Order

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 5bda0127-af9d-4981-988e-df97244efea8
		summarizeBy: none
		sourceColumn: State

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Defected Items'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 46b7f88d-3790-4b6f-8a91-99f4ffb09894
		summarizeBy: none
		sourceColumn: Defected Items

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Measured Qty'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6232532e-f0b2-4250-8bad-db920a937e68
		summarizeBy: none
		sourceColumn: Measured Qty

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Maximum Red POMs' = ```
			
			
			// Select and return Sample Size Category
			Var _SampleSizeCategories =
			    CALCULATETABLE(
			        SELECTCOLUMNS( 
			            'Measurement_AQL_2.5', 
			            "Sample Size", 'Measurement_AQL_2.5'[Sample Size] ),
			        FILTER(
			            ALL( 'Measurement_AQL_2.5' ),
			            'Measurement_AQL_2.5'[Sample Size] <= 'Inspections (Centric)'[Measured Qty]
			        )
			    )
			
			// Return maximum Major Count for closest sample size
			VAR _treatas =
			    TREATAS ( _SampleSizeCategories, 'Measurement_AQL_2.5'[Sample Size] )
			
			RETURN
			    IF(
			        NOT ISBLANK(CALCULATE ( MAX ( 'Measurement_AQL_2.5'[Major - Rejected] ), _treatas )),
			            CALCULATE ( MAX ( 'Measurement_AQL_2.5'[Major - Rejected] ), _treatas ),
			        1
			    )
			```
		isHidden
		formatString: #,0
		lineageTag: 5ea59728-f003-473e-86b8-1519386105b6
		summarizeBy: none

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = User

	column 'Maximum Orange POMs' = ```
			
			
			// Select and return Sample Size Category
			Var _SampleSizeCategories =
			    CALCULATETABLE(
			        SELECTCOLUMNS( 
			            'Measurement_AQL_2.5', 
			            "Sample Size", 'Measurement_AQL_2.5'[Sample Size] ),
			        FILTER(
			            ALL( 'Measurement_AQL_2.5' ),
			            'Measurement_AQL_2.5'[Sample Size] <= 'Inspections (Centric)'[Measured Qty]
			        )
			    )
			
			// Return maximum Minor Count for closest sample size
			VAR _treatas =
			    TREATAS ( _SampleSizeCategories, 'Measurement_AQL_2.5'[Sample Size] )
			
			RETURN
			    IF(
			        NOT ISBLANK(CALCULATE ( MAX ( 'Measurement_AQL_2.5'[Major - Rejected] ), _treatas )),
			            CALCULATE ( MAX ( 'Measurement_AQL_2.5'[Minor - Rejected] ), _treatas ),
			        1
			    )
			```
		isHidden
		formatString: #,0
		lineageTag: 8200447e-aa1a-4cc6-9113-acb14b96e4b0
		summarizeBy: none

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = User

	column 'Points RedPOMs' = ```
			
			    IF(
			        'Inspections (Centric)'[Number of Red POMs] > 'Inspections (Centric)'[Maximum Red POMs], 1,
			        0
			    )
			```
		isHidden
		formatString: 0
		lineageTag: 9cbbb7ad-c17a-4ac9-a505-1ee5af898d5a
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Points OrangePOMs' = ```
			
			    IF(
			        'Inspections (Centric)'[Number of Orange POMs] > 'Inspections (Centric)'[Maximum Orange POMs], 0.5,
			        0
			    )
			```
		isHidden
		formatString: 0.0
		lineageTag: a8c9b4e7-468e-47ac-a0ea-570c96c0c000
		summarizeBy: none

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = User

	column 'Points (MSMT)' = ```
			
			
			    SWITCH(
			        TRUE(),
			            'Inspections (Centric)'[Points RedPOMs] > 0, 1,
			            AND('Inspections (Centric)'[Points RedPOMs] < 1, 'Inspections (Centric)'[Points OrangePOMs] > 0), 0.5,
			            0
			    )
			```
		isHidden
		formatString: 0.00
		lineageTag: 18d4ca4c-43ad-4a28-ad90-7967faf4f009
		summarizeBy: none

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Points (Optical)' = ```
			
			    IF( 'Inspections (Centric)'[Optical Test Result] = "Failed" , 1 ,
			        IF( 'Inspections (Centric)'[Optical Test Result] = "Marginal" , 0.5 ,
			            0
			        )
			    )
			```
		isHidden
		formatString: #,0.00
		lineageTag: c7034185-0a0e-4e28-9146-c161207c52c5
		summarizeBy: none

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Template
		dataType: string
		lineageTag: 009d4cb1-6c88-4e74-a3b3-c6400a775f0b
		summarizeBy: none
		sourceColumn: Template

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Inspection Type'
		dataType: string
		lineageTag: ad646226-d55d-4d2a-beb1-567cbbbb5b56
		summarizeBy: none
		sourceColumn: Inspection Type

		annotation SummarizationSetBy = Automatic

	column 'Inspection ID'
		dataType: string
		lineageTag: 5bc0508a-fd21-4dc5-8f2f-b48992046744
		summarizeBy: none
		sourceColumn: Inspection ID

		annotation SummarizationSetBy = Automatic

	column 'FGI & IGI Check' =
			
			var _FGI = CALCULATE( DISTINCTCOUNT( 'Inspections (Centric)'[Inspection] ) , FILTER( ALLEXCEPT( 'Inspections (Centric)' , 'Inspections (Centric)'[Inspection] ) , 'Inspections (Centric)'[Inspection Type] = "FGI" ) )
			var _IGI = CALCULATE( DISTINCTCOUNT( 'Inspections (Centric)'[Inspection] ) , FILTER( ALLEXCEPT( 'Inspections (Centric)' , 'Inspections (Centric)'[Inspection] ) , 'Inspections (Centric)'[Inspection Type] = "IGI" ) )
			
			RETURN
			IF ( _FGI > 0 && _IGI > 0 , "YES", "NO" )
		lineageTag: 5ffce96d-2352-43bc-9a86-184ccef6d5e9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Inspections (Centric)-904ec7af-4d47-4c9d-8209-a5044afa4ce9' = m
		mode: import
		source =
				let
				    Quelle = Excel.Workbook(File.Contents(File_Source), null, true),
				    #"Inspections (Centric)_Sheet" = Quelle{[Item="Inspections (Centric)",Kind="Sheet"]}[Data],
				    #"Höher gestufte Header" = Table.PromoteHeaders(#"Inspections (Centric)_Sheet", [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"Inspection", type text}, {"MSMT Test Result", type text}, {"Optical Test Result", type text}, {"Wash Test Result", type text}, {"Final Result Test Score", Int64.Type}, {"Final Result Optical Test Score", Int64.Type}, {"Final Result Optical Test", Int64.Type}, {"Critical Defect Count", Int64.Type}, {"Critical Defect Score", Int64.Type}, {"Major Defect Count", Int64.Type}, {"Major Defects Share", Int64.Type}, {"Major Defect Score", Int64.Type}, {"Minor Defect Count", Int64.Type}, {"Minor Defects Share", Int64.Type}, {"Minor Defect Score", Int64.Type}, {"Percentage of Defected Qty", type number}, {"Defects", type text}, {"Number of Measured Key POMs", Int64.Type}, {"Total No of POM's out of tolerance", Int64.Type}, {"Number of Green POMs", Int64.Type}, {"Number of Orange POMs", Int64.Type}, {"Number of Red POMs", Int64.Type}, {"Created", type datetime}, {"Modified", type datetime}, {"Style", type text}, {"Purchase Order", type text}, {"Color", type text}, {"State", type text}, {"Season", type text}, {"Delivery Month", type text}, {"Actual Inspection Lot", Int64.Type}, {"Target Samples Count", Int64.Type}, {"Actual Samples Count", Int64.Type}, {"Defected Items", Int64.Type}, {"Defected Qty (pcs)", Int64.Type}, {"Requested Checking Qty", Int64.Type}, {"Measured Qty", Int64.Type}, {"Failed Qty", Int64.Type}, {"Failed Percentage", Int64.Type}, {"Failed Score", Int64.Type}, {"Percent of Green POMs", Int64.Type}, {"Percent of Orange POMs", Int64.Type}, {"Percent of Red POMs", Int64.Type}, {"Wash Test Results", type any}, {"Template", type text}, {"Inspection Type", type text}, {"Inspection ID", type text}}),
				    #"Columns removed by Measure Killer"= Table.RemoveColumns(#"Geänderter Typ",{"Percent of Orange POMs","Total No of POM's out of tolerance","Percent of Red POMs","Critical Defect Score","Final Result Test Score","Wash Test Results","Failed Qty","Critical Defect Count","Major Defects Share","Failed Score","Actual Samples Count","Delivery Month","Target Samples Count","Season","Defected Qty (pcs)","Defects","Actual Inspection Lot","Requested Checking Qty","Percentage of Defected Qty","Major Defect Count","Minor Defects Share","Color","Final Result Optical Test","Number of Measured Key POMs","Percent of Green POMs","Failed Percentage","Final Result Optical Test Score"})
				in
				#"Columns removed by Measure Killer"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

