table Targets_PPRatio_MC
	isHidden
	lineageTag: 4a7153c2-db3d-436c-94ab-b3b2c14c4eb7

	column 'Gültig ab'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 92ec7688-cad3-4216-b331-7e56642ba554
		summarizeBy: none
		sourceColumn: Gültig ab

		variation Variation
			isDefault
			relationship: 14c60124-e0ad-47ed-aae9-ec3075807b1d
			defaultHierarchy: LocalDateTable_ef8a8ab9-5445-4306-9cd7-3028cfb0f9b5.Datumshierarchie

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Gültig bis'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 3a855043-0b2d-442e-b548-68202bb9de82
		summarizeBy: none
		sourceColumn: Gültig bis

		variation Variation
			isDefault
			relationship: 16b35e11-29c2-43fe-90fd-a5381ea77316
			defaultHierarchy: LocalDateTable_a88c5a92-4edf-4501-83a3-201efd5ed99a.Datumshierarchie

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Koll.art'
		dataType: string
		isHidden
		lineageTag: 2504caa0-e9f5-42a9-8075-755fb5cee445
		summarizeBy: none
		sourceColumn: Koll.art

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Hauptklass
		dataType: string
		isHidden
		lineageTag: cb7bb470-2ecf-4b8e-9d36-5dd3103418fb
		summarizeBy: none
		sourceColumn: Hauptklass

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Betrag
		dataType: double
		isHidden
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 8a7c1ce8-087b-46dd-86a6-80797c684adc
		summarizeBy: none
		sourceColumn: Betrag

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Brand
		dataType: string
		lineageTag: 6e24ff26-0ca4-48b1-82a9-7921ec212bb7
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 80e45236-cf03-46d0-8428-31537981c539
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Line
		dataType: string
		lineageTag: 7fb68b06-1776-4dbb-aeda-d50c9f3b88f1
		summarizeBy: none
		sourceColumn: Line

		annotation SummarizationSetBy = Automatic

	partition Targets_PPRatio_MC-43c82bd0-6a1e-4e11-9db0-d75f3d8e17b3 = m
		mode: import
		source =
				let
				    Quelle = Excel.Workbook(File.Contents(File_Source), null, true),
				    Targets_PPRatio_MC_Sheet = Quelle{[Item="Targets_PPRatio_MC",Kind="Sheet"]}[Data],
				    #"Höher gestufte Header" = Table.PromoteHeaders(Targets_PPRatio_MC_Sheet, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"Brand", type text}, {"Gender", type text}, {"Line", type text}, {"Gültig ab", type date}, {"Gültig bis", type date}, {"Year", type text}, {"Koll.art", type text}, {"Hauptklass", type text}, {"Betrag", type number}}),
				    #"Columns removed by Measure Killer"= Table.RemoveColumns(#"Geänderter Typ",{"Year"})
				in
				#"Columns removed by Measure Killer"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

