table Targets_COS
	isHidden
	lineageTag: c7f5afe5-b9d8-4ac1-aecf-387bc28ae167

	column 'Gültig ab'
		dataType: dateTime
		isHidden
		formatString: dd.mm.yyyy
		lineageTag: c2e4c5ac-a863-4109-a0df-94643b9f807e
		summarizeBy: none
		sourceColumn: Gültig ab

		variation Variation
			isDefault
			relationship: cd33dfb3-856e-4e9d-a000-69754b7ece74
			defaultHierarchy: LocalDateTable_7519937f-4396-45fb-b51b-57b86bbe018a.Datumshierarchie

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Gültig bis'
		dataType: dateTime
		isHidden
		formatString: dd.mm.yyyy
		lineageTag: 452ebc03-a3db-4645-8110-8e43779240da
		summarizeBy: none
		sourceColumn: Gültig bis

		variation Variation
			isDefault
			relationship: ecc66bda-b2fc-4e8f-9943-5c511cb94e8f
			defaultHierarchy: LocalDateTable_46c4a9f8-7414-4dd4-b077-e267d3acc476.Datumshierarchie

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Koll.art'
		dataType: string
		isHidden
		lineageTag: d34621cc-f6c3-4fa1-ae00-8165d609f5ec
		summarizeBy: none
		sourceColumn: Koll.art

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Betrag
		dataType: double
		isHidden
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 8fc54bb9-5269-481e-bdec-79e8ee1314e5
		summarizeBy: none
		sourceColumn: Betrag

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Brand
		dataType: string
		lineageTag: 1c1de72e-a62d-4b46-9072-c42b468799e3
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: d10d8f12-4e89-4b9e-a104-b4e824ad9bbf
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Line
		dataType: string
		lineageTag: 58cf6b6b-e000-42db-aa99-e92ea7b0a79e
		summarizeBy: none
		sourceColumn: Line

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 6cdb7b48-910d-42eb-8136-6d811d47079a
		summarizeBy: sum
		sourceColumn: Year

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition Targets_COS-6b785ae2-a1c7-4574-b325-7bbeeed0734a = m
		mode: import
		source =
				let
				    Quelle = Excel.Workbook(File.Contents(File_Source), null, true),
				    Targets_COS_Sheet = Quelle{[Item="Targets_COS",Kind="Sheet"]}[Data],
				    #"Höher gestufte Header" = Table.PromoteHeaders(Targets_COS_Sheet, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"Brand", type text}, {"Gender", type text}, {"Line", type text}, {"Year", type text}, {"Gültig ab", type date}, {"Gültig bis", type date}, {"Koll.art", type text}, {"Betrag", type number}})
				in
				    #"Geänderter Typ"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

