table Targets_PPRatio
	isHidden
	lineageTag: c4da28ab-f313-43e0-ae8e-c79d6f0be261

	column 'Gültig ab'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 7b350885-7f23-4019-870d-e04e25567f59
		summarizeBy: none
		sourceColumn: Gültig ab

		variation Variation
			isDefault
			relationship: a8e3919e-b951-47f3-a18a-64bf99170b45
			defaultHierarchy: LocalDateTable_e85507f7-6dd8-4f65-b442-9f556599c19d.Datumshierarchie

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Gültig bis'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 15a6777d-80a4-4c25-90b0-b58af48accb7
		summarizeBy: none
		sourceColumn: Gültig bis

		variation Variation
			isDefault
			relationship: 02c0f67f-b024-4533-b17d-b78dac785ca1
			defaultHierarchy: LocalDateTable_b703c5e8-3e83-4351-a4ca-b71c666cf68d.Datumshierarchie

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Koll.art'
		dataType: string
		isHidden
		lineageTag: 0376b94e-4d60-4a1c-969f-60bb06b100b4
		summarizeBy: none
		sourceColumn: Koll.art

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Hauptklass
		dataType: string
		isHidden
		lineageTag: e36fe9c1-af96-48de-b560-dfdd89b6f4b8
		summarizeBy: none
		sourceColumn: Hauptklass

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AL/R
		dataType: string
		isHidden
		lineageTag: eee80dd9-5810-4ec1-a2f9-28598c403e9c
		summarizeBy: none
		sourceColumn: AL/R

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Betrag
		dataType: double
		isHidden
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 192c1226-c42d-46ce-ba27-16cb2a70568b
		summarizeBy: none
		sourceColumn: Betrag

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Brand
		dataType: string
		lineageTag: 5dfd69bb-34e9-4a9e-8191-2089dc9bae5d
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 235cac47-0e28-4abc-b90c-13f6f03564e7
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Line
		dataType: string
		lineageTag: f6af81ee-c3c3-4dd6-b37a-78545120b072
		summarizeBy: none
		sourceColumn: Line

		annotation SummarizationSetBy = Automatic

	partition Targets_PPRatio-e14241a9-2c26-4e1f-bc37-9252155d075c = m
		mode: import
		source =
				let
				    Quelle = Excel.Workbook(File.Contents(File_Source), null, true),
				    Targets_PPRatio_Sheet = Quelle{[Item="Targets_PPRatio",Kind="Sheet"]}[Data],
				    #"Höher gestufte Header" = Table.PromoteHeaders(Targets_PPRatio_Sheet, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"Brand", type text}, {"Gender", type text}, {"Line", type text}, {"Gültig ab", type date}, {"Gültig bis", type date}, {"Year", type text}, {"Koll.art", type text}, {"Hauptklass", type text}, {"AL/R", type text}, {"Betrag", type number}}),
				    #"Columns removed by Measure Killer"= Table.RemoveColumns(#"Geänderter Typ",{"Year"})
				in
				#"Columns removed by Measure Killer"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

