table Targets_PPRatio_BGL
	isHidden
	lineageTag: 137ac2be-a571-4686-8db7-169781e42f5d

	column 'Koll.art'
		dataType: string
		isHidden
		lineageTag: 6cd3b7f9-eb6e-4256-95e9-1294862d7c4f
		summarizeBy: none
		sourceColumn: Koll.art

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Betrag
		dataType: double
		isHidden
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: d0c0416b-05d4-4715-b699-b32cf7e91790
		summarizeBy: none
		sourceColumn: Betrag

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Gültig ab'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 0837c667-0e1d-4a2e-8d00-a1fbe8e57e95
		summarizeBy: none
		sourceColumn: Gültig ab

		variation Variation
			isDefault
			relationship: ac88e07b-5539-42f7-9d97-8609da78ab27
			defaultHierarchy: LocalDateTable_7932ee6d-8455-42f2-aa1d-e5a3941c3fb0.Datumshierarchie

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Gültig bis'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 31141d53-8d08-4e66-b30f-3d4e4f86fcce
		summarizeBy: none
		sourceColumn: Gültig bis

		variation Variation
			isDefault
			relationship: eeac1da7-a3b4-4753-b2cb-dc9f505b6494
			defaultHierarchy: LocalDateTable_8c871043-d34a-4c01-b0f6-497edf1b249d.Datumshierarchie

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Brand
		dataType: string
		lineageTag: dcc42530-f601-42e4-b44f-fcfbf9270a58
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 692a3f57-32bf-426e-8974-d958a9165e97
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Line
		dataType: string
		lineageTag: 6f4788f0-0835-48a3-98c9-9b293b21096c
		summarizeBy: none
		sourceColumn: Line

		annotation SummarizationSetBy = Automatic

	partition Targets_PPRatio_BGL = m
		mode: import
		source =
				let
				    Quelle = Excel.Workbook(File.Contents(File_Source), null, true),
				    Targets_PPRatio_BGL_Sheet = Quelle{[Item="Targets_PPRatio_BGL",Kind="Sheet"]}[Data],
				    #"Höher gestufte Header" = Table.PromoteHeaders(Targets_PPRatio_BGL_Sheet, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"Brand", type text}, {"Gender", type text}, {"Line", type text}, {"Koll.art", type text}, {"Betrag", type number}, {"Gültig ab", type date}, {"Gültig bis", type date}, {"Year", type text}}),
				    #"Columns removed by Measure Killer"= Table.RemoveColumns(#"Geänderter Typ",{"Year"})
				in
				#"Columns removed by Measure Killer"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

