/**
 * Theme Bundle Generator — Creates a ZIP archive containing all theme formats.
 *
 * Uses fflate (8KB, zero-dep) for ZIP generation.
 */

import { zipSync, strToU8 } from 'fflate';
import type { ThemeConfig } from '@/lib/store/project-store';
import { generateCssCustomProperties } from './export-css';
import { generateTailwindConfig } from './export-tailwind';
import { generateJsonConfig } from './export-json';

const README_CONTENT = `# ALUCA Theme Bundle

This ZIP contains your exported theme in multiple formats:

## Files

- **theme.css** — CSS Custom Properties (:root variables)
- **tailwind.config.ts** — Tailwind CSS config snippet with theme.extend
- **theme.json** — Portable JSON config for Evidence.dev, Power BI, or custom apps

## Usage

### CSS Custom Properties
\`\`\`html
<link rel="stylesheet" href="theme.css" />
\`\`\`

### Tailwind
Copy the \`theme.extend\` block into your \`tailwind.config.ts\`.

### JSON
Import the JSON file in your application:
\`\`\`typescript
import theme from './theme.json';
\`\`\`

---
Generated by ALUCA Studio — Brand Lab
`;

export function generateThemeBundle(theme: ThemeConfig): Uint8Array {
  const files: Record<string, Uint8Array> = {
    'theme.css': strToU8(generateCssCustomProperties(theme)),
    'tailwind.config.ts': strToU8(generateTailwindConfig(theme)),
    'theme.json': strToU8(generateJsonConfig(theme)),
    'README.md': strToU8(README_CONTENT),
  };

  return zipSync(files, { level: 6 });
}
